<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\City;

class CitiesSeeder extends Seeder
{
    public function run(): void
    {

        City::create(['id' => 1, 'federal_states_id' => 1, 'name' => 'Maroa', 'capital' => 0, ]);
		City::create(['id' => 2, 'federal_states_id' => 1, 'name' => 'Puerto Ayacucho', 'capital' => 1, ]);
		City::create(['id' => 3, 'federal_states_id' => 1, 'name' => 'San Fernando de Atabapo', 'capital' => 0, ]);
		City::create(['id' => 4, 'federal_states_id' => 2, 'name' => 'Anaco', 'capital' => 0, ]);
		City::create(['id' => 5, 'federal_states_id' => 2, 'name' => 'Aragua de Barcelona', 'capital' => 0, ]);
		City::create(['id' => 6, 'federal_states_id' => 2, 'name' => 'Barcelona', 'capital' => 1, ]);
		City::create(['id' => 7, 'federal_states_id' => 2, 'name' => 'Boca de Uchire', 'capital' => 0, ]);
		City::create(['id' => 8, 'federal_states_id' => 2, 'name' => 'Cantaura', 'capital' => 0, ]);
		City::create(['id' => 9, 'federal_states_id' => 2, 'name' => 'Clarines', 'capital' => 0, ]);
		City::create(['id' => 10, 'federal_states_id' => 2, 'name' => 'El Chaparro', 'capital' => 0, ]);
		City::create(['id' => 11, 'federal_states_id' => 2, 'name' => 'El Pao Anzoátegui', 'capital' => 0, ]);
		City::create(['id' => 12, 'federal_states_id' => 2, 'name' => 'El Tigre', 'capital' => 0, ]);
		City::create(['id' => 13, 'federal_states_id' => 2, 'name' => 'El Tigrito', 'capital' => 0, ]);
		City::create(['id' => 14, 'federal_states_id' => 2, 'name' => 'Guanape', 'capital' => 0, ]);
		City::create(['id' => 15, 'federal_states_id' => 2, 'name' => 'Guanta', 'capital' => 0, ]);
		City::create(['id' => 16, 'federal_states_id' => 2, 'name' => 'Lechería', 'capital' => 0, ]);
		City::create(['id' => 17, 'federal_states_id' => 2, 'name' => 'Onoto', 'capital' => 0, ]);
		City::create(['id' => 18, 'federal_states_id' => 2, 'name' => 'Pariaguán', 'capital' => 0, ]);
		City::create(['id' => 19, 'federal_states_id' => 2, 'name' => 'Píritu', 'capital' => 0, ]);
		City::create(['id' => 20, 'federal_states_id' => 2, 'name' => 'Puerto La Cruz', 'capital' => 0, ]);
		City::create(['id' => 21, 'federal_states_id' => 2, 'name' => 'Puerto Píritu', 'capital' => 0, ]);
		City::create(['id' => 22, 'federal_states_id' => 2, 'name' => 'Sabana de Uchire', 'capital' => 0, ]);
		City::create(['id' => 23, 'federal_states_id' => 2, 'name' => 'San Mateo Anzoátegui', 'capital' => 0, ]);
		City::create(['id' => 24, 'federal_states_id' => 2, 'name' => 'San Pablo Anzoátegui', 'capital' => 0, ]);
		City::create(['id' => 25, 'federal_states_id' => 2, 'name' => 'San Tomé', 'capital' => 0, ]);
		City::create(['id' => 26, 'federal_states_id' => 2, 'name' => 'Santa Ana de Anzoátegui', 'capital' => 0, ]);
		City::create(['id' => 27, 'federal_states_id' => 2, 'name' => 'Santa Fe Anzoátegui', 'capital' => 0, ]);
		City::create(['id' => 28, 'federal_states_id' => 2, 'name' => 'Santa Rosa', 'capital' => 0, ]);
		City::create(['id' => 29, 'federal_states_id' => 2, 'name' => 'Soledad', 'capital' => 0, ]);
		City::create(['id' => 30, 'federal_states_id' => 2, 'name' => 'Urica', 'capital' => 0, ]);
		City::create(['id' => 31, 'federal_states_id' => 2, 'name' => 'Valle de Guanape', 'capital' => 0, ]);
		City::create(['id' => 43, 'federal_states_id' => 3, 'name' => 'Achaguas', 'capital' => 0, ]);
		City::create(['id' => 44, 'federal_states_id' => 3, 'name' => 'Biruaca', 'capital' => 0, ]);
		City::create(['id' => 45, 'federal_states_id' => 3, 'name' => 'Bruzual', 'capital' => 0, ]);
		City::create(['id' => 46, 'federal_states_id' => 3, 'name' => 'El Amparo', 'capital' => 0, ]);
		City::create(['id' => 47, 'federal_states_id' => 3, 'name' => 'El Nula', 'capital' => 0, ]);
		City::create(['id' => 48, 'federal_states_id' => 3, 'name' => 'Elorza', 'capital' => 0, ]);
		City::create(['id' => 49, 'federal_states_id' => 3, 'name' => 'Guasdualito', 'capital' => 0, ]);
		City::create(['id' => 50, 'federal_states_id' => 3, 'name' => 'Mantecal', 'capital' => 0, ]);
		City::create(['id' => 51, 'federal_states_id' => 3, 'name' => 'Puerto Páez', 'capital' => 0, ]);
		City::create(['id' => 52, 'federal_states_id' => 3, 'name' => 'San Fernando de Apure', 'capital' => 1, ]);
		City::create(['id' => 53, 'federal_states_id' => 3, 'name' => 'San Juan de Payara', 'capital' => 0, ]);
		City::create(['id' => 54, 'federal_states_id' => 4, 'name' => 'Barbacoas', 'capital' => 0, ]);
		City::create(['id' => 55, 'federal_states_id' => 4, 'name' => 'Cagua', 'capital' => 0, ]);
		City::create(['id' => 56, 'federal_states_id' => 4, 'name' => 'Camatagua', 'capital' => 0, ]);
		City::create(['id' => 58, 'federal_states_id' => 4, 'name' => 'Choroní', 'capital' => 0, ]);
		City::create(['id' => 59, 'federal_states_id' => 4, 'name' => 'Colonia Tovar', 'capital' => 0, ]);
		City::create(['id' => 60, 'federal_states_id' => 4, 'name' => 'El Consejo', 'capital' => 0, ]);
		City::create(['id' => 61, 'federal_states_id' => 4, 'name' => 'La Victoria', 'capital' => 0, ]);
		City::create(['id' => 62, 'federal_states_id' => 4, 'name' => 'Las Tejerías', 'capital' => 0, ]);
		City::create(['id' => 63, 'federal_states_id' => 4, 'name' => 'Magdaleno', 'capital' => 0, ]);
		City::create(['id' => 64, 'federal_states_id' => 4, 'name' => 'Maracay', 'capital' => 1, ]);
		City::create(['id' => 65, 'federal_states_id' => 4, 'name' => 'Ocumare de La Costa', 'capital' => 0, ]);
		City::create(['id' => 66, 'federal_states_id' => 4, 'name' => 'Palo Negro', 'capital' => 0, ]);
		City::create(['id' => 67, 'federal_states_id' => 4, 'name' => 'San Casimiro', 'capital' => 0, ]);
		City::create(['id' => 68, 'federal_states_id' => 4, 'name' => 'San Mateo', 'capital' => 0, ]);
		City::create(['id' => 69, 'federal_states_id' => 4, 'name' => 'San Sebastián', 'capital' => 0, ]);
		City::create(['id' => 70, 'federal_states_id' => 4, 'name' => 'Santa Cruz de Aragua', 'capital' => 0, ]);
		City::create(['id' => 71, 'federal_states_id' => 4, 'name' => 'Tocorón', 'capital' => 0, ]);
		City::create(['id' => 72, 'federal_states_id' => 4, 'name' => 'Turmero', 'capital' => 0, ]);
		City::create(['id' => 73, 'federal_states_id' => 4, 'name' => 'Villa de Cura', 'capital' => 0, ]);
		City::create(['id' => 74, 'federal_states_id' => 4, 'name' => 'Zuata', 'capital' => 0, ]);
		City::create(['id' => 75, 'federal_states_id' => 5, 'name' => 'Barinas', 'capital' => 1, ]);
		City::create(['id' => 76, 'federal_states_id' => 5, 'name' => 'Barinitas', 'capital' => 0, ]);
		City::create(['id' => 77, 'federal_states_id' => 5, 'name' => 'Barrancas', 'capital' => 0, ]);
		City::create(['id' => 78, 'federal_states_id' => 5, 'name' => 'Calderas', 'capital' => 0, ]);
		City::create(['id' => 79, 'federal_states_id' => 5, 'name' => 'Capitanejo', 'capital' => 0, ]);
		City::create(['id' => 80, 'federal_states_id' => 5, 'name' => 'Models\city Bolivia', 'capital' => 0, ]);
		City::create(['id' => 81, 'federal_states_id' => 5, 'name' => 'El Cantón', 'capital' => 0, ]);
		City::create(['id' => 82, 'federal_states_id' => 5, 'name' => 'Las Veguitas', 'capital' => 0, ]);
		City::create(['id' => 83, 'federal_states_id' => 5, 'name' => 'Libertad de Barinas', 'capital' => 0, ]);
		City::create(['id' => 84, 'federal_states_id' => 5, 'name' => 'Sabaneta', 'capital' => 0, ]);
		City::create(['id' => 85, 'federal_states_id' => 5, 'name' => 'Santa Bárbara de Barinas', 'capital' => 0, ]);
		City::create(['id' => 86, 'federal_states_id' => 5, 'name' => 'Socopó', 'capital' => 0, ]);
		City::create(['id' => 87, 'federal_states_id' => 6, 'name' => 'Caicara del Orinoco', 'capital' => 0, ]);
		City::create(['id' => 88, 'federal_states_id' => 6, 'name' => 'Canaima', 'capital' => 0, ]);
		City::create(['id' => 89, 'federal_states_id' => 6, 'name' => 'Models\city Bolívar', 'capital' => 1, ]);
		City::create(['id' => 90, 'federal_states_id' => 6, 'name' => 'Models\city Piar', 'capital' => 0, ]);
		City::create(['id' => 91, 'federal_states_id' => 6, 'name' => 'El Callao', 'capital' => 0, ]);
		City::create(['id' => 92, 'federal_states_id' => 6, 'name' => 'El Dorado', 'capital' => 0, ]);
		City::create(['id' => 93, 'federal_states_id' => 6, 'name' => 'El Manteco', 'capital' => 0, ]);
		City::create(['id' => 94, 'federal_states_id' => 6, 'name' => 'El Palmar', 'capital' => 0, ]);
		City::create(['id' => 95, 'federal_states_id' => 6, 'name' => 'El Pao', 'capital' => 0, ]);
		City::create(['id' => 96, 'federal_states_id' => 6, 'name' => 'Guasipati', 'capital' => 0, ]);
		City::create(['id' => 97, 'federal_states_id' => 6, 'name' => 'Guri', 'capital' => 0, ]);
		City::create(['id' => 98, 'federal_states_id' => 6, 'name' => 'La Paragua', 'capital' => 0, ]);
		City::create(['id' => 99, 'federal_states_id' => 6, 'name' => 'Matanzas', 'capital' => 0, ]);
		City::create(['id' => 100, 'federal_states_id' => 6, 'name' => 'Puerto Ordaz', 'capital' => 0, ]);
		City::create(['id' => 101, 'federal_states_id' => 6, 'name' => 'San Félix', 'capital' => 0, ]);
		City::create(['id' => 102, 'federal_states_id' => 6, 'name' => 'Santa Elena de Uairén', 'capital' => 0, ]);
		City::create(['id' => 103, 'federal_states_id' => 6, 'name' => 'Tumeremo', 'capital' => 0, ]);
		City::create(['id' => 104, 'federal_states_id' => 6, 'name' => 'Unare', 'capital' => 0, ]);
		City::create(['id' => 105, 'federal_states_id' => 6, 'name' => 'Upata', 'capital' => 0, ]);
		City::create(['id' => 106, 'federal_states_id' => 7, 'name' => 'Bejuma', 'capital' => 0, ]);
		City::create(['id' => 107, 'federal_states_id' => 7, 'name' => 'Belén', 'capital' => 0, ]);
		City::create(['id' => 108, 'federal_states_id' => 7, 'name' => 'Campo de Carabobo', 'capital' => 0, ]);
		City::create(['id' => 109, 'federal_states_id' => 7, 'name' => 'Canoabo', 'capital' => 0, ]);
		City::create(['id' => 110, 'federal_states_id' => 7, 'name' => 'Central Tacarigua', 'capital' => 0, ]);
		City::create(['id' => 111, 'federal_states_id' => 7, 'name' => 'Chirgua', 'capital' => 0, ]);
		City::create(['id' => 112, 'federal_states_id' => 7, 'name' => 'Models\city Alianza', 'capital' => 0, ]);
		City::create(['id' => 113, 'federal_states_id' => 7, 'name' => 'El Palito', 'capital' => 0, ]);
		City::create(['id' => 114, 'federal_states_id' => 7, 'name' => 'Guacara', 'capital' => 0, ]);
		City::create(['id' => 115, 'federal_states_id' => 7, 'name' => 'Guigue', 'capital' => 0, ]);
		City::create(['id' => 116, 'federal_states_id' => 7, 'name' => 'Las Trincheras', 'capital' => 0, ]);
		City::create(['id' => 117, 'federal_states_id' => 7, 'name' => 'Los Guayos', 'capital' => 0, ]);
		City::create(['id' => 118, 'federal_states_id' => 7, 'name' => 'Mariara', 'capital' => 0, ]);
		City::create(['id' => 119, 'federal_states_id' => 7, 'name' => 'Miranda', 'capital' => 0, ]);
		City::create(['id' => 120, 'federal_states_id' => 7, 'name' => 'Montalbán', 'capital' => 0, ]);
		City::create(['id' => 121, 'federal_states_id' => 7, 'name' => 'Morón', 'capital' => 0, ]);
		City::create(['id' => 122, 'federal_states_id' => 7, 'name' => 'Naguanagua', 'capital' => 0, ]);
		City::create(['id' => 123, 'federal_states_id' => 7, 'name' => 'Puerto Cabello', 'capital' => 0, ]);
		City::create(['id' => 124, 'federal_states_id' => 7, 'name' => 'San Joaquín', 'capital' => 0, ]);
		City::create(['id' => 125, 'federal_states_id' => 7, 'name' => 'Tocuyito', 'capital' => 0, ]);
		City::create(['id' => 126, 'federal_states_id' => 7, 'name' => 'Urama', 'capital' => 0, ]);
		City::create(['id' => 127, 'federal_states_id' => 7, 'name' => 'Valencia', 'capital' => 1, ]);
		City::create(['id' => 128, 'federal_states_id' => 7, 'name' => 'Vigirimita', 'capital' => 0, ]);
		City::create(['id' => 129, 'federal_states_id' => 8, 'name' => 'Aguirre', 'capital' => 0, ]);
		City::create(['id' => 130, 'federal_states_id' => 8, 'name' => 'Apartaderos Cojedes', 'capital' => 0, ]);
		City::create(['id' => 131, 'federal_states_id' => 8, 'name' => 'Arismendi', 'capital' => 0, ]);
		City::create(['id' => 132, 'federal_states_id' => 8, 'name' => 'Camuriquito', 'capital' => 0, ]);
		City::create(['id' => 133, 'federal_states_id' => 8, 'name' => 'El Baúl', 'capital' => 0, ]);
		City::create(['id' => 134, 'federal_states_id' => 8, 'name' => 'El Limón', 'capital' => 0, ]);
		City::create(['id' => 135, 'federal_states_id' => 8, 'name' => 'El Pao Cojedes', 'capital' => 0, ]);
		City::create(['id' => 136, 'federal_states_id' => 8, 'name' => 'El Socorro', 'capital' => 0, ]);
		City::create(['id' => 137, 'federal_states_id' => 8, 'name' => 'La Aguadita', 'capital' => 0, ]);
		City::create(['id' => 138, 'federal_states_id' => 8, 'name' => 'Las Vegas', 'capital' => 0, ]);
		City::create(['id' => 139, 'federal_states_id' => 8, 'name' => 'Libertad de Cojedes', 'capital' => 0, ]);
		City::create(['id' => 140, 'federal_states_id' => 8, 'name' => 'Mapuey', 'capital' => 0, ]);
		City::create(['id' => 141, 'federal_states_id' => 8, 'name' => 'Piñedo', 'capital' => 0, ]);
		City::create(['id' => 142, 'federal_states_id' => 8, 'name' => 'Samancito', 'capital' => 0, ]);
		City::create(['id' => 143, 'federal_states_id' => 8, 'name' => 'San Carlos', 'capital' => 1, ]);
		City::create(['id' => 144, 'federal_states_id' => 8, 'name' => 'Sucre', 'capital' => 0, ]);
		City::create(['id' => 145, 'federal_states_id' => 8, 'name' => 'Tinaco', 'capital' => 0, ]);
		City::create(['id' => 146, 'federal_states_id' => 8, 'name' => 'Tinaquillo', 'capital' => 0, ]);
		City::create(['id' => 147, 'federal_states_id' => 8, 'name' => 'Vallecito', 'capital' => 0, ]);
		City::create(['id' => 148, 'federal_states_id' => 9, 'name' => 'Tucupita', 'capital' => 1, ]);
		City::create(['id' => 149, 'federal_states_id' => 24, 'name' => 'Caracas', 'capital' => 1, ]);
		City::create(['id' => 150, 'federal_states_id' => 24, 'name' => 'El Junquito', 'capital' => 0, ]);
		City::create(['id' => 151, 'federal_states_id' => 10, 'name' => 'Adícora', 'capital' => 0, ]);
		City::create(['id' => 152, 'federal_states_id' => 10, 'name' => 'Boca de Aroa', 'capital' => 0, ]);
		City::create(['id' => 153, 'federal_states_id' => 10, 'name' => 'Cabure', 'capital' => 0, ]);
		City::create(['id' => 154, 'federal_states_id' => 10, 'name' => 'Capadare', 'capital' => 0, ]);
		City::create(['id' => 155, 'federal_states_id' => 10, 'name' => 'Capatárida', 'capital' => 0, ]);
		City::create(['id' => 156, 'federal_states_id' => 10, 'name' => 'Chichiriviche', 'capital' => 0, ]);
		City::create(['id' => 157, 'federal_states_id' => 10, 'name' => 'Churuguara', 'capital' => 0, ]);
		City::create(['id' => 158, 'federal_states_id' => 10, 'name' => 'Coro', 'capital' => 1, ]);
		City::create(['id' => 159, 'federal_states_id' => 10, 'name' => 'Cumarebo', 'capital' => 0, ]);
		City::create(['id' => 160, 'federal_states_id' => 10, 'name' => 'Dabajuro', 'capital' => 0, ]);
		City::create(['id' => 161, 'federal_states_id' => 10, 'name' => 'Judibana', 'capital' => 0, ]);
		City::create(['id' => 162, 'federal_states_id' => 10, 'name' => 'La Cruz de Taratara', 'capital' => 0, ]);
		City::create(['id' => 163, 'federal_states_id' => 10, 'name' => 'La Vela de Coro', 'capital' => 0, ]);
		City::create(['id' => 164, 'federal_states_id' => 10, 'name' => 'Los Taques', 'capital' => 0, ]);
		City::create(['id' => 165, 'federal_states_id' => 10, 'name' => 'Maparari', 'capital' => 0, ]);
		City::create(['id' => 166, 'federal_states_id' => 10, 'name' => 'Mene de Mauroa', 'capital' => 0, ]);
		City::create(['id' => 167, 'federal_states_id' => 10, 'name' => 'Mirimire', 'capital' => 0, ]);
		City::create(['id' => 168, 'federal_states_id' => 10, 'name' => 'Pedregal', 'capital' => 0, ]);
		City::create(['id' => 169, 'federal_states_id' => 10, 'name' => 'Píritu Falcón', 'capital' => 0, ]);
		City::create(['id' => 170, 'federal_states_id' => 10, 'name' => 'Pueblo Nuevo Falcón', 'capital' => 0, ]);
		City::create(['id' => 171, 'federal_states_id' => 10, 'name' => 'Puerto Cumarebo', 'capital' => 0, ]);
		City::create(['id' => 172, 'federal_states_id' => 10, 'name' => 'Punta Cardón', 'capital' => 0, ]);
		City::create(['id' => 173, 'federal_states_id' => 10, 'name' => 'Punto Fijo', 'capital' => 0, ]);
		City::create(['id' => 174, 'federal_states_id' => 10, 'name' => 'San Juan de Los Cayos', 'capital' => 0, ]);
		City::create(['id' => 175, 'federal_states_id' => 10, 'name' => 'San Luis', 'capital' => 0, ]);
		City::create(['id' => 176, 'federal_states_id' => 10, 'name' => 'Santa Ana Falcón', 'capital' => 0, ]);
		City::create(['id' => 177, 'federal_states_id' => 10, 'name' => 'Santa Cruz De Bucaral', 'capital' => 0, ]);
		City::create(['id' => 178, 'federal_states_id' => 10, 'name' => 'Tocopero', 'capital' => 0, ]);
		City::create(['id' => 179, 'federal_states_id' => 10, 'name' => 'Tocuyo de La Costa', 'capital' => 0, ]);
		City::create(['id' => 180, 'federal_states_id' => 10, 'name' => 'Tucacas', 'capital' => 0, ]);
		City::create(['id' => 181, 'federal_states_id' => 10, 'name' => 'Yaracal', 'capital' => 0, ]);
		City::create(['id' => 182, 'federal_states_id' => 11, 'name' => 'Altagracia de Orituco', 'capital' => 0, ]);
		City::create(['id' => 183, 'federal_states_id' => 11, 'name' => 'Cabruta', 'capital' => 0, ]);
		City::create(['id' => 184, 'federal_states_id' => 11, 'name' => 'Calabozo', 'capital' => 0, ]);
		City::create(['id' => 185, 'federal_states_id' => 11, 'name' => 'Camaguán', 'capital' => 0, ]);
		City::create(['id' => 196, 'federal_states_id' => 11, 'name' => 'Chaguaramas Guárico', 'capital' => 0, ]);
		City::create(['id' => 197, 'federal_states_id' => 11, 'name' => 'El Socorro', 'capital' => 0, ]);
		City::create(['id' => 198, 'federal_states_id' => 11, 'name' => 'El Sombrero', 'capital' => 0, ]);
		City::create(['id' => 199, 'federal_states_id' => 11, 'name' => 'Las Mercedes de Los Llanos', 'capital' => 0, ]);
		City::create(['id' => 200, 'federal_states_id' => 11, 'name' => 'Lezama', 'capital' => 0, ]);
		City::create(['id' => 201, 'federal_states_id' => 11, 'name' => 'Onoto', 'capital' => 0, ]);
		City::create(['id' => 202, 'federal_states_id' => 11, 'name' => 'Ortíz', 'capital' => 0, ]);
		City::create(['id' => 203, 'federal_states_id' => 11, 'name' => 'San José de Guaribe', 'capital' => 0, ]);
		City::create(['id' => 204, 'federal_states_id' => 11, 'name' => 'San Juan de Los Morros', 'capital' => 1, ]);
		City::create(['id' => 205, 'federal_states_id' => 11, 'name' => 'San Rafael de Laya', 'capital' => 0, ]);
		City::create(['id' => 206, 'federal_states_id' => 11, 'name' => 'Santa María de Ipire', 'capital' => 0, ]);
		City::create(['id' => 207, 'federal_states_id' => 11, 'name' => 'Tucupido', 'capital' => 0, ]);
		City::create(['id' => 208, 'federal_states_id' => 11, 'name' => 'Valle de La Pascua', 'capital' => 0, ]);
		City::create(['id' => 209, 'federal_states_id' => 11, 'name' => 'Zaraza', 'capital' => 0, ]);
		City::create(['id' => 210, 'federal_states_id' => 12, 'name' => 'Aguada Grande', 'capital' => 0, ]);
		City::create(['id' => 211, 'federal_states_id' => 12, 'name' => 'Atarigua', 'capital' => 0, ]);
		City::create(['id' => 212, 'federal_states_id' => 12, 'name' => 'Barquisimeto', 'capital' => 1, ]);
		City::create(['id' => 213, 'federal_states_id' => 12, 'name' => 'Bobare', 'capital' => 0, ]);
		City::create(['id' => 214, 'federal_states_id' => 12, 'name' => 'Cabudare', 'capital' => 0, ]);
		City::create(['id' => 215, 'federal_states_id' => 12, 'name' => 'Carora', 'capital' => 0, ]);
		City::create(['id' => 216, 'federal_states_id' => 12, 'name' => 'Cubiro', 'capital' => 0, ]);
		City::create(['id' => 217, 'federal_states_id' => 12, 'name' => 'Cují', 'capital' => 0, ]);
		City::create(['id' => 218, 'federal_states_id' => 12, 'name' => 'Duaca', 'capital' => 0, ]);
		City::create(['id' => 219, 'federal_states_id' => 12, 'name' => 'El Manzano', 'capital' => 0, ]);
		City::create(['id' => 220, 'federal_states_id' => 12, 'name' => 'El Tocuyo', 'capital' => 0, ]);
		City::create(['id' => 221, 'federal_states_id' => 12, 'name' => 'Guaríco', 'capital' => 0, ]);
		City::create(['id' => 222, 'federal_states_id' => 12, 'name' => 'Humocaro Alto', 'capital' => 0, ]);
		City::create(['id' => 223, 'federal_states_id' => 12, 'name' => 'Humocaro Bajo', 'capital' => 0, ]);
		City::create(['id' => 224, 'federal_states_id' => 12, 'name' => 'La Miel', 'capital' => 0, ]);
		City::create(['id' => 225, 'federal_states_id' => 12, 'name' => 'Moroturo', 'capital' => 0, ]);
		City::create(['id' => 226, 'federal_states_id' => 12, 'name' => 'Quíbor', 'capital' => 0, ]);
		City::create(['id' => 227, 'federal_states_id' => 12, 'name' => 'Río Claro', 'capital' => 0, ]);
		City::create(['id' => 228, 'federal_states_id' => 12, 'name' => 'Sanare', 'capital' => 0, ]);
		City::create(['id' => 229, 'federal_states_id' => 12, 'name' => 'Santa Inés', 'capital' => 0, ]);
		City::create(['id' => 230, 'federal_states_id' => 12, 'name' => 'Sarare', 'capital' => 0, ]);
		City::create(['id' => 231, 'federal_states_id' => 12, 'name' => 'Siquisique', 'capital' => 0, ]);
		City::create(['id' => 232, 'federal_states_id' => 12, 'name' => 'Tintorero', 'capital' => 0, ]);
		City::create(['id' => 233, 'federal_states_id' => 13, 'name' => 'Apartaderos Mérida', 'capital' => 0, ]);
		City::create(['id' => 234, 'federal_states_id' => 13, 'name' => 'Arapuey', 'capital' => 0, ]);
		City::create(['id' => 235, 'federal_states_id' => 13, 'name' => 'Bailadores', 'capital' => 0, ]);
		City::create(['id' => 236, 'federal_states_id' => 13, 'name' => 'Caja Seca', 'capital' => 0, ]);
		City::create(['id' => 237, 'federal_states_id' => 13, 'name' => 'Canaguá', 'capital' => 0, ]);
		City::create(['id' => 238, 'federal_states_id' => 13, 'name' => 'Chachopo', 'capital' => 0, ]);
		City::create(['id' => 239, 'federal_states_id' => 13, 'name' => 'Chiguara', 'capital' => 0, ]);
		City::create(['id' => 240, 'federal_states_id' => 13, 'name' => 'Ejido', 'capital' => 0, ]);
		City::create(['id' => 241, 'federal_states_id' => 13, 'name' => 'El Vigía', 'capital' => 0, ]);
		City::create(['id' => 242, 'federal_states_id' => 13, 'name' => 'La Azulita', 'capital' => 0, ]);
		City::create(['id' => 243, 'federal_states_id' => 13, 'name' => 'La Playa', 'capital' => 0, ]);
		City::create(['id' => 244, 'federal_states_id' => 13, 'name' => 'Lagunillas Mérida', 'capital' => 0, ]);
		City::create(['id' => 245, 'federal_states_id' => 13, 'name' => 'Mérida', 'capital' => 1, ]);
		City::create(['id' => 246, 'federal_states_id' => 13, 'name' => 'Mesa de Bolívar', 'capital' => 0, ]);
		City::create(['id' => 247, 'federal_states_id' => 13, 'name' => 'Mucuchíes', 'capital' => 0, ]);
		City::create(['id' => 248, 'federal_states_id' => 13, 'name' => 'Mucujepe', 'capital' => 0, ]);
		City::create(['id' => 249, 'federal_states_id' => 13, 'name' => 'Mucuruba', 'capital' => 0, ]);
		City::create(['id' => 250, 'federal_states_id' => 13, 'name' => 'Nueva Bolivia', 'capital' => 0, ]);
		City::create(['id' => 251, 'federal_states_id' => 13, 'name' => 'Palmarito', 'capital' => 0, ]);
		City::create(['id' => 252, 'federal_states_id' => 13, 'name' => 'Pueblo Llano', 'capital' => 0, ]);
		City::create(['id' => 253, 'federal_states_id' => 13, 'name' => 'Santa Cruz de Mora', 'capital' => 0, ]);
		City::create(['id' => 254, 'federal_states_id' => 13, 'name' => 'Santa Elena de Arenales', 'capital' => 0, ]);
		City::create(['id' => 255, 'federal_states_id' => 13, 'name' => 'Santo Domingo', 'capital' => 0, ]);
		City::create(['id' => 256, 'federal_states_id' => 13, 'name' => 'Tabáy', 'capital' => 0, ]);
		City::create(['id' => 257, 'federal_states_id' => 13, 'name' => 'Timotes', 'capital' => 0, ]);
		City::create(['id' => 258, 'federal_states_id' => 13, 'name' => 'Torondoy', 'capital' => 0, ]);
		City::create(['id' => 259, 'federal_states_id' => 13, 'name' => 'Tovar', 'capital' => 0, ]);
		City::create(['id' => 260, 'federal_states_id' => 13, 'name' => 'Tucani', 'capital' => 0, ]);
		City::create(['id' => 261, 'federal_states_id' => 13, 'name' => 'Zea', 'capital' => 0, ]);
		City::create(['id' => 262, 'federal_states_id' => 14, 'name' => 'Araguita', 'capital' => 0, ]);
		City::create(['id' => 263, 'federal_states_id' => 14, 'name' => 'Carrizal', 'capital' => 0, ]);
		City::create(['id' => 264, 'federal_states_id' => 14, 'name' => 'Caucagua', 'capital' => 0, ]);
		City::create(['id' => 265, 'federal_states_id' => 14, 'name' => 'Chaguaramas Miranda', 'capital' => 0, ]);
		City::create(['id' => 266, 'federal_states_id' => 14, 'name' => 'Charallave', 'capital' => 0, ]);
		City::create(['id' => 267, 'federal_states_id' => 14, 'name' => 'Chirimena', 'capital' => 0, ]);
		City::create(['id' => 268, 'federal_states_id' => 14, 'name' => 'Chuspa', 'capital' => 0, ]);
		City::create(['id' => 269, 'federal_states_id' => 14, 'name' => 'Cúa', 'capital' => 0, ]);
		City::create(['id' => 270, 'federal_states_id' => 14, 'name' => 'Cupira', 'capital' => 0, ]);
		City::create(['id' => 271, 'federal_states_id' => 14, 'name' => 'Curiepe', 'capital' => 0, ]);
		City::create(['id' => 272, 'federal_states_id' => 14, 'name' => 'El Guapo', 'capital' => 0, ]);
		City::create(['id' => 273, 'federal_states_id' => 14, 'name' => 'El Jarillo', 'capital' => 0, ]);
		City::create(['id' => 274, 'federal_states_id' => 14, 'name' => 'Filas de Mariche', 'capital' => 0, ]);
		City::create(['id' => 275, 'federal_states_id' => 14, 'name' => 'Guarenas', 'capital' => 0, ]);
		City::create(['id' => 276, 'federal_states_id' => 14, 'name' => 'Guatire', 'capital' => 0, ]);
		City::create(['id' => 277, 'federal_states_id' => 14, 'name' => 'Higuerote', 'capital' => 0, ]);
		City::create(['id' => 278, 'federal_states_id' => 14, 'name' => 'Los Anaucos', 'capital' => 0, ]);
		City::create(['id' => 279, 'federal_states_id' => 14, 'name' => 'Los Teques', 'capital' => 1, ]);
		City::create(['id' => 280, 'federal_states_id' => 14, 'name' => 'Ocumare del Tuy', 'capital' => 0, ]);
		City::create(['id' => 281, 'federal_states_id' => 14, 'name' => 'Panaquire', 'capital' => 0, ]);
		City::create(['id' => 282, 'federal_states_id' => 14, 'name' => 'Paracotos', 'capital' => 0, ]);
		City::create(['id' => 283, 'federal_states_id' => 14, 'name' => 'Río Chico', 'capital' => 0, ]);
		City::create(['id' => 284, 'federal_states_id' => 14, 'name' => 'San Antonio de Los Altos', 'capital' => 0, ]);
		City::create(['id' => 285, 'federal_states_id' => 14, 'name' => 'San Diego de Los Altos', 'capital' => 0, ]);
		City::create(['id' => 286, 'federal_states_id' => 14, 'name' => 'San Fernando del Guapo', 'capital' => 0, ]);
		City::create(['id' => 287, 'federal_states_id' => 14, 'name' => 'San Francisco de Yare', 'capital' => 0, ]);
		City::create(['id' => 288, 'federal_states_id' => 14, 'name' => 'San José de Los Altos', 'capital' => 0, ]);
		City::create(['id' => 289, 'federal_states_id' => 14, 'name' => 'San José de Río Chico', 'capital' => 0, ]);
		City::create(['id' => 290, 'federal_states_id' => 14, 'name' => 'San Pedro de Los Altos', 'capital' => 0, ]);
		City::create(['id' => 291, 'federal_states_id' => 14, 'name' => 'Santa Lucía', 'capital' => 0, ]);
		City::create(['id' => 292, 'federal_states_id' => 14, 'name' => 'Santa Teresa', 'capital' => 0, ]);
		City::create(['id' => 293, 'federal_states_id' => 14, 'name' => 'Tacarigua de La Laguna', 'capital' => 0, ]);
		City::create(['id' => 294, 'federal_states_id' => 14, 'name' => 'Tacarigua de Mamporal', 'capital' => 0, ]);
		City::create(['id' => 295, 'federal_states_id' => 14, 'name' => 'Tácata', 'capital' => 0, ]);
		City::create(['id' => 296, 'federal_states_id' => 14, 'name' => 'Turumo', 'capital' => 0, ]);
		City::create(['id' => 297, 'federal_states_id' => 15, 'name' => 'Aguasay', 'capital' => 0, ]);
		City::create(['id' => 298, 'federal_states_id' => 15, 'name' => 'Aragua de Maturín', 'capital' => 0, ]);
		City::create(['id' => 299, 'federal_states_id' => 15, 'name' => 'Barrancas del Orinoco', 'capital' => 0, ]);
		City::create(['id' => 300, 'federal_states_id' => 15, 'name' => 'Caicara de Maturín', 'capital' => 0, ]);
		City::create(['id' => 301, 'federal_states_id' => 15, 'name' => 'Caripe', 'capital' => 0, ]);
		City::create(['id' => 302, 'federal_states_id' => 15, 'name' => 'Caripito', 'capital' => 0, ]);
		City::create(['id' => 303, 'federal_states_id' => 15, 'name' => 'Chaguaramal', 'capital' => 0, ]);
		City::create(['id' => 305, 'federal_states_id' => 15, 'name' => 'Chaguaramas Monagas', 'capital' => 0, ]);
		City::create(['id' => 307, 'federal_states_id' => 15, 'name' => 'El Furrial', 'capital' => 0, ]);
		City::create(['id' => 308, 'federal_states_id' => 15, 'name' => 'El Tejero', 'capital' => 0, ]);
		City::create(['id' => 309, 'federal_states_id' => 15, 'name' => 'Jusepín', 'capital' => 0, ]);
		City::create(['id' => 310, 'federal_states_id' => 15, 'name' => 'La Toscana', 'capital' => 0, ]);
		City::create(['id' => 311, 'federal_states_id' => 15, 'name' => 'Maturín', 'capital' => 1, ]);
		City::create(['id' => 312, 'federal_states_id' => 15, 'name' => 'Miraflores', 'capital' => 0, ]);
		City::create(['id' => 313, 'federal_states_id' => 15, 'name' => 'Punta de Mata', 'capital' => 0, ]);
		City::create(['id' => 314, 'federal_states_id' => 15, 'name' => 'Quiriquire', 'capital' => 0, ]);
		City::create(['id' => 315, 'federal_states_id' => 15, 'name' => 'San Antonio de Maturín', 'capital' => 0, ]);
		City::create(['id' => 316, 'federal_states_id' => 15, 'name' => 'San Vicente Monagas', 'capital' => 0, ]);
		City::create(['id' => 317, 'federal_states_id' => 15, 'name' => 'Santa Bárbara', 'capital' => 0, ]);
		City::create(['id' => 318, 'federal_states_id' => 15, 'name' => 'Temblador', 'capital' => 0, ]);
		City::create(['id' => 319, 'federal_states_id' => 15, 'name' => 'Teresen', 'capital' => 0, ]);
		City::create(['id' => 320, 'federal_states_id' => 15, 'name' => 'Uracoa', 'capital' => 0, ]);
		City::create(['id' => 321, 'federal_states_id' => 16, 'name' => 'Altagracia', 'capital' => 0, ]);
		City::create(['id' => 322, 'federal_states_id' => 16, 'name' => 'Boca de Pozo', 'capital' => 0, ]);
		City::create(['id' => 323, 'federal_states_id' => 16, 'name' => 'Boca de Río', 'capital' => 0, ]);
		City::create(['id' => 324, 'federal_states_id' => 16, 'name' => 'El Espinal', 'capital' => 0, ]);
		City::create(['id' => 325, 'federal_states_id' => 16, 'name' => 'El Valle del Espíritu Santo', 'capital' => 0, ]);
		City::create(['id' => 326, 'federal_states_id' => 16, 'name' => 'El Yaque', 'capital' => 0, ]);
		City::create(['id' => 327, 'federal_states_id' => 16, 'name' => 'Juangriego', 'capital' => 0, ]);
		City::create(['id' => 328, 'federal_states_id' => 16, 'name' => 'La Asunción', 'capital' => 1, ]);
		City::create(['id' => 329, 'federal_states_id' => 16, 'name' => 'La Guardia', 'capital' => 0, ]);
		City::create(['id' => 330, 'federal_states_id' => 16, 'name' => 'Pampatar', 'capital' => 0, ]);
		City::create(['id' => 331, 'federal_states_id' => 16, 'name' => 'Porlamar', 'capital' => 0, ]);
		City::create(['id' => 332, 'federal_states_id' => 16, 'name' => 'Puerto Fermín', 'capital' => 0, ]);
		City::create(['id' => 333, 'federal_states_id' => 16, 'name' => 'Punta de Piedras', 'capital' => 0, ]);
		City::create(['id' => 334, 'federal_states_id' => 16, 'name' => 'San Francisco de Macanao', 'capital' => 0, ]);
		City::create(['id' => 335, 'federal_states_id' => 16, 'name' => 'San Juan Bautista', 'capital' => 0, ]);
		City::create(['id' => 336, 'federal_states_id' => 16, 'name' => 'San Pedro de Coche', 'capital' => 0, ]);
		City::create(['id' => 337, 'federal_states_id' => 16, 'name' => 'Santa Ana de Nueva Esparta', 'capital' => 0, ]);
		City::create(['id' => 338, 'federal_states_id' => 16, 'name' => 'Villa Rosa', 'capital' => 0, ]);
		City::create(['id' => 339, 'federal_states_id' => 17, 'name' => 'Acarigua', 'capital' => 0, ]);
		City::create(['id' => 340, 'federal_states_id' => 17, 'name' => 'Agua Blanca', 'capital' => 0, ]);
		City::create(['id' => 341, 'federal_states_id' => 17, 'name' => 'Araure', 'capital' => 0, ]);
		City::create(['id' => 342, 'federal_states_id' => 17, 'name' => 'Biscucuy', 'capital' => 0, ]);
		City::create(['id' => 343, 'federal_states_id' => 17, 'name' => 'Boconoito', 'capital' => 0, ]);
		City::create(['id' => 344, 'federal_states_id' => 17, 'name' => 'Campo Elías', 'capital' => 0, ]);
		City::create(['id' => 345, 'federal_states_id' => 17, 'name' => 'Chabasquén', 'capital' => 0, ]);
		City::create(['id' => 346, 'federal_states_id' => 17, 'name' => 'Guanare', 'capital' => 1, ]);
		City::create(['id' => 347, 'federal_states_id' => 17, 'name' => 'Guanarito', 'capital' => 0, ]);
		City::create(['id' => 348, 'federal_states_id' => 17, 'name' => 'La Aparición', 'capital' => 0, ]);
		City::create(['id' => 349, 'federal_states_id' => 17, 'name' => 'La Misión', 'capital' => 0, ]);
		City::create(['id' => 350, 'federal_states_id' => 17, 'name' => 'Mesa de Cavacas', 'capital' => 0, ]);
		City::create(['id' => 351, 'federal_states_id' => 17, 'name' => 'Ospino', 'capital' => 0, ]);
		City::create(['id' => 352, 'federal_states_id' => 17, 'name' => 'Papelón', 'capital' => 0, ]);
		City::create(['id' => 353, 'federal_states_id' => 17, 'name' => 'Payara', 'capital' => 0, ]);
		City::create(['id' => 354, 'federal_states_id' => 17, 'name' => 'Pimpinela', 'capital' => 0, ]);
		City::create(['id' => 355, 'federal_states_id' => 17, 'name' => 'Píritu de Portuguesa', 'capital' => 0, ]);
		City::create(['id' => 356, 'federal_states_id' => 17, 'name' => 'San Rafael de Onoto', 'capital' => 0, ]);
		City::create(['id' => 357, 'federal_states_id' => 17, 'name' => 'Santa Rosalía', 'capital' => 0, ]);
		City::create(['id' => 358, 'federal_states_id' => 17, 'name' => 'Turén', 'capital' => 0, ]);
		City::create(['id' => 359, 'federal_states_id' => 18, 'name' => 'Altos de Sucre', 'capital' => 0, ]);
		City::create(['id' => 360, 'federal_states_id' => 18, 'name' => 'Araya', 'capital' => 0, ]);
		City::create(['id' => 361, 'federal_states_id' => 18, 'name' => 'Cariaco', 'capital' => 0, ]);
		City::create(['id' => 362, 'federal_states_id' => 18, 'name' => 'Carúpano', 'capital' => 0, ]);
		City::create(['id' => 363, 'federal_states_id' => 18, 'name' => 'Casanay', 'capital' => 0, ]);
		City::create(['id' => 364, 'federal_states_id' => 18, 'name' => 'Cumaná', 'capital' => 1, ]);
		City::create(['id' => 365, 'federal_states_id' => 18, 'name' => 'Cumanacoa', 'capital' => 0, ]);
		City::create(['id' => 366, 'federal_states_id' => 18, 'name' => 'El Morro Puerto Santo', 'capital' => 0, ]);
		City::create(['id' => 367, 'federal_states_id' => 18, 'name' => 'El Pilar', 'capital' => 0, ]);
		City::create(['id' => 368, 'federal_states_id' => 18, 'name' => 'El Poblado', 'capital' => 0, ]);
		City::create(['id' => 369, 'federal_states_id' => 18, 'name' => 'Guaca', 'capital' => 0, ]);
		City::create(['id' => 370, 'federal_states_id' => 18, 'name' => 'Guiria', 'capital' => 0, ]);
		City::create(['id' => 371, 'federal_states_id' => 18, 'name' => 'Irapa', 'capital' => 0, ]);
		City::create(['id' => 372, 'federal_states_id' => 18, 'name' => 'Manicuare', 'capital' => 0, ]);
		City::create(['id' => 373, 'federal_states_id' => 18, 'name' => 'Mariguitar', 'capital' => 0, ]);
		City::create(['id' => 374, 'federal_states_id' => 18, 'name' => 'Río Caribe', 'capital' => 0, ]);
		City::create(['id' => 375, 'federal_states_id' => 18, 'name' => 'San Antonio del Golfo', 'capital' => 0, ]);
		City::create(['id' => 376, 'federal_states_id' => 18, 'name' => 'San José de Aerocuar', 'capital' => 0, ]);
		City::create(['id' => 377, 'federal_states_id' => 18, 'name' => 'San Vicente de Sucre', 'capital' => 0, ]);
		City::create(['id' => 378, 'federal_states_id' => 18, 'name' => 'Santa Fe de Sucre', 'capital' => 0, ]);
		City::create(['id' => 379, 'federal_states_id' => 18, 'name' => 'Tunapuy', 'capital' => 0, ]);
		City::create(['id' => 380, 'federal_states_id' => 18, 'name' => 'Yaguaraparo', 'capital' => 0, ]);
		City::create(['id' => 381, 'federal_states_id' => 18, 'name' => 'Yoco', 'capital' => 0, ]);
		City::create(['id' => 382, 'federal_states_id' => 19, 'name' => 'Abejales', 'capital' => 0, ]);
		City::create(['id' => 383, 'federal_states_id' => 19, 'name' => 'Borota', 'capital' => 0, ]);
		City::create(['id' => 384, 'federal_states_id' => 19, 'name' => 'Bramon', 'capital' => 0, ]);
		City::create(['id' => 385, 'federal_states_id' => 19, 'name' => 'Capacho', 'capital' => 0, ]);
		City::create(['id' => 386, 'federal_states_id' => 19, 'name' => 'Colón', 'capital' => 0, ]);
		City::create(['id' => 387, 'federal_states_id' => 19, 'name' => 'Coloncito', 'capital' => 0, ]);
		City::create(['id' => 388, 'federal_states_id' => 19, 'name' => 'Cordero', 'capital' => 0, ]);
		City::create(['id' => 389, 'federal_states_id' => 19, 'name' => 'El Cobre', 'capital' => 0, ]);
		City::create(['id' => 390, 'federal_states_id' => 19, 'name' => 'El Pinal', 'capital' => 0, ]);
		City::create(['id' => 391, 'federal_states_id' => 19, 'name' => 'Independencia', 'capital' => 0, ]);
		City::create(['id' => 392, 'federal_states_id' => 19, 'name' => 'La Fría', 'capital' => 0, ]);
		City::create(['id' => 393, 'federal_states_id' => 19, 'name' => 'La Grita', 'capital' => 0, ]);
		City::create(['id' => 394, 'federal_states_id' => 19, 'name' => 'La Pedrera', 'capital' => 0, ]);
		City::create(['id' => 395, 'federal_states_id' => 19, 'name' => 'La Tendida', 'capital' => 0, ]);
		City::create(['id' => 396, 'federal_states_id' => 19, 'name' => 'Las Delicias', 'capital' => 0, ]);
		City::create(['id' => 397, 'federal_states_id' => 19, 'name' => 'Las Hernández', 'capital' => 0, ]);
		City::create(['id' => 398, 'federal_states_id' => 19, 'name' => 'Lobatera', 'capital' => 0, ]);
		City::create(['id' => 399, 'federal_states_id' => 19, 'name' => 'Michelena', 'capital' => 0, ]);
		City::create(['id' => 400, 'federal_states_id' => 19, 'name' => 'Palmira', 'capital' => 0, ]);
		City::create(['id' => 401, 'federal_states_id' => 19, 'name' => 'Pregonero', 'capital' => 0, ]);
		City::create(['id' => 402, 'federal_states_id' => 19, 'name' => 'Queniquea', 'capital' => 0, ]);
		City::create(['id' => 403, 'federal_states_id' => 19, 'name' => 'Rubio', 'capital' => 0, ]);
		City::create(['id' => 404, 'federal_states_id' => 19, 'name' => 'San Antonio del Tachira', 'capital' => 0, ]);
		City::create(['id' => 405, 'federal_states_id' => 19, 'name' => 'San Cristobal', 'capital' => 1, ]);
		City::create(['id' => 406, 'federal_states_id' => 19, 'name' => 'San José de Bolívar', 'capital' => 0, ]);
		City::create(['id' => 407, 'federal_states_id' => 19, 'name' => 'San Josecito', 'capital' => 0, ]);
		City::create(['id' => 408, 'federal_states_id' => 19, 'name' => 'San Pedro del Río', 'capital' => 0, ]);
		City::create(['id' => 409, 'federal_states_id' => 19, 'name' => 'Santa Ana Táchira', 'capital' => 0, ]);
		City::create(['id' => 410, 'federal_states_id' => 19, 'name' => 'Seboruco', 'capital' => 0, ]);
		City::create(['id' => 411, 'federal_states_id' => 19, 'name' => 'Táriba', 'capital' => 0, ]);
		City::create(['id' => 412, 'federal_states_id' => 19, 'name' => 'Umuquena', 'capital' => 0, ]);
		City::create(['id' => 413, 'federal_states_id' => 19, 'name' => 'Ureña', 'capital' => 0, ]);
		City::create(['id' => 414, 'federal_states_id' => 20, 'name' => 'Batatal', 'capital' => 0, ]);
		City::create(['id' => 415, 'federal_states_id' => 20, 'name' => 'Betijoque', 'capital' => 0, ]);
		City::create(['id' => 416, 'federal_states_id' => 20, 'name' => 'Boconó', 'capital' => 0, ]);
		City::create(['id' => 417, 'federal_states_id' => 20, 'name' => 'Carache', 'capital' => 0, ]);
		City::create(['id' => 418, 'federal_states_id' => 20, 'name' => 'Chejende', 'capital' => 0, ]);
		City::create(['id' => 419, 'federal_states_id' => 20, 'name' => 'Cuicas', 'capital' => 0, ]);
		City::create(['id' => 420, 'federal_states_id' => 20, 'name' => 'El Dividive', 'capital' => 0, ]);
		City::create(['id' => 421, 'federal_states_id' => 20, 'name' => 'El Jaguito', 'capital' => 0, ]);
		City::create(['id' => 422, 'federal_states_id' => 20, 'name' => 'Escuque', 'capital' => 0, ]);
		City::create(['id' => 423, 'federal_states_id' => 20, 'name' => 'Isnotú', 'capital' => 0, ]);
		City::create(['id' => 424, 'federal_states_id' => 20, 'name' => 'Jajó', 'capital' => 0, ]);
		City::create(['id' => 425, 'federal_states_id' => 20, 'name' => 'La Ceiba', 'capital' => 0, ]);
		City::create(['id' => 426, 'federal_states_id' => 20, 'name' => 'La Concepción de Trujllo', 'capital' => 0, ]);
		City::create(['id' => 427, 'federal_states_id' => 20, 'name' => 'La Mesa de Esnujaque', 'capital' => 0, ]);
		City::create(['id' => 428, 'federal_states_id' => 20, 'name' => 'La Puerta', 'capital' => 0, ]);
		City::create(['id' => 429, 'federal_states_id' => 20, 'name' => 'La Quebrada', 'capital' => 0, ]);
		City::create(['id' => 430, 'federal_states_id' => 20, 'name' => 'Mendoza Fría', 'capital' => 0, ]);
		City::create(['id' => 431, 'federal_states_id' => 20, 'name' => 'Meseta de Chimpire', 'capital' => 0, ]);
		City::create(['id' => 432, 'federal_states_id' => 20, 'name' => 'Monay', 'capital' => 0, ]);
		City::create(['id' => 433, 'federal_states_id' => 20, 'name' => 'Motatán', 'capital' => 0, ]);
		City::create(['id' => 434, 'federal_states_id' => 20, 'name' => 'Pampán', 'capital' => 0, ]);
		City::create(['id' => 435, 'federal_states_id' => 20, 'name' => 'Pampanito', 'capital' => 0, ]);
		City::create(['id' => 436, 'federal_states_id' => 20, 'name' => 'Sabana de Mendoza', 'capital' => 0, ]);
		City::create(['id' => 437, 'federal_states_id' => 20, 'name' => 'San Lázaro', 'capital' => 0, ]);
		City::create(['id' => 438, 'federal_states_id' => 20, 'name' => 'Santa Ana de Trujillo', 'capital' => 0, ]);
		City::create(['id' => 439, 'federal_states_id' => 20, 'name' => 'Tostós', 'capital' => 0, ]);
		City::create(['id' => 440, 'federal_states_id' => 20, 'name' => 'Trujillo', 'capital' => 1, ]);
		City::create(['id' => 441, 'federal_states_id' => 20, 'name' => 'Valera', 'capital' => 0, ]);
		City::create(['id' => 442, 'federal_states_id' => 21, 'name' => 'Carayaca', 'capital' => 0, ]);
		City::create(['id' => 443, 'federal_states_id' => 21, 'name' => 'Litoral', 'capital' => 0, ]);
		City::create(['id' => 444, 'federal_states_id' => 25, 'name' => 'Archipiélago Los Roques', 'capital' => 0, ]);
		City::create(['id' => 445, 'federal_states_id' => 22, 'name' => 'Aroa', 'capital' => 0, ]);
		City::create(['id' => 446, 'federal_states_id' => 22, 'name' => 'Boraure', 'capital' => 0, ]);
		City::create(['id' => 447, 'federal_states_id' => 22, 'name' => 'Campo Elías de Yaracuy', 'capital' => 0, ]);
		City::create(['id' => 448, 'federal_states_id' => 22, 'name' => 'Chivacoa', 'capital' => 0, ]);
		City::create(['id' => 449, 'federal_states_id' => 22, 'name' => 'Cocorote', 'capital' => 0, ]);
		City::create(['id' => 450, 'federal_states_id' => 22, 'name' => 'Farriar', 'capital' => 0, ]);
		City::create(['id' => 451, 'federal_states_id' => 22, 'name' => 'Guama', 'capital' => 0, ]);
		City::create(['id' => 452, 'federal_states_id' => 22, 'name' => 'Marín', 'capital' => 0, ]);
		City::create(['id' => 453, 'federal_states_id' => 22, 'name' => 'Nirgua', 'capital' => 0, ]);
		City::create(['id' => 454, 'federal_states_id' => 22, 'name' => 'Sabana de Parra', 'capital' => 0, ]);
		City::create(['id' => 455, 'federal_states_id' => 22, 'name' => 'Salom', 'capital' => 0, ]);
		City::create(['id' => 456, 'federal_states_id' => 22, 'name' => 'San Felipe', 'capital' => 1, ]);
		City::create(['id' => 457, 'federal_states_id' => 22, 'name' => 'San Pablo de Yaracuy', 'capital' => 0, ]);
		City::create(['id' => 458, 'federal_states_id' => 22, 'name' => 'Urachiche', 'capital' => 0, ]);
		City::create(['id' => 459, 'federal_states_id' => 22, 'name' => 'Yaritagua', 'capital' => 0, ]);
		City::create(['id' => 460, 'federal_states_id' => 22, 'name' => 'Yumare', 'capital' => 0, ]);
		City::create(['id' => 461, 'federal_states_id' => 23, 'name' => 'Bachaquero', 'capital' => 0, ]);
		City::create(['id' => 462, 'federal_states_id' => 23, 'name' => 'Bobures', 'capital' => 0, ]);
		City::create(['id' => 463, 'federal_states_id' => 23, 'name' => 'Cabimas', 'capital' => 0, ]);
		City::create(['id' => 464, 'federal_states_id' => 23, 'name' => 'Campo Concepción', 'capital' => 0, ]);
		City::create(['id' => 465, 'federal_states_id' => 23, 'name' => 'Campo Mara', 'capital' => 0, ]);
		City::create(['id' => 466, 'federal_states_id' => 23, 'name' => 'Campo Rojo', 'capital' => 0, ]);
		City::create(['id' => 467, 'federal_states_id' => 23, 'name' => 'Carrasquero', 'capital' => 0, ]);
		City::create(['id' => 468, 'federal_states_id' => 23, 'name' => 'Casigua', 'capital' => 0, ]);
		City::create(['id' => 469, 'federal_states_id' => 23, 'name' => 'Chiquinquirá', 'capital' => 0, ]);
		City::create(['id' => 470, 'federal_states_id' => 23, 'name' => 'Models\city Ojeda', 'capital' => 0, ]);
		City::create(['id' => 471, 'federal_states_id' => 23, 'name' => 'El Batey', 'capital' => 0, ]);
		City::create(['id' => 472, 'federal_states_id' => 23, 'name' => 'El Carmelo', 'capital' => 0, ]);
		City::create(['id' => 473, 'federal_states_id' => 23, 'name' => 'El Chivo', 'capital' => 0, ]);
		City::create(['id' => 474, 'federal_states_id' => 23, 'name' => 'El Guayabo', 'capital' => 0, ]);
		City::create(['id' => 475, 'federal_states_id' => 23, 'name' => 'El Mene', 'capital' => 0, ]);
		City::create(['id' => 476, 'federal_states_id' => 23, 'name' => 'El Venado', 'capital' => 0, ]);
		City::create(['id' => 477, 'federal_states_id' => 23, 'name' => 'Encontrados', 'capital' => 0, ]);
		City::create(['id' => 478, 'federal_states_id' => 23, 'name' => 'Gibraltar', 'capital' => 0, ]);
		City::create(['id' => 479, 'federal_states_id' => 23, 'name' => 'Isla de Toas', 'capital' => 0, ]);
		City::create(['id' => 480, 'federal_states_id' => 23, 'name' => 'La Concepción del Zulia', 'capital' => 0, ]);
		City::create(['id' => 481, 'federal_states_id' => 23, 'name' => 'La Paz', 'capital' => 0, ]);
		City::create(['id' => 482, 'federal_states_id' => 23, 'name' => 'La Sierrita', 'capital' => 0, ]);
		City::create(['id' => 483, 'federal_states_id' => 23, 'name' => 'Lagunillas del Zulia', 'capital' => 0, ]);
		City::create(['id' => 484, 'federal_states_id' => 23, 'name' => 'Las Piedras de Perijá', 'capital' => 0, ]);
		City::create(['id' => 485, 'federal_states_id' => 23, 'name' => 'Los Cortijos', 'capital' => 0, ]);
		City::create(['id' => 486, 'federal_states_id' => 23, 'name' => 'Machiques', 'capital' => 0, ]);
		City::create(['id' => 487, 'federal_states_id' => 23, 'name' => 'Maracaibo', 'capital' => 1, ]);
		City::create(['id' => 488, 'federal_states_id' => 23, 'name' => 'Mene Grande', 'capital' => 0, ]);
		City::create(['id' => 489, 'federal_states_id' => 23, 'name' => 'Palmarejo', 'capital' => 0, ]);
		City::create(['id' => 490, 'federal_states_id' => 23, 'name' => 'Paraguaipoa', 'capital' => 0, ]);
		City::create(['id' => 491, 'federal_states_id' => 23, 'name' => 'Potrerito', 'capital' => 0, ]);
		City::create(['id' => 492, 'federal_states_id' => 23, 'name' => 'Pueblo Nuevo del Zulia', 'capital' => 0, ]);
		City::create(['id' => 493, 'federal_states_id' => 23, 'name' => 'Puertos de Altagracia', 'capital' => 0, ]);
		City::create(['id' => 494, 'federal_states_id' => 23, 'name' => 'Punta Gorda', 'capital' => 0, ]);
		City::create(['id' => 495, 'federal_states_id' => 23, 'name' => 'Sabaneta de Palma', 'capital' => 0, ]);
		City::create(['id' => 496, 'federal_states_id' => 23, 'name' => 'San Francisco', 'capital' => 0, ]);
		City::create(['id' => 497, 'federal_states_id' => 23, 'name' => 'San José de Perijá', 'capital' => 0, ]);
		City::create(['id' => 498, 'federal_states_id' => 23, 'name' => 'San Rafael del Moján', 'capital' => 0, ]);
		City::create(['id' => 499, 'federal_states_id' => 23, 'name' => 'San Timoteo', 'capital' => 0, ]);
		City::create(['id' => 500, 'federal_states_id' => 23, 'name' => 'Santa Bárbara Del Zulia', 'capital' => 0, ]);
		City::create(['id' => 501, 'federal_states_id' => 23, 'name' => 'Santa Cruz de Mara', 'capital' => 0, ]);
		City::create(['id' => 502, 'federal_states_id' => 23, 'name' => 'Santa Cruz del Zulia', 'capital' => 0, ]);
		City::create(['id' => 503, 'federal_states_id' => 23, 'name' => 'Santa Rita', 'capital' => 0, ]);
		City::create(['id' => 504, 'federal_states_id' => 23, 'name' => 'Sinamaica', 'capital' => 0, ]);
		City::create(['id' => 505, 'federal_states_id' => 23, 'name' => 'Tamare', 'capital' => 0, ]);
		City::create(['id' => 506, 'federal_states_id' => 23, 'name' => 'Tía Juana', 'capital' => 0, ]);
		City::create(['id' => 507, 'federal_states_id' => 23, 'name' => 'Villa del Rosario', 'capital' => 0, ]);
		City::create(['id' => 508, 'federal_states_id' => 21, 'name' => 'La Guaira', 'capital' => 1, ]);
		City::create(['id' => 509, 'federal_states_id' => 21, 'name' => 'Catia La Mar', 'capital' => 0, ]);
		City::create(['id' => 510, 'federal_states_id' => 21, 'name' => 'Macuto', 'capital' => 0, ]);
		City::create(['id' => 511, 'federal_states_id' => 21, 'name' => 'Naiguatá', 'capital' => 0, ]);
		City::create(['id' => 512, 'federal_states_id' => 25, 'name' => 'Archipiélago Los Monjes', 'capital' => 0, ]);
		City::create(['id' => 513, 'federal_states_id' => 25, 'name' => 'Isla La Tortuga y Cayos adyacentes', 'capital' => 0, ]);
		City::create(['id' => 514, 'federal_states_id' => 25, 'name' => 'Isla La Sola', 'capital' => 0, ]);
		City::create(['id' => 515, 'federal_states_id' => 25, 'name' => 'Islas Los Testigos', 'capital' => 0, ]);
		City::create(['id' => 516, 'federal_states_id' => 25, 'name' => 'Islas Los Frailes', 'capital' => 0, ]);
		City::create(['id' => 517, 'federal_states_id' => 25, 'name' => 'Isla La Orchila', 'capital' => 0, ]);
		City::create(['id' => 518, 'federal_states_id' => 25, 'name' => 'Archipiélago Las Aves', 'capital' => 0, ]);
		City::create(['id' => 519, 'federal_states_id' => 25, 'name' => 'Isla de Aves', 'capital' => 0, ]);
		City::create(['id' => 520, 'federal_states_id' => 25, 'name' => 'Isla La Blanquilla', 'capital' => 0, ]);
		City::create(['id' => 521, 'federal_states_id' => 25, 'name' => 'Isla de Patos', 'capital' => 0, ]);
		City::create(['id' => 522, 'federal_states_id' => 25, 'name' => 'Islas Los Hermanos', 'capital' => 0, ]);
    }
}
