<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Municipality;

class MunicipalitiesSeeder extends Seeder
{
    public function run(): void
    {
    /* MunicipalityS */
		Municipality::create(['id' => 1, 'federal_states_id' => 1, 'name'=> 'Alto Orinoco' ]);
		Municipality::create(['id' => 2, 'federal_states_id' => 1, 'name'=> 'Atabapo' ]);
		Municipality::create(['id' => 3, 'federal_states_id' => 1, 'name'=> 'Atures' ]);
		Municipality::create(['id' => 4, 'federal_states_id' => 1, 'name'=> 'Autana' ]);
		Municipality::create(['id' => 5, 'federal_states_id' => 1, 'name'=> 'Manapiare' ]);
		Municipality::create(['id' => 6, 'federal_states_id' => 1, 'name'=> 'Maroa' ]);
		Municipality::create(['id' => 7, 'federal_states_id' => 1, 'name'=> 'Río Negro' ]);
		Municipality::create(['id' => 8, 'federal_states_id' => 2, 'name'=> 'Anaco' ]);
		Municipality::create(['id' => 9, 'federal_states_id' => 2, 'name'=> 'Aragua' ]);
		Municipality::create(['id' => 10, 'federal_states_id' => 2, 'name'=> 'Manuel Ezequiel Bruzual' ]);
		Municipality::create(['id' => 11, 'federal_states_id' => 2, 'name'=> 'Diego Bautista Urbaneja' ]);
		Municipality::create(['id' => 12, 'federal_states_id' => 2, 'name'=> 'Fernando Peñalver' ]);
		Municipality::create(['id' => 13, 'federal_states_id' => 2, 'name'=> 'Francisco Del Carmen Carvajal' ]);
		Municipality::create(['id' => 14, 'federal_states_id' => 2, 'name'=> 'General Sir Arthur McGregor' ]);
		Municipality::create(['id' => 15, 'federal_states_id' => 2, 'name'=> 'Guanta' ]);
		Municipality::create(['id' => 16, 'federal_states_id' => 2, 'name'=> 'Independencia' ]);
		Municipality::create(['id' => 17, 'federal_states_id' => 2, 'name'=> 'José Gregorio Monagas' ]);
		Municipality::create(['id' => 18, 'federal_states_id' => 2, 'name'=> 'Juan Antonio Sotillo' ]);
		Municipality::create(['id' => 19, 'federal_states_id' => 2, 'name'=> 'Juan Manuel Cajigal' ]);
		Municipality::create(['id' => 20, 'federal_states_id' => 2, 'name'=> 'Libertad' ]);
		Municipality::create(['id' => 21, 'federal_states_id' => 2, 'name'=> 'Francisco de Miranda' ]);
		Municipality::create(['id' => 22, 'federal_states_id' => 2, 'name'=> 'Pedro María Freites' ]);
		Municipality::create(['id' => 23, 'federal_states_id' => 2, 'name'=> 'Píritu' ]);
		Municipality::create(['id' => 24, 'federal_states_id' => 2, 'name'=> 'San José de Guanipa' ]);
		Municipality::create(['id' => 25, 'federal_states_id' => 2, 'name'=> 'San Juan de Capistrano' ]);
		Municipality::create(['id' => 26, 'federal_states_id' => 2, 'name'=> 'Santa Ana' ]);
		Municipality::create(['id' => 27, 'federal_states_id' => 2, 'name'=> 'Simón Bolívar' ]);
		Municipality::create(['id' => 28, 'federal_states_id' => 2, 'name'=> 'Simón Rodríguez' ]);
		Municipality::create(['id' => 29, 'federal_states_id' => 3, 'name'=> 'Achaguas' ]);
		Municipality::create(['id' => 30, 'federal_states_id' => 3, 'name'=> 'Biruaca' ]);
		Municipality::create(['id' => 31, 'federal_states_id' => 3, 'name'=> 'Muñóz' ]);
		Municipality::create(['id' => 32, 'federal_states_id' => 3, 'name'=> 'Páez' ]);
		Municipality::create(['id' => 33, 'federal_states_id' => 3, 'name'=> 'Pedro Camejo' ]);
		Municipality::create(['id' => 34, 'federal_states_id' => 3, 'name'=> 'Rómulo Gallegos' ]);
		Municipality::create(['id' => 35, 'federal_states_id' => 3, 'name'=> 'San Fernando' ]);
		Municipality::create(['id' => 36, 'federal_states_id' => 4, 'name'=> 'Atanasio Girardot' ]);
		Municipality::create(['id' => 37, 'federal_states_id' => 4, 'name'=> 'Bolívar' ]);
		Municipality::create(['id' => 38, 'federal_states_id' => 4, 'name'=> 'Camatagua' ]);
		Municipality::create(['id' => 39, 'federal_states_id' => 4, 'name'=> 'Francisco Linares Alcántara' ]);
		Municipality::create(['id' => 40, 'federal_states_id' => 4, 'name'=> 'José Ángel Lamas' ]);
		Municipality::create(['id' => 41, 'federal_states_id' => 4, 'name'=> 'José Félix Ribas' ]);
		Municipality::create(['id' => 42, 'federal_states_id' => 4, 'name'=> 'José Rafael Revenga' ]);
		Municipality::create(['id' => 43, 'federal_states_id' => 4, 'name'=> 'Libertador' ]);
		Municipality::create(['id' => 44, 'federal_states_id' => 4, 'name'=> 'Mario Briceño Iragorry' ]);
		Municipality::create(['id' => 45, 'federal_states_id' => 4, 'name'=> 'Ocumare de la Costa de Oro' ]);
		Municipality::create(['id' => 46, 'federal_states_id' => 4, 'name'=> 'San Casimiro' ]);
		Municipality::create(['id' => 47, 'federal_states_id' => 4, 'name'=> 'San Sebastián' ]);
		Municipality::create(['id' => 48, 'federal_states_id' => 4, 'name'=> 'Santiago Mariño' ]);
		Municipality::create(['id' => 49, 'federal_states_id' => 4, 'name'=> 'Santos Michelena' ]);
		Municipality::create(['id' => 50, 'federal_states_id' => 4, 'name'=> 'Sucre' ]);
		Municipality::create(['id' => 51, 'federal_states_id' => 4, 'name'=> 'Tovar' ]);
		Municipality::create(['id' => 52, 'federal_states_id' => 4, 'name'=> 'Urdaneta' ]);
		Municipality::create(['id' => 53, 'federal_states_id' => 4, 'name'=> 'Zamora' ]);
		Municipality::create(['id' => 54, 'federal_states_id' => 5, 'name'=> 'Alberto Arvelo Torrealba' ]);
		Municipality::create(['id' => 55, 'federal_states_id' => 5, 'name'=> 'Andrés Eloy Blanco' ]);
		Municipality::create(['id' => 56, 'federal_states_id' => 5, 'name'=> 'Antonio José de Sucre' ]);
		Municipality::create(['id' => 57, 'federal_states_id' => 5, 'name'=> 'Arismendi' ]);
		Municipality::create(['id' => 58, 'federal_states_id' => 5, 'name'=> 'Barinas' ]);
		Municipality::create(['id' => 59, 'federal_states_id' => 5, 'name'=> 'Bolívar' ]);
		Municipality::create(['id' => 60, 'federal_states_id' => 5, 'name'=> 'Cruz Paredes' ]);
		Municipality::create(['id' => 61, 'federal_states_id' => 5, 'name'=> 'Ezequiel Zamora' ]);
		Municipality::create(['id' => 62, 'federal_states_id' => 5, 'name'=> 'Obispos' ]);
		Municipality::create(['id' => 63, 'federal_states_id' => 5, 'name'=> 'Pedraza' ]);
		Municipality::create(['id' => 64, 'federal_states_id' => 5, 'name'=> 'Rojas' ]);
		Municipality::create(['id' => 65, 'federal_states_id' => 5, 'name'=> 'Sosa' ]);
		Municipality::create(['id' => 66, 'federal_states_id' => 6, 'name'=> 'Caroní' ]);
		Municipality::create(['id' => 67, 'federal_states_id' => 6, 'name'=> 'Cedeño' ]);
		Municipality::create(['id' => 68, 'federal_states_id' => 6, 'name'=> 'El Callao' ]);
		Municipality::create(['id' => 69, 'federal_states_id' => 6, 'name'=> 'Gran Sabana' ]);
		Municipality::create(['id' => 70, 'federal_states_id' => 6, 'name'=> 'Heres' ]);
		Municipality::create(['id' => 71, 'federal_states_id' => 6, 'name'=> 'Piar' ]);
		Municipality::create(['id' => 72, 'federal_states_id' => 6, 'name'=> 'Angostura (Raúl Leoni)' ]);
		Municipality::create(['id' => 73, 'federal_states_id' => 6, 'name'=> 'Roscio' ]);
		Municipality::create(['id' => 74, 'federal_states_id' => 6, 'name'=> 'Sifontes' ]);
		Municipality::create(['id' => 75, 'federal_states_id' => 6, 'name'=> 'Sucre' ]);
		Municipality::create(['id' => 76, 'federal_states_id' => 6, 'name'=> 'Padre Pedro Chien' ]);
		Municipality::create(['id' => 77, 'federal_states_id' => 7, 'name'=> 'Bejuma' ]);
		Municipality::create(['id' => 78, 'federal_states_id' => 7, 'name'=> 'Carlos Arvelo' ]);
		Municipality::create(['id' => 79, 'federal_states_id' => 7, 'name'=> 'Diego Ibarra' ]);
		Municipality::create(['id' => 80, 'federal_states_id' => 7, 'name'=> 'Guacara' ]);
		Municipality::create(['id' => 81, 'federal_states_id' => 7, 'name'=> 'Juan José Mora' ]);
		Municipality::create(['id' => 82, 'federal_states_id' => 7, 'name'=> 'Libertador' ]);
		Municipality::create(['id' => 83, 'federal_states_id' => 7, 'name'=> 'Los Guayos' ]);
		Municipality::create(['id' => 84, 'federal_states_id' => 7, 'name'=> 'Miranda' ]);
		Municipality::create(['id' => 85, 'federal_states_id' => 7, 'name'=> 'Montalbán' ]);
		Municipality::create(['id' => 86, 'federal_states_id' => 7, 'name'=> 'Naguanagua' ]);
		Municipality::create(['id' => 87, 'federal_states_id' => 7, 'name'=> 'Puerto Cabello' ]);
		Municipality::create(['id' => 88, 'federal_states_id' => 7, 'name'=> 'San Diego' ]);
		Municipality::create(['id' => 89, 'federal_states_id' => 7, 'name'=> 'San Joaquín' ]);
		Municipality::create(['id' => 90, 'federal_states_id' => 7, 'name'=> 'Valencia' ]);
		Municipality::create(['id' => 91, 'federal_states_id' => 8, 'name'=> 'Anzoátegui' ]);
		Municipality::create(['id' => 92, 'federal_states_id' => 8, 'name'=> 'Tinaquillo' ]);
		Municipality::create(['id' => 93, 'federal_states_id' => 8, 'name'=> 'Girardot' ]);
		Municipality::create(['id' => 94, 'federal_states_id' => 8, 'name'=> 'Lima Blanco' ]);
		Municipality::create(['id' => 95, 'federal_states_id' => 8, 'name'=> 'Pao de San Juan Bautista' ]);
		Municipality::create(['id' => 96, 'federal_states_id' => 8, 'name'=> 'Ricaurte' ]);
		Municipality::create(['id' => 97, 'federal_states_id' => 8, 'name'=> 'Rómulo Gallegos' ]);
		Municipality::create(['id' => 98, 'federal_states_id' => 8, 'name'=> 'San Carlos' ]);
		Municipality::create(['id' => 99, 'federal_states_id' => 8, 'name'=> 'Tinaco' ]);
		Municipality::create(['id' => 100, 'federal_states_id' => 9, 'name'=> 'Antonio Díaz' ]);
		Municipality::create(['id' => 101, 'federal_states_id' => 9, 'name'=> 'Casacoima' ]);
		Municipality::create(['id' => 102, 'federal_states_id' => 9, 'name'=> 'Pedernales' ]);
		Municipality::create(['id' => 103, 'federal_states_id' => 9, 'name'=> 'Tucupita' ]);
		Municipality::create(['id' => 104, 'federal_states_id' => 10, 'name'=> 'Acosta' ]);
		Municipality::create(['id' => 105, 'federal_states_id' => 10, 'name'=> 'Bolívar' ]);
		Municipality::create(['id' => 106, 'federal_states_id' => 10, 'name'=> 'Buchivacoa' ]);
		Municipality::create(['id' => 107, 'federal_states_id' => 10, 'name'=> 'Cacique Manaure' ]);
		Municipality::create(['id' => 108, 'federal_states_id' => 10, 'name'=> 'Carirubana' ]);
		Municipality::create(['id' => 109, 'federal_states_id' => 10, 'name'=> 'Colina' ]);
		Municipality::create(['id' => 110, 'federal_states_id' => 10, 'name'=> 'Dabajuro' ]);
		Municipality::create(['id' => 111, 'federal_states_id' => 10, 'name'=> 'Democracia' ]);
		Municipality::create(['id' => 112, 'federal_states_id' => 10, 'name'=> 'Falcón' ]);
		Municipality::create(['id' => 113, 'federal_states_id' => 10, 'name'=> 'Federación' ]);
		Municipality::create(['id' => 114, 'federal_states_id' => 10, 'name'=> 'Jacura' ]);
		Municipality::create(['id' => 115, 'federal_states_id' => 10, 'name'=> 'José Laurencio Silva' ]);
		Municipality::create(['id' => 116, 'federal_states_id' => 10, 'name'=> 'Los Taques' ]);
		Municipality::create(['id' => 117, 'federal_states_id' => 10, 'name'=> 'Mauroa' ]);
		Municipality::create(['id' => 118, 'federal_states_id' => 10, 'name'=> 'Miranda' ]);
		Municipality::create(['id' => 119, 'federal_states_id' => 10, 'name'=> 'Monseñor Iturriza' ]);
		Municipality::create(['id' => 120, 'federal_states_id' => 10, 'name'=> 'Palmasola' ]);
		Municipality::create(['id' => 121, 'federal_states_id' => 10, 'name'=> 'Petit' ]);
		Municipality::create(['id' => 122, 'federal_states_id' => 10, 'name'=> 'Píritu' ]);
		Municipality::create(['id' => 123, 'federal_states_id' => 10, 'name'=> 'San Francisco' ]);
		Municipality::create(['id' => 124, 'federal_states_id' => 10, 'name'=> 'Sucre' ]);
		Municipality::create(['id' => 125, 'federal_states_id' => 10, 'name'=> 'Tocópero' ]);
		Municipality::create(['id' => 126, 'federal_states_id' => 10, 'name'=> 'Unión' ]);
		Municipality::create(['id' => 127, 'federal_states_id' => 10, 'name'=> 'Urumaco' ]);
		Municipality::create(['id' => 128, 'federal_states_id' => 10, 'name'=> 'Zamora' ]);
		Municipality::create(['id' => 129, 'federal_states_id' => 11, 'name'=> 'Camaguán' ]);
		Municipality::create(['id' => 130, 'federal_states_id' => 11, 'name'=> 'Chaguaramas' ]);
		Municipality::create(['id' => 131, 'federal_states_id' => 11, 'name'=> 'El Socorro' ]);
		Municipality::create(['id' => 132, 'federal_states_id' => 11, 'name'=> 'José Félix Ribas' ]);
		Municipality::create(['id' => 133, 'federal_states_id' => 11, 'name'=> 'José Tadeo Monagas' ]);
		Municipality::create(['id' => 134, 'federal_states_id' => 11, 'name'=> 'Juan Germán Roscio' ]);
		Municipality::create(['id' => 135, 'federal_states_id' => 11, 'name'=> 'Julián Mellado' ]);
		Municipality::create(['id' => 136, 'federal_states_id' => 11, 'name'=> 'Las Mercedes' ]);
		Municipality::create(['id' => 137, 'federal_states_id' => 11, 'name'=> 'Leonardo Infante' ]);
		Municipality::create(['id' => 138, 'federal_states_id' => 11, 'name'=> 'Pedro Zaraza' ]);
		Municipality::create(['id' => 139, 'federal_states_id' => 11, 'name'=> 'Ortíz' ]);
		Municipality::create(['id' => 140, 'federal_states_id' => 11, 'name'=> 'San Gerónimo de Guayabal' ]);
		Municipality::create(['id' => 141, 'federal_states_id' => 11, 'name'=> 'San José de Guaribe' ]);
		Municipality::create(['id' => 142, 'federal_states_id' => 11, 'name'=> 'Santa María de Ipire' ]);
		Municipality::create(['id' => 143, 'federal_states_id' => 11, 'name'=> 'Sebastián Francisco de Miranda' ]);
		Municipality::create(['id' => 144, 'federal_states_id' => 12, 'name'=> 'Andrés Eloy Blanco' ]);
		Municipality::create(['id' => 145, 'federal_states_id' => 12, 'name'=> 'Crespo' ]);
		Municipality::create(['id' => 146, 'federal_states_id' => 12, 'name'=> 'Iribarren' ]);
		Municipality::create(['id' => 147, 'federal_states_id' => 12, 'name'=> 'Jiménez' ]);
		Municipality::create(['id' => 148, 'federal_states_id' => 12, 'name'=> 'Morán' ]);
		Municipality::create(['id' => 149, 'federal_states_id' => 12, 'name'=> 'Palavecino' ]);
		Municipality::create(['id' => 150, 'federal_states_id' => 12, 'name'=> 'Simón Planas' ]);
		Municipality::create(['id' => 151, 'federal_states_id' => 12, 'name'=> 'Torres' ]);
		Municipality::create(['id' => 152, 'federal_states_id' => 12, 'name'=> 'Urdaneta' ]);
		Municipality::create(['id' => 179, 'federal_states_id' => 13, 'name'=> 'Alberto Adriani' ]);
		Municipality::create(['id' => 180, 'federal_states_id' => 13, 'name'=> 'Andrés Bello' ]);
		Municipality::create(['id' => 181, 'federal_states_id' => 13, 'name'=> 'Antonio Pinto Salinas' ]);
		Municipality::create(['id' => 182, 'federal_states_id' => 13, 'name'=> 'Aricagua' ]);
		Municipality::create(['id' => 183, 'federal_states_id' => 13, 'name'=> 'Arzobispo Chacón' ]);
		Municipality::create(['id' => 184, 'federal_states_id' => 13, 'name'=> 'Campo Elías' ]);
		Municipality::create(['id' => 185, 'federal_states_id' => 13, 'name'=> 'Caracciolo Parra Olmedo' ]);
		Municipality::create(['id' => 186, 'federal_states_id' => 13, 'name'=> 'Cardenal Quintero' ]);
		Municipality::create(['id' => 187, 'federal_states_id' => 13, 'name'=> 'Guaraque' ]);
		Municipality::create(['id' => 188, 'federal_states_id' => 13, 'name'=> 'Julio César Salas' ]);
		Municipality::create(['id' => 189, 'federal_states_id' => 13, 'name'=> 'Justo Briceño' ]);
		Municipality::create(['id' => 190, 'federal_states_id' => 13, 'name'=> 'Libertador' ]);
		Municipality::create(['id' => 191, 'federal_states_id' => 13, 'name'=> 'Miranda' ]);
		Municipality::create(['id' => 192, 'federal_states_id' => 13, 'name'=> 'Obispo Ramos de Lora' ]);
		Municipality::create(['id' => 193, 'federal_states_id' => 13, 'name'=> 'Padre Noguera' ]);
		Municipality::create(['id' => 194, 'federal_states_id' => 13, 'name'=> 'Pueblo Llano' ]);
		Municipality::create(['id' => 195, 'federal_states_id' => 13, 'name'=> 'Rangel' ]);
		Municipality::create(['id' => 196, 'federal_states_id' => 13, 'name'=> 'Rivas Dávila' ]);
		Municipality::create(['id' => 197, 'federal_states_id' => 13, 'name'=> 'Santos Marquina' ]);
		Municipality::create(['id' => 198, 'federal_states_id' => 13, 'name'=> 'Sucre' ]);
		Municipality::create(['id' => 199, 'federal_states_id' => 13, 'name'=> 'Tovar' ]);
		Municipality::create(['id' => 200, 'federal_states_id' => 13, 'name'=> 'Tulio Febres Cordero' ]);
		Municipality::create(['id' => 201, 'federal_states_id' => 13, 'name'=> 'Zea' ]);
		Municipality::create(['id' => 223, 'federal_states_id' => 14, 'name'=> 'Acevedo' ]);
		Municipality::create(['id' => 224, 'federal_states_id' => 14, 'name'=> 'Andrés Bello' ]);
		Municipality::create(['id' => 225, 'federal_states_id' => 14, 'name'=> 'Baruta' ]);
		Municipality::create(['id' => 226, 'federal_states_id' => 14, 'name'=> 'Brión' ]);
		Municipality::create(['id' => 227, 'federal_states_id' => 14, 'name'=> 'Buroz' ]);
		Municipality::create(['id' => 228, 'federal_states_id' => 14, 'name'=> 'Carrizal' ]);
		Municipality::create(['id' => 229, 'federal_states_id' => 14, 'name'=> 'Chacao' ]);
		Municipality::create(['id' => 230, 'federal_states_id' => 14, 'name'=> 'Cristóbal Rojas' ]);
		Municipality::create(['id' => 231, 'federal_states_id' => 14, 'name'=> 'El Hatillo' ]);
		Municipality::create(['id' => 232, 'federal_states_id' => 14, 'name'=> 'Guaicaipuro' ]);
		Municipality::create(['id' => 233, 'federal_states_id' => 14, 'name'=> 'Independencia' ]);
		Municipality::create(['id' => 234, 'federal_states_id' => 14, 'name'=> 'Lander' ]);
		Municipality::create(['id' => 235, 'federal_states_id' => 14, 'name'=> 'Los Salias' ]);
		Municipality::create(['id' => 236, 'federal_states_id' => 14, 'name'=> 'Páez' ]);
		Municipality::create(['id' => 237, 'federal_states_id' => 14, 'name'=> 'Paz Castillo' ]);
		Municipality::create(['id' => 238, 'federal_states_id' => 14, 'name'=> 'Pedro Gual' ]);
		Municipality::create(['id' => 239, 'federal_states_id' => 14, 'name'=> 'Plaza' ]);
		Municipality::create(['id' => 240, 'federal_states_id' => 14, 'name'=> 'Simón Bolívar' ]);
		Municipality::create(['id' => 241, 'federal_states_id' => 14, 'name'=> 'Sucre' ]);
		Municipality::create(['id' => 242, 'federal_states_id' => 14, 'name'=> 'Urdaneta' ]);
		Municipality::create(['id' => 243, 'federal_states_id' => 14, 'name'=> 'Zamora' ]);
		Municipality::create(['id' => 258, 'federal_states_id' => 15, 'name'=> 'Acosta' ]);
		Municipality::create(['id' => 259, 'federal_states_id' => 15, 'name'=> 'Aguasay' ]);
		Municipality::create(['id' => 260, 'federal_states_id' => 15, 'name'=> 'Bolívar' ]);
		Municipality::create(['id' => 261, 'federal_states_id' => 15, 'name'=> 'Caripe' ]);
		Municipality::create(['id' => 262, 'federal_states_id' => 15, 'name'=> 'Cedeño' ]);
		Municipality::create(['id' => 263, 'federal_states_id' => 15, 'name'=> 'Ezequiel Zamora' ]);
		Municipality::create(['id' => 264, 'federal_states_id' => 15, 'name'=> 'Libertador' ]);
		Municipality::create(['id' => 265, 'federal_states_id' => 15, 'name'=> 'Maturín' ]);
		Municipality::create(['id' => 266, 'federal_states_id' => 15, 'name'=> 'Piar' ]);
		Municipality::create(['id' => 267, 'federal_states_id' => 15, 'name'=> 'Punceres' ]);
		Municipality::create(['id' => 268, 'federal_states_id' => 15, 'name'=> 'Santa Bárbara' ]);
		Municipality::create(['id' => 269, 'federal_states_id' => 15, 'name'=> 'Sotillo' ]);
		Municipality::create(['id' => 270, 'federal_states_id' => 15, 'name'=> 'Uracoa' ]);
		Municipality::create(['id' => 271, 'federal_states_id' => 16, 'name'=> 'Antolín del Campo' ]);
		Municipality::create(['id' => 272, 'federal_states_id' => 16, 'name'=> 'Arismendi' ]);
		Municipality::create(['id' => 273, 'federal_states_id' => 16, 'name'=> 'García' ]);
		Municipality::create(['id' => 274, 'federal_states_id' => 16, 'name'=> 'Gómez' ]);
		Municipality::create(['id' => 275, 'federal_states_id' => 16, 'name'=> 'Maneiro' ]);
		Municipality::create(['id' => 276, 'federal_states_id' => 16, 'name'=> 'Marcano' ]);
		Municipality::create(['id' => 277, 'federal_states_id' => 16, 'name'=> 'Mariño' ]);
		Municipality::create(['id' => 278, 'federal_states_id' => 16, 'name'=> 'Península de Macanao' ]);
		Municipality::create(['id' => 279, 'federal_states_id' => 16, 'name'=> 'Tubores' ]);
		Municipality::create(['id' => 280, 'federal_states_id' => 16, 'name'=> 'Villalba' ]);
		Municipality::create(['id' => 281, 'federal_states_id' => 16, 'name'=> 'Díaz' ]);
		Municipality::create(['id' => 282, 'federal_states_id' => 17, 'name'=> 'Agua Blanca' ]);
		Municipality::create(['id' => 283, 'federal_states_id' => 17, 'name'=> 'Araure' ]);
		Municipality::create(['id' => 284, 'federal_states_id' => 17, 'name'=> 'Esteller' ]);
		Municipality::create(['id' => 285, 'federal_states_id' => 17, 'name'=> 'Guanare' ]);
		Municipality::create(['id' => 286, 'federal_states_id' => 17, 'name'=> 'Guanarito' ]);
		Municipality::create(['id' => 287, 'federal_states_id' => 17, 'name'=> 'Monseñor José Vicente de Unda' ]);
		Municipality::create(['id' => 288, 'federal_states_id' => 17, 'name'=> 'Ospino' ]);
		Municipality::create(['id' => 289, 'federal_states_id' => 17, 'name'=> 'Páez' ]);
		Municipality::create(['id' => 290, 'federal_states_id' => 17, 'name'=> 'Papelón' ]);
		Municipality::create(['id' => 291, 'federal_states_id' => 17, 'name'=> 'San Genaro de Boconoíto' ]);
		Municipality::create(['id' => 292, 'federal_states_id' => 17, 'name'=> 'San Rafael de Onoto' ]);
		Municipality::create(['id' => 293, 'federal_states_id' => 17, 'name'=> 'Santa Rosalía' ]);
		Municipality::create(['id' => 294, 'federal_states_id' => 17, 'name'=> 'Sucre' ]);
		Municipality::create(['id' => 295, 'federal_states_id' => 17, 'name'=> 'Turén' ]);
		Municipality::create(['id' => 296, 'federal_states_id' => 18, 'name'=> 'Andrés Eloy Blanco' ]);
		Municipality::create(['id' => 297, 'federal_states_id' => 18, 'name'=> 'Andrés Mata' ]);
		Municipality::create(['id' => 298, 'federal_states_id' => 18, 'name'=> 'Arismendi' ]);
		Municipality::create(['id' => 299, 'federal_states_id' => 18, 'name'=> 'Benítez' ]);
		Municipality::create(['id' => 300, 'federal_states_id' => 18, 'name'=> 'Bermúdez' ]);
		Municipality::create(['id' => 301, 'federal_states_id' => 18, 'name'=> 'Bolívar' ]);
		Municipality::create(['id' => 302, 'federal_states_id' => 18, 'name'=> 'Cajigal' ]);
		Municipality::create(['id' => 303, 'federal_states_id' => 18, 'name'=> 'Cruz Salmerón Acosta' ]);
		Municipality::create(['id' => 304, 'federal_states_id' => 18, 'name'=> 'Libertador' ]);
		Municipality::create(['id' => 305, 'federal_states_id' => 18, 'name'=> 'Mariño' ]);
		Municipality::create(['id' => 306, 'federal_states_id' => 18, 'name'=> 'Mejía' ]);
		Municipality::create(['id' => 307, 'federal_states_id' => 18, 'name'=> 'Montes' ]);
		Municipality::create(['id' => 308, 'federal_states_id' => 18, 'name'=> 'Ribero' ]);
		Municipality::create(['id' => 309, 'federal_states_id' => 18, 'name'=> 'Sucre' ]);
		Municipality::create(['id' => 310, 'federal_states_id' => 18, 'name'=> 'Valdéz' ]);
		Municipality::create(['id' => 341, 'federal_states_id' => 19, 'name'=> 'Andrés Bello' ]);
		Municipality::create(['id' => 342, 'federal_states_id' => 19, 'name'=> 'Antonio Rómulo Costa' ]);
		Municipality::create(['id' => 343, 'federal_states_id' => 19, 'name'=> 'Ayacucho' ]);
		Municipality::create(['id' => 344, 'federal_states_id' => 19, 'name'=> 'Bolívar' ]);
		Municipality::create(['id' => 345, 'federal_states_id' => 19, 'name'=> 'Cárdenas' ]);
		Municipality::create(['id' => 346, 'federal_states_id' => 19, 'name'=> 'Córdoba' ]);
		Municipality::create(['id' => 347, 'federal_states_id' => 19, 'name'=> 'Fernández Feo' ]);
		Municipality::create(['id' => 348, 'federal_states_id' => 19, 'name'=> 'Francisco de Miranda' ]);
		Municipality::create(['id' => 349, 'federal_states_id' => 19, 'name'=> 'García de Hevia' ]);
		Municipality::create(['id' => 350, 'federal_states_id' => 19, 'name'=> 'Guásimos' ]);
		Municipality::create(['id' => 351, 'federal_states_id' => 19, 'name'=> 'Independencia' ]);
		Municipality::create(['id' => 352, 'federal_states_id' => 19, 'name'=> 'Jáuregui' ]);
		Municipality::create(['id' => 353, 'federal_states_id' => 19, 'name'=> 'José María Vargas' ]);
		Municipality::create(['id' => 354, 'federal_states_id' => 19, 'name'=> 'Junín' ]);
		Municipality::create(['id' => 355, 'federal_states_id' => 19, 'name'=> 'Libertad' ]);
		Municipality::create(['id' => 356, 'federal_states_id' => 19, 'name'=> 'Libertador' ]);
		Municipality::create(['id' => 357, 'federal_states_id' => 19, 'name'=> 'Lobatera' ]);
		Municipality::create(['id' => 358, 'federal_states_id' => 19, 'name'=> 'Michelena' ]);
		Municipality::create(['id' => 359, 'federal_states_id' => 19, 'name'=> 'Panamericano' ]);
		Municipality::create(['id' => 360, 'federal_states_id' => 19, 'name'=> 'Pedro María Ureña' ]);
		Municipality::create(['id' => 361, 'federal_states_id' => 19, 'name'=> 'Rafael Urdaneta' ]);
		Municipality::create(['id' => 362, 'federal_states_id' => 19, 'name'=> 'Samuel Darío Maldonado' ]);
		Municipality::create(['id' => 363, 'federal_states_id' => 19, 'name'=> 'San Cristóbal' ]);
		Municipality::create(['id' => 364, 'federal_states_id' => 19, 'name'=> 'Seboruco' ]);
		Municipality::create(['id' => 365, 'federal_states_id' => 19, 'name'=> 'Simón Rodríguez' ]);
		Municipality::create(['id' => 366, 'federal_states_id' => 19, 'name'=> 'Sucre' ]);
		Municipality::create(['id' => 367, 'federal_states_id' => 19, 'name'=> 'Torbes' ]);
		Municipality::create(['id' => 368, 'federal_states_id' => 19, 'name'=> 'Uribante' ]);
		Municipality::create(['id' => 369, 'federal_states_id' => 19, 'name'=> 'San Judas Tadeo' ]);
		Municipality::create(['id' => 370, 'federal_states_id' => 20, 'name'=> 'Andrés Bello' ]);
		Municipality::create(['id' => 371, 'federal_states_id' => 20, 'name'=> 'Boconó' ]);
		Municipality::create(['id' => 372, 'federal_states_id' => 20, 'name'=> 'Bolívar' ]);
		Municipality::create(['id' => 373, 'federal_states_id' => 20, 'name'=> 'Candelaria' ]);
		Municipality::create(['id' => 374, 'federal_states_id' => 20, 'name'=> 'Carache' ]);
		Municipality::create(['id' => 375, 'federal_states_id' => 20, 'name'=> 'Escuque' ]);
		Municipality::create(['id' => 376, 'federal_states_id' => 20, 'name'=> 'José Felipe Márquez Cañizalez' ]);
		Municipality::create(['id' => 377, 'federal_states_id' => 20, 'name'=> 'Juan Vicente Campos Elías' ]);
		Municipality::create(['id' => 378, 'federal_states_id' => 20, 'name'=> 'La Ceiba' ]);
		Municipality::create(['id' => 379, 'federal_states_id' => 20, 'name'=> 'Miranda' ]);
		Municipality::create(['id' => 380, 'federal_states_id' => 20, 'name'=> 'Monte Carmelo' ]);
		Municipality::create(['id' => 381, 'federal_states_id' => 20, 'name'=> 'Motatán' ]);
		Municipality::create(['id' => 382, 'federal_states_id' => 20, 'name'=> 'Pampán' ]);
		Municipality::create(['id' => 383, 'federal_states_id' => 20, 'name'=> 'Pampanito' ]);
		Municipality::create(['id' => 384, 'federal_states_id' => 20, 'name'=> 'Rafael Rangel' ]);
		Municipality::create(['id' => 385, 'federal_states_id' => 20, 'name'=> 'San Rafael de Carvajal' ]);
		Municipality::create(['id' => 386, 'federal_states_id' => 20, 'name'=> 'Sucre' ]);
		Municipality::create(['id' => 387, 'federal_states_id' => 20, 'name'=> 'Trujillo' ]);
		Municipality::create(['id' => 388, 'federal_states_id' => 20, 'name'=> 'Urdaneta' ]);
		Municipality::create(['id' => 389, 'federal_states_id' => 20, 'name'=> 'Valera' ]);
		Municipality::create(['id' => 390, 'federal_states_id' => 21, 'name'=> 'Vargas' ]);
		Municipality::create(['id' => 391, 'federal_states_id' => 22, 'name'=> 'Arístides Bastidas' ]);
		Municipality::create(['id' => 392, 'federal_states_id' => 22, 'name'=> 'Bolívar' ]);
		Municipality::create(['id' => 407, 'federal_states_id' => 22, 'name'=> 'Bruzual' ]);
		Municipality::create(['id' => 408, 'federal_states_id' => 22, 'name'=> 'Cocorote' ]);
		Municipality::create(['id' => 409, 'federal_states_id' => 22, 'name'=> 'Independencia' ]);
		Municipality::create(['id' => 410, 'federal_states_id' => 22, 'name'=> 'José Antonio Páez' ]);
		Municipality::create(['id' => 411, 'federal_states_id' => 22, 'name'=> 'La Trinidad' ]);
		Municipality::create(['id' => 412, 'federal_states_id' => 22, 'name'=> 'Manuel Monge' ]);
		Municipality::create(['id' => 413, 'federal_states_id' => 22, 'name'=> 'Nirgua' ]);
		Municipality::create(['id' => 414, 'federal_states_id' => 22, 'name'=> 'Peña' ]);
		Municipality::create(['id' => 415, 'federal_states_id' => 22, 'name'=> 'San Felipe' ]);
		Municipality::create(['id' => 416, 'federal_states_id' => 22, 'name'=> 'Sucre' ]);
		Municipality::create(['id' => 417, 'federal_states_id' => 22, 'name'=> 'Urachiche' ]);
		Municipality::create(['id' => 418, 'federal_states_id' => 22, 'name'=> 'José Joaquín Veroes' ]);
		Municipality::create(['id' => 441, 'federal_states_id' => 23, 'name'=> 'Almirante Padilla' ]);
		Municipality::create(['id' => 442, 'federal_states_id' => 23, 'name'=> 'Baralt' ]);
		Municipality::create(['id' => 443, 'federal_states_id' => 23, 'name'=> 'Cabimas' ]);
		Municipality::create(['id' => 444, 'federal_states_id' => 23, 'name'=> 'Catatumbo' ]);
		Municipality::create(['id' => 445, 'federal_states_id' => 23, 'name'=> 'Colón' ]);
		Municipality::create(['id' => 446, 'federal_states_id' => 23, 'name'=> 'Francisco Javier Pulgar' ]);
		Municipality::create(['id' => 447, 'federal_states_id' => 23, 'name'=> 'Páez' ]);
		Municipality::create(['id' => 448, 'federal_states_id' => 23, 'name'=> 'Jesús Enrique Losada' ]);
		Municipality::create(['id' => 449, 'federal_states_id' => 23, 'name'=> 'Jesús María Semprún' ]);
		Municipality::create(['id' => 450, 'federal_states_id' => 23, 'name'=> 'La Cañada de Urdaneta' ]);
		Municipality::create(['id' => 451, 'federal_states_id' => 23, 'name'=> 'Lagunillas' ]);
		Municipality::create(['id' => 452, 'federal_states_id' => 23, 'name'=> 'Machiques de Perijá' ]);
		Municipality::create(['id' => 453, 'federal_states_id' => 23, 'name'=> 'Mara' ]);
		Municipality::create(['id' => 454, 'federal_states_id' => 23, 'name'=> 'Maracaibo' ]);
		Municipality::create(['id' => 455, 'federal_states_id' => 23, 'name'=> 'Miranda' ]);
		Municipality::create(['id' => 456, 'federal_states_id' => 23, 'name'=> 'Rosario de Perijá' ]);
		Municipality::create(['id' => 457, 'federal_states_id' => 23, 'name'=> 'San Francisco' ]);
		Municipality::create(['id' => 458, 'federal_states_id' => 23, 'name'=> 'Santa Rita' ]);
		Municipality::create(['id' => 459, 'federal_states_id' => 23, 'name'=> 'Simón Bolívar' ]);
		Municipality::create(['id' => 460, 'federal_states_id' => 23, 'name'=> 'Sucre' ]);
		Municipality::create(['id' => 461, 'federal_states_id' => 23, 'name'=> 'Valmore Rodríguez' ]);
		Municipality::create(['id' => 462, 'federal_states_id' => 24, 'name'=> 'Libertador' ]);
    }
}

