<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Parish;

class ParishSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Parish::create([ 'id' => 1, 'municipality_id' => 1, 'name'=> 'Alto Orinoco', ]);
		Parish::create([ 'id' => 2, 'municipality_id' => 1, 'name'=> 'Huachamacare Acanaña', ]);
		Parish::create([ 'id' => 3, 'municipality_id' => 1, 'name'=> 'Marawaka Toky Shamanaña', ]);
		Parish::create([ 'id' => 4, 'municipality_id' => 1, 'name'=> 'Mavaka Mavaka', ]);
		Parish::create([ 'id' => 5, 'municipality_id' => 1, 'name'=> 'Sierra Parima Parimabé', ]);
		Parish::create([ 'id' => 6, 'municipality_id' => 2, 'name'=> 'Ucata Laja Lisa', ]);
		Parish::create([ 'id' => 7, 'municipality_id' => 2, 'name'=> 'Yapacana Macuruco', ]);
		Parish::create([ 'id' => 8, 'municipality_id' => 2, 'name'=> 'Caname Guarinuma', ]);
		Parish::create([ 'id' => 9, 'municipality_id' => 3, 'name'=> 'Fernando Girón Tovar', ]);
		Parish::create([ 'id' => 10, 'municipality_id' => 3, 'name'=> 'Luis Alberto Gómez', ]);
		Parish::create([ 'id' => 11, 'municipality_id' => 3, 'name'=> 'Pahueña Limón de Parhueña', ]);
		Parish::create([ 'id' => 12, 'municipality_id' => 3, 'name'=> 'Platanillal Platanillal', ]);
		Parish::create([ 'id' => 13, 'municipality_id' => 4, 'name'=> 'Samariapo', ]);
		Parish::create([ 'id' => 14, 'municipality_id' => 4, 'name'=> 'Sipapo', ]);
		Parish::create([ 'id' => 15, 'municipality_id' => 4, 'name'=> 'Munduapo', ]);
		Parish::create([ 'id' => 16, 'municipality_id' => 4, 'name'=> 'Guayapo', ]);
		Parish::create([ 'id' => 17, 'municipality_id' => 5, 'name'=> 'Alto Ventuari', ]);
		Parish::create([ 'id' => 18, 'municipality_id' => 5, 'name'=> 'Medio Ventuari', ]);
		Parish::create([ 'id' => 19, 'municipality_id' => 5, 'name'=> 'Bajo Ventuari', ]);
		Parish::create([ 'id' => 20, 'municipality_id' => 6, 'name'=> 'Victorino', ]);
		Parish::create([ 'id' => 21, 'municipality_id' => 6, 'name'=> 'Comunidad', ]);
		Parish::create([ 'id' => 22, 'municipality_id' => 7, 'name'=> 'Casiquiare', ]);
		Parish::create([ 'id' => 23, 'municipality_id' => 7, 'name'=> 'Cocuy', ]);
		Parish::create([ 'id' => 24, 'municipality_id' => 7, 'name'=> 'San Carlos de Río Negro', ]);
		Parish::create([ 'id' => 25, 'municipality_id' => 7, 'name'=> 'Solano', ]);
		Parish::create([ 'id' => 26, 'municipality_id' => 8, 'name'=> 'Anaco', ]);
		Parish::create([ 'id' => 27, 'municipality_id' => 8, 'name'=> 'San Joaquín', ]);
		Parish::create([ 'id' => 28, 'municipality_id' => 9, 'name'=> 'Cachipo', ]);
		Parish::create([ 'id' => 29, 'municipality_id' => 9, 'name'=> 'Aragua de Barcelona', ]);
		Parish::create([ 'id' => 30, 'municipality_id' => 11, 'name'=> 'Lechería', ]);
		Parish::create([ 'id' => 31, 'municipality_id' => 11, 'name'=> 'El Morro', ]);
		Parish::create([ 'id' => 32, 'municipality_id' => 12, 'name'=> 'Puerto Píritu', ]);
		Parish::create([ 'id' => 33, 'municipality_id' => 12, 'name'=> 'San Miguel', ]);
		Parish::create([ 'id' => 34, 'municipality_id' => 12, 'name'=> 'Sucre', ]);
		Parish::create([ 'id' => 35, 'municipality_id' => 13, 'name'=> 'Valle de Guanape', ]);
		Parish::create([ 'id' => 36, 'municipality_id' => 13, 'name'=> 'Santa Bárbara', ]);
		Parish::create([ 'id' => 37, 'municipality_id' => 14, 'name'=> 'El Chaparro', ]);
		Parish::create([ 'id' => 38, 'municipality_id' => 14, 'name'=> 'Tomás Alfaro', ]);
		Parish::create([ 'id' => 39, 'municipality_id' => 14, 'name'=> 'Calatrava', ]);
		Parish::create([ 'id' => 40, 'municipality_id' => 15, 'name'=> 'Guanta', ]);
		Parish::create([ 'id' => 41, 'municipality_id' => 15, 'name'=> 'Chorrerón', ]);
		Parish::create([ 'id' => 42, 'municipality_id' => 16, 'name'=> 'Mamo', ]);
		Parish::create([ 'id' => 43, 'municipality_id' => 16, 'name'=> 'Soledad', ]);
		Parish::create([ 'id' => 44, 'municipality_id' => 17, 'name'=> 'Mapire', ]);
		Parish::create([ 'id' => 45, 'municipality_id' => 17, 'name'=> 'Piar', ]);
		Parish::create([ 'id' => 46, 'municipality_id' => 17, 'name'=> 'Santa Clara', ]);
		Parish::create([ 'id' => 47, 'municipality_id' => 17, 'name'=> 'San Diego de Cabrutica', ]);
		Parish::create([ 'id' => 48, 'municipality_id' => 17, 'name'=> 'Uverito', ]);
		Parish::create([ 'id' => 49, 'municipality_id' => 17, 'name'=> 'Zuata', ]);
		Parish::create([ 'id' => 50, 'municipality_id' => 18, 'name'=> 'Puerto La Cruz', ]);
		Parish::create([ 'id' => 51, 'municipality_id' => 18, 'name'=> 'Pozuelos', ]);
		Parish::create([ 'id' => 52, 'municipality_id' => 19, 'name'=> 'Onoto', ]);
		Parish::create([ 'id' => 53, 'municipality_id' => 19, 'name'=> 'San Pablo', ]);
		Parish::create([ 'id' => 54, 'municipality_id' => 20, 'name'=> 'San Mateo', ]);
		Parish::create([ 'id' => 55, 'municipality_id' => 20, 'name'=> 'El Carito', ]);
		Parish::create([ 'id' => 56, 'municipality_id' => 20, 'name'=> 'Santa Inés', ]);
		Parish::create([ 'id' => 57, 'municipality_id' => 20, 'name'=> 'La Romereña', ]);
		Parish::create([ 'id' => 58, 'municipality_id' => 21, 'name'=> 'Atapirire', ]);
		Parish::create([ 'id' => 59, 'municipality_id' => 21, 'name'=> 'Boca del Pao', ]);
		Parish::create([ 'id' => 60, 'municipality_id' => 21, 'name'=> 'El Pao', ]);
		Parish::create([ 'id' => 61, 'municipality_id' => 21, 'name'=> 'Pariaguán', ]);
		Parish::create([ 'id' => 62, 'municipality_id' => 22, 'name'=> 'Cantaura', ]);
		Parish::create([ 'id' => 63, 'municipality_id' => 22, 'name'=> 'Libertador', ]);
		Parish::create([ 'id' => 64, 'municipality_id' => 22, 'name'=> 'Santa Rosa', ]);
		Parish::create([ 'id' => 65, 'municipality_id' => 22, 'name'=> 'Urica', ]);
		Parish::create([ 'id' => 66, 'municipality_id' => 23, 'name'=> 'Píritu', ]);
		Parish::create([ 'id' => 67, 'municipality_id' => 23, 'name'=> 'San Francisco', ]);
		Parish::create([ 'id' => 68, 'municipality_id' => 24, 'name'=> 'San José de Guanipa', ]);
		Parish::create([ 'id' => 69, 'municipality_id' => 25, 'name'=> 'Boca de Uchire', ]);
		Parish::create([ 'id' => 70, 'municipality_id' => 25, 'name'=> 'Boca de Chávez', ]);
		Parish::create([ 'id' => 71, 'municipality_id' => 26, 'name'=> 'Pueblo Nuevo', ]);
		Parish::create([ 'id' => 72, 'municipality_id' => 26, 'name'=> 'Santa Ana', ]);
		Parish::create([ 'id' => 73, 'municipality_id' => 27, 'name'=> 'Bergatín', ]);
		Parish::create([ 'id' => 74, 'municipality_id' => 27, 'name'=> 'Caigua', ]);
		Parish::create([ 'id' => 75, 'municipality_id' => 27, 'name'=> 'El Carmen', ]);
		Parish::create([ 'id' => 76, 'municipality_id' => 27, 'name'=> 'El Pilar', ]);
		Parish::create([ 'id' => 77, 'municipality_id' => 27, 'name'=> 'Naricual', ]);
		Parish::create([ 'id' => 78, 'municipality_id' => 27, 'name'=> 'San Crsitóbal', ]);
		Parish::create([ 'id' => 79, 'municipality_id' => 28, 'name'=> 'Edmundo Barrios', ]);
		Parish::create([ 'id' => 80, 'municipality_id' => 28, 'name'=> 'Miguel Otero Silva', ]);
		Parish::create([ 'id' => 81, 'municipality_id' => 29, 'name'=> 'Achaguas', ]);
		Parish::create([ 'id' => 82, 'municipality_id' => 29, 'name'=> 'Apurito', ]);
		Parish::create([ 'id' => 83, 'municipality_id' => 29, 'name'=> 'El Yagual', ]);
		Parish::create([ 'id' => 84, 'municipality_id' => 29, 'name'=> 'Guachara', ]);
		Parish::create([ 'id' => 85, 'municipality_id' => 29, 'name'=> 'Mucuritas', ]);
		Parish::create([ 'id' => 86, 'municipality_id' => 29, 'name'=> 'Queseras del medio', ]);
		Parish::create([ 'id' => 87, 'municipality_id' => 30, 'name'=> 'Biruaca', ]);
		Parish::create([ 'id' => 88, 'municipality_id' => 31, 'name'=> 'Bruzual', ]);
		Parish::create([ 'id' => 89, 'municipality_id' => 31, 'name'=> 'Mantecal', ]);
		Parish::create([ 'id' => 90, 'municipality_id' => 31, 'name'=> 'Quintero', ]);
		Parish::create([ 'id' => 91, 'municipality_id' => 31, 'name'=> 'Rincón Hondo', ]);
		Parish::create([ 'id' => 92, 'municipality_id' => 31, 'name'=> 'San Vicente', ]);
		Parish::create([ 'id' => 93, 'municipality_id' => 32, 'name'=> 'Guasdualito', ]);
		Parish::create([ 'id' => 94, 'municipality_id' => 32, 'name'=> 'Aramendi', ]);
		Parish::create([ 'id' => 95, 'municipality_id' => 32, 'name'=> 'El Amparo', ]);
		Parish::create([ 'id' => 96, 'municipality_id' => 32, 'name'=> 'San Camilo', ]);
		Parish::create([ 'id' => 97, 'municipality_id' => 32, 'name'=> 'Urdaneta', ]);
		Parish::create([ 'id' => 98, 'municipality_id' => 33, 'name'=> 'San Juan de Payara', ]);
		Parish::create([ 'id' => 99, 'municipality_id' => 33, 'name'=> 'Codazzi', ]);
		Parish::create([ 'id' => 100, 'municipality_id' => 33, 'name'=> 'Cunaviche', ]);
		Parish::create([ 'id' => 101, 'municipality_id' => 34, 'name'=> 'Elorza', ]);
		Parish::create([ 'id' => 102, 'municipality_id' => 34, 'name'=> 'La Trinidad', ]);
		Parish::create([ 'id' => 103, 'municipality_id' => 35, 'name'=> 'San Fernando', ]);
		Parish::create([ 'id' => 104, 'municipality_id' => 35, 'name'=> 'El Recreo', ]);
		Parish::create([ 'id' => 105, 'municipality_id' => 35, 'name'=> 'Peñalver', ]);
		Parish::create([ 'id' => 106, 'municipality_id' => 35, 'name'=> 'San Rafael de Atamaica', ]);
		Parish::create([ 'id' => 107, 'municipality_id' => 36, 'name'=> 'Pedro José Ovalles', ]);
		Parish::create([ 'id' => 108, 'municipality_id' => 36, 'name'=> 'Joaquín Crespo', ]);
		Parish::create([ 'id' => 109, 'municipality_id' => 36, 'name'=> 'José Casanova Godoy', ]);
		Parish::create([ 'id' => 110, 'municipality_id' => 36, 'name'=> 'Madre María de San José', ]);
		Parish::create([ 'id' => 111, 'municipality_id' => 36, 'name'=> 'Andrés Eloy Blanco', ]);
		Parish::create([ 'id' => 112, 'municipality_id' => 36, 'name'=> 'Los Tacarigua', ]);
		Parish::create([ 'id' => 113, 'municipality_id' => 36, 'name'=> 'Las Delicias', ]);
		Parish::create([ 'id' => 114, 'municipality_id' => 36, 'name'=> 'Choroní', ]);
		Parish::create([ 'id' => 115, 'municipality_id' => 37, 'name'=> 'Bolívar', ]);
		Parish::create([ 'id' => 116, 'municipality_id' => 38, 'name'=> 'Camatagua', ]);
		Parish::create([ 'id' => 117, 'municipality_id' => 38, 'name'=> 'Carmen de Cura', ]);
		Parish::create([ 'id' => 118, 'municipality_id' => 39, 'name'=> 'Santa Rita', ]);
		Parish::create([ 'id' => 119, 'municipality_id' => 39, 'name'=> 'Francisco de Miranda', ]);
		Parish::create([ 'id' => 120, 'municipality_id' => 39, 'name'=> 'Moseñor Feliciano González', ]);
		Parish::create([ 'id' => 121, 'municipality_id' => 40, 'name'=> 'Santa Cruz', ]);
		Parish::create([ 'id' => 122, 'municipality_id' => 41, 'name'=> 'José Félix Ribas', ]);
		Parish::create([ 'id' => 123, 'municipality_id' => 41, 'name'=> 'Castor Nieves Ríos', ]);
		Parish::create([ 'id' => 124, 'municipality_id' => 41, 'name'=> 'Las Guacamayas', ]);
		Parish::create([ 'id' => 125, 'municipality_id' => 41, 'name'=> 'Pao de Zárate', ]);
		Parish::create([ 'id' => 126, 'municipality_id' => 41, 'name'=> 'Zuata', ]);
		Parish::create([ 'id' => 127, 'municipality_id' => 42, 'name'=> 'José Rafael Revenga', ]);
		Parish::create([ 'id' => 128, 'municipality_id' => 43, 'name'=> 'Palo Negro', ]);
		Parish::create([ 'id' => 129, 'municipality_id' => 43, 'name'=> 'San Martín de Porres', ]);
		Parish::create([ 'id' => 130, 'municipality_id' => 44, 'name'=> 'El Limón', ]);
		Parish::create([ 'id' => 131, 'municipality_id' => 44, 'name'=> 'Caña de Azúcar', ]);
		Parish::create([ 'id' => 132, 'municipality_id' => 45, 'name'=> 'Ocumare de la Costa', ]);
		Parish::create([ 'id' => 133, 'municipality_id' => 46, 'name'=> 'San Casimiro', ]);
		Parish::create([ 'id' => 134, 'municipality_id' => 46, 'name'=> 'Güiripa', ]);
		Parish::create([ 'id' => 135, 'municipality_id' => 46, 'name'=> 'Ollas de Caramacate', ]);
		Parish::create([ 'id' => 136, 'municipality_id' => 46, 'name'=> 'Valle Morín', ]);
		Parish::create([ 'id' => 137, 'municipality_id' => 47, 'name'=> 'San Sebastían', ]);
		Parish::create([ 'id' => 138, 'municipality_id' => 48, 'name'=> 'Turmero', ]);
		Parish::create([ 'id' => 139, 'municipality_id' => 48, 'name'=> 'Arevalo Aponte', ]);
		Parish::create([ 'id' => 140, 'municipality_id' => 48, 'name'=> 'Chuao', ]);
		Parish::create([ 'id' => 141, 'municipality_id' => 48, 'name'=> 'Samán de Güere', ]);
		Parish::create([ 'id' => 142, 'municipality_id' => 48, 'name'=> 'Alfredo Pacheco Miranda', ]);
		Parish::create([ 'id' => 143, 'municipality_id' => 49, 'name'=> 'Santos Michelena', ]);
		Parish::create([ 'id' => 144, 'municipality_id' => 49, 'name'=> 'Tiara', ]);
		Parish::create([ 'id' => 145, 'municipality_id' => 50, 'name'=> 'Cagua', ]);
		Parish::create([ 'id' => 146, 'municipality_id' => 50, 'name'=> 'Bella Vista', ]);
		Parish::create([ 'id' => 147, 'municipality_id' => 51, 'name'=> 'Tovar', ]);
		Parish::create([ 'id' => 148, 'municipality_id' => 52, 'name'=> 'Urdaneta', ]);
		Parish::create([ 'id' => 149, 'municipality_id' => 52, 'name'=> 'Las Peñitas', ]);
		Parish::create([ 'id' => 150, 'municipality_id' => 52, 'name'=> 'San Francisco de Cara', ]);
		Parish::create([ 'id' => 151, 'municipality_id' => 52, 'name'=> 'Taguay', ]);
		Parish::create([ 'id' => 152, 'municipality_id' => 53, 'name'=> 'Zamora', ]);
		Parish::create([ 'id' => 153, 'municipality_id' => 53, 'name'=> 'Magdaleno', ]);
		Parish::create([ 'id' => 154, 'municipality_id' => 53, 'name'=> 'San Francisco de Asís', ]);
		Parish::create([ 'id' => 155, 'municipality_id' => 53, 'name'=> 'Valles de Tucutunemo', ]);
		Parish::create([ 'id' => 156, 'municipality_id' => 53, 'name'=> 'Augusto Mijares', ]);
		Parish::create([ 'id' => 157, 'municipality_id' => 54, 'name'=> 'Sabaneta', ]);
		Parish::create([ 'id' => 158, 'municipality_id' => 54, 'name'=> 'Juan Antonio Rodríguez Domínguez', ]);
		Parish::create([ 'id' => 159, 'municipality_id' => 55, 'name'=> 'El Cantón', ]);
		Parish::create([ 'id' => 160, 'municipality_id' => 55, 'name'=> 'Santa Cruz de Guacas', ]);
		Parish::create([ 'id' => 161, 'municipality_id' => 55, 'name'=> 'Puerto Vivas', ]);
		Parish::create([ 'id' => 162, 'municipality_id' => 56, 'name'=> 'Ticoporo', ]);
		Parish::create([ 'id' => 163, 'municipality_id' => 56, 'name'=> 'Nicolás Pulido', ]);
		Parish::create([ 'id' => 164, 'municipality_id' => 56, 'name'=> 'Andrés Bello', ]);
		Parish::create([ 'id' => 165, 'municipality_id' => 57, 'name'=> 'Arismendi', ]);
		Parish::create([ 'id' => 166, 'municipality_id' => 57, 'name'=> 'Guadarrama', ]);
		Parish::create([ 'id' => 167, 'municipality_id' => 57, 'name'=> 'La Unión', ]);
		Parish::create([ 'id' => 168, 'municipality_id' => 57, 'name'=> 'San Antonio', ]);
		Parish::create([ 'id' => 169, 'municipality_id' => 58, 'name'=> 'Barinas', ]);
		Parish::create([ 'id' => 170, 'municipality_id' => 58, 'name'=> 'Alberto Arvelo Larriva', ]);
		Parish::create([ 'id' => 171, 'municipality_id' => 58, 'name'=> 'San Silvestre', ]);
		Parish::create([ 'id' => 172, 'municipality_id' => 58, 'name'=> 'Santa Inés', ]);
		Parish::create([ 'id' => 173, 'municipality_id' => 58, 'name'=> 'Santa Lucía', ]);
		Parish::create([ 'id' => 174, 'municipality_id' => 58, 'name'=> 'Torumos', ]);
		Parish::create([ 'id' => 175, 'municipality_id' => 58, 'name'=> 'El Carmen', ]);
		Parish::create([ 'id' => 176, 'municipality_id' => 58, 'name'=> 'Rómulo Betancourt', ]);
		Parish::create([ 'id' => 177, 'municipality_id' => 58, 'name'=> 'Corazón de Jesús', ]);
		Parish::create([ 'id' => 178, 'municipality_id' => 58, 'name'=> 'Ramón Ignacio Méndez', ]);
		Parish::create([ 'id' => 179, 'municipality_id' => 58, 'name'=> 'Alto Barinas', ]);
		Parish::create([ 'id' => 180, 'municipality_id' => 58, 'name'=> 'Manuel Palacio Fajardo', ]);
		Parish::create([ 'id' => 181, 'municipality_id' => 58, 'name'=> 'Juan Antonio Rodríguez Domínguez', ]);
		Parish::create([ 'id' => 182, 'municipality_id' => 58, 'name'=> 'Dominga Ortiz de Páez', ]);
		Parish::create([ 'id' => 183, 'municipality_id' => 59, 'name'=> 'Barinitas', ]);
		Parish::create([ 'id' => 184, 'municipality_id' => 59, 'name'=> 'Altamira de Cáceres', ]);
		Parish::create([ 'id' => 185, 'municipality_id' => 59, 'name'=> 'Calderas', ]);
		Parish::create([ 'id' => 186, 'municipality_id' => 60, 'name'=> 'Barrancas', ]);
		Parish::create([ 'id' => 187, 'municipality_id' => 60, 'name'=> 'El Socorro', ]);
		Parish::create([ 'id' => 188, 'municipality_id' => 60, 'name'=> 'Mazparrito', ]);
		Parish::create([ 'id' => 189, 'municipality_id' => 61, 'name'=> 'Santa Bárbara', ]);
		Parish::create([ 'id' => 190, 'municipality_id' => 61, 'name'=> 'Pedro Briceño Méndez', ]);
		Parish::create([ 'id' => 191, 'municipality_id' => 61, 'name'=> 'Ramón Ignacio Méndez', ]);
		Parish::create([ 'id' => 192, 'municipality_id' => 61, 'name'=> 'José Ignacio del Pumar', ]);
		Parish::create([ 'id' => 193, 'municipality_id' => 62, 'name'=> 'Obispos', ]);
		Parish::create([ 'id' => 194, 'municipality_id' => 62, 'name'=> 'Guasimitos', ]);
		Parish::create([ 'id' => 195, 'municipality_id' => 62, 'name'=> 'El Real', ]);
		Parish::create([ 'id' => 196, 'municipality_id' => 62, 'name'=> 'La Luz', ]);
		Parish::create([ 'id' => 197, 'municipality_id' => 63, 'name'=> 'Models\Ciudad Bolívia', ]);
		Parish::create([ 'id' => 198, 'municipality_id' => 63, 'name'=> 'José Ignacio Briceño', ]);
		Parish::create([ 'id' => 199, 'municipality_id' => 63, 'name'=> 'José Félix Ribas', ]);
		Parish::create([ 'id' => 200, 'municipality_id' => 63, 'name'=> 'Páez', ]);
		Parish::create([ 'id' => 201, 'municipality_id' => 64, 'name'=> 'Libertad', ]);
		Parish::create([ 'id' => 202, 'municipality_id' => 64, 'name'=> 'Dolores', ]);
		Parish::create([ 'id' => 203, 'municipality_id' => 64, 'name'=> 'Santa Rosa', ]);
		Parish::create([ 'id' => 204, 'municipality_id' => 64, 'name'=> 'Palacio Fajardo', ]);
		Parish::create([ 'id' => 205, 'municipality_id' => 65, 'name'=> 'Models\Ciudad de Nutrias', ]);
		Parish::create([ 'id' => 206, 'municipality_id' => 65, 'name'=> 'El Regalo', ]);
		Parish::create([ 'id' => 207, 'municipality_id' => 65, 'name'=> 'Puerto Nutrias', ]);
		Parish::create([ 'id' => 208, 'municipality_id' => 65, 'name'=> 'Santa Catalina', ]);
		Parish::create([ 'id' => 209, 'municipality_id' => 66, 'name'=> 'Cachamay', ]);
		Parish::create([ 'id' => 210, 'municipality_id' => 66, 'name'=> 'Chirica', ]);
		Parish::create([ 'id' => 211, 'municipality_id' => 66, 'name'=> 'Dalla Costa', ]);
		Parish::create([ 'id' => 212, 'municipality_id' => 66, 'name'=> 'Once de Abril', ]);
		Parish::create([ 'id' => 213, 'municipality_id' => 66, 'name'=> 'Simón Bolívar', ]);
		Parish::create([ 'id' => 214, 'municipality_id' => 66, 'name'=> 'Unare', ]);
		Parish::create([ 'id' => 215, 'municipality_id' => 66, 'name'=> 'Universidad', ]);
		Parish::create([ 'id' => 216, 'municipality_id' => 66, 'name'=> 'Vista al Sol', ]);
		Parish::create([ 'id' => 217, 'municipality_id' => 66, 'name'=> 'Pozo Verde', ]);
		Parish::create([ 'id' => 218, 'municipality_id' => 66, 'name'=> 'Yocoima', ]);
		Parish::create([ 'id' => 219, 'municipality_id' => 66, 'name'=> '5 de Julio', ]);
		Parish::create([ 'id' => 220, 'municipality_id' => 67, 'name'=> 'Cedeño', ]);
		Parish::create([ 'id' => 221, 'municipality_id' => 67, 'name'=> 'Altagracia', ]);
		Parish::create([ 'id' => 222, 'municipality_id' => 67, 'name'=> 'Ascensión Farreras', ]);
		Parish::create([ 'id' => 223, 'municipality_id' => 67, 'name'=> 'Guaniamo', ]);
		Parish::create([ 'id' => 224, 'municipality_id' => 67, 'name'=> 'La Urbana', ]);
		Parish::create([ 'id' => 225, 'municipality_id' => 67, 'name'=> 'Pijiguaos', ]);
		Parish::create([ 'id' => 226, 'municipality_id' => 68, 'name'=> 'El Callao', ]);
		Parish::create([ 'id' => 227, 'municipality_id' => 69, 'name'=> 'Gran Sabana', ]);
		Parish::create([ 'id' => 228, 'municipality_id' => 69, 'name'=> 'Ikabarú', ]);
		Parish::create([ 'id' => 229, 'municipality_id' => 70, 'name'=> 'Catedral', ]);
		Parish::create([ 'id' => 230, 'municipality_id' => 70, 'name'=> 'Zea', ]);
		Parish::create([ 'id' => 231, 'municipality_id' => 70, 'name'=> 'Orinoco', ]);
		Parish::create([ 'id' => 232, 'municipality_id' => 70, 'name'=> 'José Antonio Páez', ]);
		Parish::create([ 'id' => 233, 'municipality_id' => 70, 'name'=> 'Marhuanta', ]);
		Parish::create([ 'id' => 234, 'municipality_id' => 70, 'name'=> 'Agua Salada', ]);
		Parish::create([ 'id' => 235, 'municipality_id' => 70, 'name'=> 'Vista Hermosa', ]);
		Parish::create([ 'id' => 236, 'municipality_id' => 70, 'name'=> 'La Sabanita', ]);
		Parish::create([ 'id' => 237, 'municipality_id' => 70, 'name'=> 'Panapana', ]);
		Parish::create([ 'id' => 238, 'municipality_id' => 71, 'name'=> 'Andrés Eloy Blanco', ]);
		Parish::create([ 'id' => 239, 'municipality_id' => 71, 'name'=> 'Pedro Cova', ]);
		Parish::create([ 'id' => 240, 'municipality_id' => 72, 'name'=> 'Raúl Leoni', ]);
		Parish::create([ 'id' => 241, 'municipality_id' => 72, 'name'=> 'Barceloneta', ]);
		Parish::create([ 'id' => 242, 'municipality_id' => 72, 'name'=> 'Santa Bárbara', ]);
		Parish::create([ 'id' => 243, 'municipality_id' => 72, 'name'=> 'San Francisco', ]);
		Parish::create([ 'id' => 244, 'municipality_id' => 73, 'name'=> 'Roscio', ]);
		Parish::create([ 'id' => 245, 'municipality_id' => 73, 'name'=> 'Salóm', ]);
		Parish::create([ 'id' => 246, 'municipality_id' => 74, 'name'=> 'Sifontes', ]);
		Parish::create([ 'id' => 247, 'municipality_id' => 74, 'name'=> 'Dalla Costa', ]);
		Parish::create([ 'id' => 248, 'municipality_id' => 74, 'name'=> 'San Isidro', ]);
		Parish::create([ 'id' => 249, 'municipality_id' => 75, 'name'=> 'Sucre', ]);
		Parish::create([ 'id' => 250, 'municipality_id' => 75, 'name'=> 'Aripao', ]);
		Parish::create([ 'id' => 251, 'municipality_id' => 75, 'name'=> 'Guarataro', ]);
		Parish::create([ 'id' => 252, 'municipality_id' => 75, 'name'=> 'Las Majadas', ]);
		Parish::create([ 'id' => 253, 'municipality_id' => 75, 'name'=> 'Moitaco', ]);
		Parish::create([ 'id' => 254, 'municipality_id' => 76, 'name'=> 'Padre Pedro Chien', ]);
		Parish::create([ 'id' => 255, 'municipality_id' => 76, 'name'=> 'Río Grande', ]);
		Parish::create([ 'id' => 256, 'municipality_id' => 77, 'name'=> 'Bejuma', ]);
		Parish::create([ 'id' => 257, 'municipality_id' => 77, 'name'=> 'Canoabo', ]);
		Parish::create([ 'id' => 258, 'municipality_id' => 77, 'name'=> 'Simón Bolívar', ]);
		Parish::create([ 'id' => 259, 'municipality_id' => 78, 'name'=> 'Güigüe', ]);
		Parish::create([ 'id' => 260, 'municipality_id' => 78, 'name'=> 'Carabobo', ]);
		Parish::create([ 'id' => 261, 'municipality_id' => 78, 'name'=> 'Tacarigua', ]);
		Parish::create([ 'id' => 262, 'municipality_id' => 79, 'name'=> 'Mariara', ]);
		Parish::create([ 'id' => 263, 'municipality_id' => 79, 'name'=> 'Aguas Calientes', ]);
		Parish::create([ 'id' => 264, 'municipality_id' => 80, 'name'=> 'Models\Ciudad Alianza', ]);
		Parish::create([ 'id' => 265, 'municipality_id' => 80, 'name'=> 'Guacara', ]);
		Parish::create([ 'id' => 266, 'municipality_id' => 80, 'name'=> 'Yagua', ]);
		Parish::create([ 'id' => 267, 'municipality_id' => 81, 'name'=> 'Morón', ]);
		Parish::create([ 'id' => 268, 'municipality_id' => 81, 'name'=> 'Yagua', ]);
		Parish::create([ 'id' => 269, 'municipality_id' => 82, 'name'=> 'Tocuyito', ]);
		Parish::create([ 'id' => 270, 'municipality_id' => 82, 'name'=> 'Independencia', ]);
		Parish::create([ 'id' => 271, 'municipality_id' => 83, 'name'=> 'Los Guayos', ]);
		Parish::create([ 'id' => 272, 'municipality_id' => 84, 'name'=> 'Miranda', ]);
		Parish::create([ 'id' => 273, 'municipality_id' => 85, 'name'=> 'Montalbán', ]);
		Parish::create([ 'id' => 274, 'municipality_id' => 86, 'name'=> 'Naguanagua', ]);
		Parish::create([ 'id' => 275, 'municipality_id' => 87, 'name'=> 'Bartolomé Salóm', ]);
		Parish::create([ 'id' => 276, 'municipality_id' => 87, 'name'=> 'Democracia', ]);
		Parish::create([ 'id' => 277, 'municipality_id' => 87, 'name'=> 'Fraternidad', ]);
		Parish::create([ 'id' => 278, 'municipality_id' => 87, 'name'=> 'Goaigoaza', ]);
		Parish::create([ 'id' => 279, 'municipality_id' => 87, 'name'=> 'Juan José Flores', ]);
		Parish::create([ 'id' => 280, 'municipality_id' => 87, 'name'=> 'Unión', ]);
		Parish::create([ 'id' => 281, 'municipality_id' => 87, 'name'=> 'Borburata', ]);
		Parish::create([ 'id' => 282, 'municipality_id' => 87, 'name'=> 'Patanemo', ]);
		Parish::create([ 'id' => 283, 'municipality_id' => 88, 'name'=> 'San Diego', ]);
		Parish::create([ 'id' => 284, 'municipality_id' => 89, 'name'=> 'San Joaquín', ]);
		Parish::create([ 'id' => 285, 'municipality_id' => 90, 'name'=> 'Candelaria', ]);
		Parish::create([ 'id' => 286, 'municipality_id' => 90, 'name'=> 'Catedral', ]);
		Parish::create([ 'id' => 287, 'municipality_id' => 90, 'name'=> 'El Socorro', ]);
		Parish::create([ 'id' => 288, 'municipality_id' => 90, 'name'=> 'Miguel Peña', ]);
		Parish::create([ 'id' => 289, 'municipality_id' => 90, 'name'=> 'Rafael Urdaneta', ]);
		Parish::create([ 'id' => 290, 'municipality_id' => 90, 'name'=> 'San Blas', ]);
		Parish::create([ 'id' => 291, 'municipality_id' => 90, 'name'=> 'San José', ]);
		Parish::create([ 'id' => 292, 'municipality_id' => 90, 'name'=> 'Santa Rosa', ]);
		Parish::create([ 'id' => 293, 'municipality_id' => 90, 'name'=> 'Negro Primero', ]);
		Parish::create([ 'id' => 294, 'municipality_id' => 91, 'name'=> 'Cojedes', ]);
		Parish::create([ 'id' => 295, 'municipality_id' => 91, 'name'=> 'Juan de Mata Suárez', ]);
		Parish::create([ 'id' => 296, 'municipality_id' => 92, 'name'=> 'Tinaquillo', ]);
		Parish::create([ 'id' => 297, 'municipality_id' => 93, 'name'=> 'El Baúl', ]);
		Parish::create([ 'id' => 298, 'municipality_id' => 93, 'name'=> 'Sucre', ]);
		Parish::create([ 'id' => 299, 'municipality_id' => 94, 'name'=> 'La Aguadita', ]);
		Parish::create([ 'id' => 300, 'municipality_id' => 94, 'name'=> 'Macapo', ]);
		Parish::create([ 'id' => 301, 'municipality_id' => 95, 'name'=> 'El Pao', ]);
		Parish::create([ 'id' => 302, 'municipality_id' => 96, 'name'=> 'El Amparo', ]);
		Parish::create([ 'id' => 303, 'municipality_id' => 96, 'name'=> 'Libertad de Cojedes', ]);
		Parish::create([ 'id' => 304, 'municipality_id' => 97, 'name'=> 'Rómulo Gallegos', ]);
		Parish::create([ 'id' => 305, 'municipality_id' => 98, 'name'=> 'San Carlos de Austria', ]);
		Parish::create([ 'id' => 306, 'municipality_id' => 98, 'name'=> 'Juan Ángel Bravo', ]);
		Parish::create([ 'id' => 307, 'municipality_id' => 98, 'name'=> 'Manuel Manrique', ]);
		Parish::create([ 'id' => 308, 'municipality_id' => 99, 'name'=> 'General en Jefe José Laurencio Silva', ]);
		Parish::create([ 'id' => 309, 'municipality_id' => 100, 'name'=> 'Curiapo', ]);
		Parish::create([ 'id' => 310, 'municipality_id' => 100, 'name'=> 'Almirante Luis Brión', ]);
		Parish::create([ 'id' => 311, 'municipality_id' => 100, 'name'=> 'Francisco Aniceto Lugo', ]);
		Parish::create([ 'id' => 312, 'municipality_id' => 100, 'name'=> 'Manuel Renaud', ]);
		Parish::create([ 'id' => 313, 'municipality_id' => 100, 'name'=> 'Padre Barral', ]);
		Parish::create([ 'id' => 314, 'municipality_id' => 100, 'name'=> 'Santos de Abelgas', ]);
		Parish::create([ 'id' => 315, 'municipality_id' => 101, 'name'=> 'Imataca', ]);
		Parish::create([ 'id' => 316, 'municipality_id' => 101, 'name'=> 'Cinco de Julio', ]);
		Parish::create([ 'id' => 317, 'municipality_id' => 101, 'name'=> 'Juan Bautista Arismendi', ]);
		Parish::create([ 'id' => 318, 'municipality_id' => 101, 'name'=> 'Manuel Piar', ]);
		Parish::create([ 'id' => 319, 'municipality_id' => 101, 'name'=> 'Rómulo Gallegos', ]);
		Parish::create([ 'id' => 320, 'municipality_id' => 102, 'name'=> 'Pedernales', ]);
		Parish::create([ 'id' => 321, 'municipality_id' => 102, 'name'=> 'Luis Beltrán Prieto Figueroa', ]);
		Parish::create([ 'id' => 322, 'municipality_id' => 103, 'name'=> 'San José (Delta Amacuro)', ]);
		Parish::create([ 'id' => 323, 'municipality_id' => 103, 'name'=> 'José Vidal Marcano', ]);
		Parish::create([ 'id' => 324, 'municipality_id' => 103, 'name'=> 'Juan Millán', ]);
		Parish::create([ 'id' => 325, 'municipality_id' => 103, 'name'=> 'Leonardo Ruíz Pineda', ]);
		Parish::create([ 'id' => 326, 'municipality_id' => 103, 'name'=> 'Mariscal Antonio José de Sucre', ]);
		Parish::create([ 'id' => 327, 'municipality_id' => 103, 'name'=> 'Monseñor Argimiro García', ]);
		Parish::create([ 'id' => 328, 'municipality_id' => 103, 'name'=> 'San Rafael (Delta Amacuro)', ]);
		Parish::create([ 'id' => 329, 'municipality_id' => 103, 'name'=> 'Virgen del Valle', ]);
		Parish::create([ 'id' => 330, 'municipality_id' => 10, 'name'=> 'Clarines', ]);
		Parish::create([ 'id' => 331, 'municipality_id' => 10, 'name'=> 'Guanape', ]);
		Parish::create([ 'id' => 332, 'municipality_id' => 10, 'name'=> 'Sabana de Uchire', ]);
		Parish::create([ 'id' => 333, 'municipality_id' => 104, 'name'=> 'Capadare', ]);
		Parish::create([ 'id' => 334, 'municipality_id' => 104, 'name'=> 'La Pastora', ]);
		Parish::create([ 'id' => 335, 'municipality_id' => 104, 'name'=> 'Libertador', ]);
		Parish::create([ 'id' => 336, 'municipality_id' => 104, 'name'=> 'San Juan de los Cayos', ]);
		Parish::create([ 'id' => 337, 'municipality_id' => 105, 'name'=> 'Aracua', ]);
		Parish::create([ 'id' => 338, 'municipality_id' => 105, 'name'=> 'La Peña', ]);
		Parish::create([ 'id' => 339, 'municipality_id' => 105, 'name'=> 'San Luis', ]);
		Parish::create([ 'id' => 340, 'municipality_id' => 106, 'name'=> 'Bariro', ]);
		Parish::create([ 'id' => 341, 'municipality_id' => 106, 'name'=> 'Borojó', ]);
		Parish::create([ 'id' => 342, 'municipality_id' => 106, 'name'=> 'Capatárida', ]);
		Parish::create([ 'id' => 343, 'municipality_id' => 106, 'name'=> 'Guajiro', ]);
		Parish::create([ 'id' => 344, 'municipality_id' => 106, 'name'=> 'Seque', ]);
		Parish::create([ 'id' => 345, 'municipality_id' => 106, 'name'=> 'Zazárida', ]);
		Parish::create([ 'id' => 346, 'municipality_id' => 106, 'name'=> 'Valle de Eroa', ]);
		Parish::create([ 'id' => 347, 'municipality_id' => 107, 'name'=> 'Cacique Manaure', ]);
		Parish::create([ 'id' => 348, 'municipality_id' => 108, 'name'=> 'Norte', ]);
		Parish::create([ 'id' => 349, 'municipality_id' => 108, 'name'=> 'Carirubana', ]);
		Parish::create([ 'id' => 350, 'municipality_id' => 108, 'name'=> 'Santa Ana', ]);
		Parish::create([ 'id' => 351, 'municipality_id' => 108, 'name'=> 'Urbana Punta Cardón', ]);
		Parish::create([ 'id' => 352, 'municipality_id' => 109, 'name'=> 'La Vela de Coro', ]);
		Parish::create([ 'id' => 353, 'municipality_id' => 109, 'name'=> 'Acurigua', ]);
		Parish::create([ 'id' => 354, 'municipality_id' => 109, 'name'=> 'Guaibacoa', ]);
		Parish::create([ 'id' => 355, 'municipality_id' => 109, 'name'=> 'Las Calderas', ]);
		Parish::create([ 'id' => 356, 'municipality_id' => 109, 'name'=> 'Macoruca', ]);
		Parish::create([ 'id' => 357, 'municipality_id' => 110, 'name'=> 'Dabajuro', ]);
		Parish::create([ 'id' => 358, 'municipality_id' => 111, 'name'=> 'Agua Clara', ]);
		Parish::create([ 'id' => 359, 'municipality_id' => 111, 'name'=> 'Avaria', ]);
		Parish::create([ 'id' => 360, 'municipality_id' => 111, 'name'=> 'Pedregal', ]);
		Parish::create([ 'id' => 361, 'municipality_id' => 111, 'name'=> 'Piedra Grande', ]);
		Parish::create([ 'id' => 362, 'municipality_id' => 111, 'name'=> 'Purureche', ]);
		Parish::create([ 'id' => 363, 'municipality_id' => 112, 'name'=> 'Adaure', ]);
		Parish::create([ 'id' => 364, 'municipality_id' => 112, 'name'=> 'Adícora', ]);
		Parish::create([ 'id' => 365, 'municipality_id' => 112, 'name'=> 'Baraived', ]);
		Parish::create([ 'id' => 366, 'municipality_id' => 112, 'name'=> 'Buena Vista', ]);
		Parish::create([ 'id' => 367, 'municipality_id' => 112, 'name'=> 'Jadacaquiva', ]);
		Parish::create([ 'id' => 368, 'municipality_id' => 112, 'name'=> 'El Vínculo', ]);
		Parish::create([ 'id' => 369, 'municipality_id' => 112, 'name'=> 'El Hato', ]);
		Parish::create([ 'id' => 370, 'municipality_id' => 112, 'name'=> 'Moruy', ]);
		Parish::create([ 'id' => 371, 'municipality_id' => 112, 'name'=> 'Pueblo Nuevo', ]);
		Parish::create([ 'id' => 372, 'municipality_id' => 113, 'name'=> 'Agua Larga', ]);
		Parish::create([ 'id' => 373, 'municipality_id' => 113, 'name'=> 'El Paují', ]);
		Parish::create([ 'id' => 374, 'municipality_id' => 113, 'name'=> 'Independencia', ]);
		Parish::create([ 'id' => 375, 'municipality_id' => 113, 'name'=> 'Mapararí', ]);
		Parish::create([ 'id' => 376, 'municipality_id' => 114, 'name'=> 'Agua Linda', ]);
		Parish::create([ 'id' => 377, 'municipality_id' => 114, 'name'=> 'Araurima', ]);
		Parish::create([ 'id' => 378, 'municipality_id' => 114, 'name'=> 'Jacura', ]);
		Parish::create([ 'id' => 379, 'municipality_id' => 115, 'name'=> 'Tucacas', ]);
		Parish::create([ 'id' => 380, 'municipality_id' => 115, 'name'=> 'Boca de Aroa', ]);
		Parish::create([ 'id' => 381, 'municipality_id' => 116, 'name'=> 'Los Taques', ]);
		Parish::create([ 'id' => 382, 'municipality_id' => 116, 'name'=> 'Judibana', ]);
		Parish::create([ 'id' => 383, 'municipality_id' => 117, 'name'=> 'Mene de Mauroa', ]);
		Parish::create([ 'id' => 384, 'municipality_id' => 117, 'name'=> 'San Félix', ]);
		Parish::create([ 'id' => 385, 'municipality_id' => 117, 'name'=> 'Casigua', ]);
		Parish::create([ 'id' => 386, 'municipality_id' => 118, 'name'=> 'Guzmán Guillermo', ]);
		Parish::create([ 'id' => 387, 'municipality_id' => 118, 'name'=> 'Mitare', ]);
		Parish::create([ 'id' => 388, 'municipality_id' => 118, 'name'=> 'Río Seco', ]);
		Parish::create([ 'id' => 389, 'municipality_id' => 118, 'name'=> 'Sabaneta', ]);
		Parish::create([ 'id' => 390, 'municipality_id' => 118, 'name'=> 'San Antonio', ]);
		Parish::create([ 'id' => 391, 'municipality_id' => 118, 'name'=> 'San Gabriel', ]);
		Parish::create([ 'id' => 392, 'municipality_id' => 118, 'name'=> 'Santa Ana', ]);
		Parish::create([ 'id' => 393, 'municipality_id' => 119, 'name'=> 'Boca del Tocuyo', ]);
		Parish::create([ 'id' => 394, 'municipality_id' => 119, 'name'=> 'Chichiriviche', ]);
		Parish::create([ 'id' => 395, 'municipality_id' => 119, 'name'=> 'Tocuyo de la Costa', ]);
		Parish::create([ 'id' => 396, 'municipality_id' => 120, 'name'=> 'Palmasola', ]);
		Parish::create([ 'id' => 397, 'municipality_id' => 121, 'name'=> 'Cabure', ]);
		Parish::create([ 'id' => 398, 'municipality_id' => 121, 'name'=> 'Colina', ]);
		Parish::create([ 'id' => 399, 'municipality_id' => 121, 'name'=> 'Curimagua', ]);
		Parish::create([ 'id' => 400, 'municipality_id' => 122, 'name'=> 'San José de la Costa', ]);
		Parish::create([ 'id' => 401, 'municipality_id' => 122, 'name'=> 'Píritu', ]);
		Parish::create([ 'id' => 402, 'municipality_id' => 123, 'name'=> 'San Francisco', ]);
		Parish::create([ 'id' => 403, 'municipality_id' => 124, 'name'=> 'Sucre', ]);
		Parish::create([ 'id' => 404, 'municipality_id' => 124, 'name'=> 'Pecaya', ]);
		Parish::create([ 'id' => 405, 'municipality_id' => 125, 'name'=> 'Tocópero', ]);
		Parish::create([ 'id' => 406, 'municipality_id' => 126, 'name'=> 'El Charal', ]);
		Parish::create([ 'id' => 407, 'municipality_id' => 126, 'name'=> 'Las Vegas del Tuy', ]);
		Parish::create([ 'id' => 408, 'municipality_id' => 126, 'name'=> 'Santa Cruz de Bucaral', ]);
		Parish::create([ 'id' => 409, 'municipality_id' => 127, 'name'=> 'Bruzual', ]);
		Parish::create([ 'id' => 410, 'municipality_id' => 127, 'name'=> 'Urumaco', ]);
		Parish::create([ 'id' => 411, 'municipality_id' => 128, 'name'=> 'Puerto Cumarebo', ]);
		Parish::create([ 'id' => 412, 'municipality_id' => 128, 'name'=> 'La Ciénaga', ]);
		Parish::create([ 'id' => 413, 'municipality_id' => 128, 'name'=> 'La Soledad', ]);
		Parish::create([ 'id' => 414, 'municipality_id' => 128, 'name'=> 'Pueblo Cumarebo', ]);
		Parish::create([ 'id' => 415, 'municipality_id' => 128, 'name'=> 'Zazárida', ]);
		Parish::create([ 'id' => 416, 'municipality_id' => 113, 'name'=> 'Churuguara', ]);
		Parish::create([ 'id' => 417, 'municipality_id' => 129, 'name'=> 'Camaguán', ]);
		Parish::create([ 'id' => 418, 'municipality_id' => 129, 'name'=> 'Puerto Miranda', ]);
		Parish::create([ 'id' => 419, 'municipality_id' => 129, 'name'=> 'Uverito', ]);
		Parish::create([ 'id' => 420, 'municipality_id' => 130, 'name'=> 'Chaguaramas', ]);
		Parish::create([ 'id' => 421, 'municipality_id' => 131, 'name'=> 'El Socorro', ]);
		Parish::create([ 'id' => 422, 'municipality_id' => 132, 'name'=> 'Tucupido', ]);
		Parish::create([ 'id' => 423, 'municipality_id' => 132, 'name'=> 'San Rafael de Laya', ]);
		Parish::create([ 'id' => 424, 'municipality_id' => 133, 'name'=> 'Altagracia de Orituco', ]);
		Parish::create([ 'id' => 425, 'municipality_id' => 133, 'name'=> 'San Rafael de Orituco', ]);
		Parish::create([ 'id' => 426, 'municipality_id' => 133, 'name'=> 'San Francisco Javier de Lezama', ]);
		Parish::create([ 'id' => 427, 'municipality_id' => 133, 'name'=> 'Paso Real de Macaira', ]);
		Parish::create([ 'id' => 428, 'municipality_id' => 133, 'name'=> 'Carlos Soublette', ]);
		Parish::create([ 'id' => 429, 'municipality_id' => 133, 'name'=> 'San Francisco de Macaira', ]);
		Parish::create([ 'id' => 430, 'municipality_id' => 133, 'name'=> 'Libertad de Orituco', ]);
		Parish::create([ 'id' => 431, 'municipality_id' => 134, 'name'=> 'Cantaclaro', ]);
		Parish::create([ 'id' => 432, 'municipality_id' => 134, 'name'=> 'San Juan de los Morros', ]);
		Parish::create([ 'id' => 433, 'municipality_id' => 134, 'name'=> 'Parapara', ]);
		Parish::create([ 'id' => 434, 'municipality_id' => 135, 'name'=> 'El Sombrero', ]);
		Parish::create([ 'id' => 435, 'municipality_id' => 135, 'name'=> 'Sosa', ]);
		Parish::create([ 'id' => 436, 'municipality_id' => 136, 'name'=> 'Las Mercedes', ]);
		Parish::create([ 'id' => 437, 'municipality_id' => 136, 'name'=> 'Cabruta', ]);
		Parish::create([ 'id' => 438, 'municipality_id' => 136, 'name'=> 'Santa Rita de Manapire', ]);
		Parish::create([ 'id' => 439, 'municipality_id' => 137, 'name'=> 'Valle de la Pascua', ]);
		Parish::create([ 'id' => 440, 'municipality_id' => 137, 'name'=> 'Espino', ]);
		Parish::create([ 'id' => 441, 'municipality_id' => 138, 'name'=> 'San José de Unare', ]);
		Parish::create([ 'id' => 442, 'municipality_id' => 138, 'name'=> 'Zaraza', ]);
		Parish::create([ 'id' => 443, 'municipality_id' => 139, 'name'=> 'San José de Tiznados', ]);
		Parish::create([ 'id' => 444, 'municipality_id' => 139, 'name'=> 'San Francisco de Tiznados', ]);
		Parish::create([ 'id' => 445, 'municipality_id' => 139, 'name'=> 'San Lorenzo de Tiznados', ]);
		Parish::create([ 'id' => 446, 'municipality_id' => 139, 'name'=> 'Ortiz', ]);
		Parish::create([ 'id' => 447, 'municipality_id' => 140, 'name'=> 'Guayabal', ]);
		Parish::create([ 'id' => 448, 'municipality_id' => 140, 'name'=> 'Cazorla', ]);
		Parish::create([ 'id' => 449, 'municipality_id' => 141, 'name'=> 'San José de Guaribe', ]);
		Parish::create([ 'id' => 450, 'municipality_id' => 141, 'name'=> 'Uveral', ]);
		Parish::create([ 'id' => 451, 'municipality_id' => 142, 'name'=> 'Santa María de Ipire', ]);
		Parish::create([ 'id' => 452, 'municipality_id' => 142, 'name'=> 'Altamira', ]);
		Parish::create([ 'id' => 453, 'municipality_id' => 143, 'name'=> 'El Calvario', ]);
		Parish::create([ 'id' => 454, 'municipality_id' => 143, 'name'=> 'El Rastro', ]);
		Parish::create([ 'id' => 455, 'municipality_id' => 143, 'name'=> 'Guardatinajas', ]);
		Parish::create([ 'id' => 456, 'municipality_id' => 143, 'name'=> 'Capital Urbana Calabozo', ]);
		Parish::create([ 'id' => 457, 'municipality_id' => 144, 'name'=> 'Quebrada Honda de Guache', ]);
		Parish::create([ 'id' => 458, 'municipality_id' => 144, 'name'=> 'Pío Tamayo', ]);
		Parish::create([ 'id' => 459, 'municipality_id' => 144, 'name'=> 'Yacambú', ]);
		Parish::create([ 'id' => 460, 'municipality_id' => 145, 'name'=> 'Fréitez', ]);
		Parish::create([ 'id' => 461, 'municipality_id' => 145, 'name'=> 'José María Blanco', ]);
		Parish::create([ 'id' => 462, 'municipality_id' => 146, 'name'=> 'Catedral', ]);
		Parish::create([ 'id' => 463, 'municipality_id' => 146, 'name'=> 'Concepción', ]);
		Parish::create([ 'id' => 464, 'municipality_id' => 146, 'name'=> 'El Cují', ]);
		Parish::create([ 'id' => 465, 'municipality_id' => 146, 'name'=> 'Juan de Villegas', ]);
		Parish::create([ 'id' => 466, 'municipality_id' => 146, 'name'=> 'Santa Rosa', ]);
		Parish::create([ 'id' => 467, 'municipality_id' => 146, 'name'=> 'Tamaca', ]);
		Parish::create([ 'id' => 468, 'municipality_id' => 146, 'name'=> 'Unión', ]);
		Parish::create([ 'id' => 469, 'municipality_id' => 146, 'name'=> 'Aguedo Felipe Alvarado', ]);
		Parish::create([ 'id' => 470, 'municipality_id' => 146, 'name'=> 'Buena Vista', ]);
		Parish::create([ 'id' => 471, 'municipality_id' => 146, 'name'=> 'Juárez', ]);
		Parish::create([ 'id' => 472, 'municipality_id' => 147, 'name'=> 'Juan Bautista Rodríguez', ]);
		Parish::create([ 'id' => 473, 'municipality_id' => 147, 'name'=> 'Cuara', ]);
		Parish::create([ 'id' => 474, 'municipality_id' => 147, 'name'=> 'Diego de Lozada', ]);
		Parish::create([ 'id' => 475, 'municipality_id' => 147, 'name'=> 'Paraíso de San José', ]);
		Parish::create([ 'id' => 476, 'municipality_id' => 147, 'name'=> 'San Miguel', ]);
		Parish::create([ 'id' => 477, 'municipality_id' => 147, 'name'=> 'Tintorero', ]);
		Parish::create([ 'id' => 478, 'municipality_id' => 147, 'name'=> 'José Bernardo Dorante', ]);
		Parish::create([ 'id' => 479, 'municipality_id' => 147, 'name'=> 'Coronel Mariano Peraza ', ]);
		Parish::create([ 'id' => 480, 'municipality_id' => 148, 'name'=> 'Bolívar', ]);
		Parish::create([ 'id' => 481, 'municipality_id' => 148, 'name'=> 'Anzoátegui', ]);
		Parish::create([ 'id' => 482, 'municipality_id' => 148, 'name'=> 'Guarico', ]);
		Parish::create([ 'id' => 483, 'municipality_id' => 148, 'name'=> 'Hilario Luna y Luna', ]);
		Parish::create([ 'id' => 484, 'municipality_id' => 148, 'name'=> 'Humocaro Alto', ]);
		Parish::create([ 'id' => 485, 'municipality_id' => 148, 'name'=> 'Humocaro Bajo', ]);
		Parish::create([ 'id' => 486, 'municipality_id' => 148, 'name'=> 'La Candelaria', ]);
		Parish::create([ 'id' => 487, 'municipality_id' => 148, 'name'=> 'Morán', ]);
		Parish::create([ 'id' => 488, 'municipality_id' => 149, 'name'=> 'Cabudare', ]);
		Parish::create([ 'id' => 489, 'municipality_id' => 149, 'name'=> 'José Gregorio Bastidas', ]);
		Parish::create([ 'id' => 490, 'municipality_id' => 149, 'name'=> 'Agua Viva', ]);
		Parish::create([ 'id' => 491, 'municipality_id' => 150, 'name'=> 'Sarare', ]);
		Parish::create([ 'id' => 492, 'municipality_id' => 150, 'name'=> 'Buría', ]);
		Parish::create([ 'id' => 493, 'municipality_id' => 150, 'name'=> 'Gustavo Vegas León', ]);
		Parish::create([ 'id' => 494, 'municipality_id' => 151, 'name'=> 'Trinidad Samuel', ]);
		Parish::create([ 'id' => 495, 'municipality_id' => 151, 'name'=> 'Antonio Díaz', ]);
		Parish::create([ 'id' => 496, 'municipality_id' => 151, 'name'=> 'Camacaro', ]);
		Parish::create([ 'id' => 497, 'municipality_id' => 151, 'name'=> 'Castañeda', ]);
		Parish::create([ 'id' => 498, 'municipality_id' => 151, 'name'=> 'Cecilio Zubillaga', ]);
		Parish::create([ 'id' => 499, 'municipality_id' => 151, 'name'=> 'Chiquinquirá', ]);
		Parish::create([ 'id' => 500, 'municipality_id' => 151, 'name'=> 'El Blanco', ]);
		Parish::create([ 'id' => 501, 'municipality_id' => 151, 'name'=> 'Espinoza de los Monteros', ]);
		Parish::create([ 'id' => 502, 'municipality_id' => 151, 'name'=> 'Lara', ]);
		Parish::create([ 'id' => 503, 'municipality_id' => 151, 'name'=> 'Las Mercedes', ]);
		Parish::create([ 'id' => 504, 'municipality_id' => 151, 'name'=> 'Manuel Morillo', ]);
		Parish::create([ 'id' => 505, 'municipality_id' => 151, 'name'=> 'Montaña Verde', ]);
		Parish::create([ 'id' => 506, 'municipality_id' => 151, 'name'=> 'Montes de Oca', ]);
		Parish::create([ 'id' => 507, 'municipality_id' => 151, 'name'=> 'Torres', ]);
		Parish::create([ 'id' => 508, 'municipality_id' => 151, 'name'=> 'Heriberto Arroyo', ]);
		Parish::create([ 'id' => 509, 'municipality_id' => 151, 'name'=> 'Reyes Vargas', ]);
		Parish::create([ 'id' => 510, 'municipality_id' => 151, 'name'=> 'Altagracia', ]);
		Parish::create([ 'id' => 511, 'municipality_id' => 152, 'name'=> 'Siquisique', ]);
		Parish::create([ 'id' => 512, 'municipality_id' => 152, 'name'=> 'Moroturo', ]);
		Parish::create([ 'id' => 513, 'municipality_id' => 152, 'name'=> 'San Miguel', ]);
		Parish::create([ 'id' => 514, 'municipality_id' => 152, 'name'=> 'Xaguas', ]);
		Parish::create([ 'id' => 515, 'municipality_id' => 179, 'name'=> 'Presidente Betancourt', ]);
		Parish::create([ 'id' => 516, 'municipality_id' => 179, 'name'=> 'Presidente Páez', ]);
		Parish::create([ 'id' => 517, 'municipality_id' => 179, 'name'=> 'Presidente Rómulo Gallegos', ]);
		Parish::create([ 'id' => 518, 'municipality_id' => 179, 'name'=> 'Gabriel Picón González', ]);
		Parish::create([ 'id' => 519, 'municipality_id' => 179, 'name'=> 'Héctor Amable Mora', ]);
		Parish::create([ 'id' => 520, 'municipality_id' => 179, 'name'=> 'José Nucete Sardi', ]);
		Parish::create([ 'id' => 521, 'municipality_id' => 179, 'name'=> 'Pulido Méndez', ]);
		Parish::create([ 'id' => 522, 'municipality_id' => 180, 'name'=> 'La Azulita', ]);
		Parish::create([ 'id' => 523, 'municipality_id' => 181, 'name'=> 'Santa Cruz de Mora', ]);
		Parish::create([ 'id' => 524, 'municipality_id' => 181, 'name'=> 'Mesa Bolívar', ]);
		Parish::create([ 'id' => 525, 'municipality_id' => 181, 'name'=> 'Mesa de Las Palmas', ]);
		Parish::create([ 'id' => 526, 'municipality_id' => 182, 'name'=> 'Aricagua', ]);
		Parish::create([ 'id' => 527, 'municipality_id' => 182, 'name'=> 'San Antonio', ]);
		Parish::create([ 'id' => 528, 'municipality_id' => 183, 'name'=> 'Canagua', ]);
		Parish::create([ 'id' => 529, 'municipality_id' => 183, 'name'=> 'Capurí', ]);
		Parish::create([ 'id' => 530, 'municipality_id' => 183, 'name'=> 'Chacantá', ]);
		Parish::create([ 'id' => 531, 'municipality_id' => 183, 'name'=> 'El Molino', ]);
		Parish::create([ 'id' => 532, 'municipality_id' => 183, 'name'=> 'Guaimaral', ]);
		Parish::create([ 'id' => 533, 'municipality_id' => 183, 'name'=> 'Mucutuy', ]);
		Parish::create([ 'id' => 534, 'municipality_id' => 183, 'name'=> 'Mucuchachí', ]);
		Parish::create([ 'id' => 535, 'municipality_id' => 184, 'name'=> 'Fernández Peña', ]);
		Parish::create([ 'id' => 536, 'municipality_id' => 184, 'name'=> 'Matriz', ]);
		Parish::create([ 'id' => 537, 'municipality_id' => 184, 'name'=> 'Montalbán', ]);
		Parish::create([ 'id' => 538, 'municipality_id' => 184, 'name'=> 'Acequias', ]);
		Parish::create([ 'id' => 539, 'municipality_id' => 184, 'name'=> 'Jají', ]);
		Parish::create([ 'id' => 540, 'municipality_id' => 184, 'name'=> 'La Mesa', ]);
		Parish::create([ 'id' => 541, 'municipality_id' => 184, 'name'=> 'San José del Sur', ]);
		Parish::create([ 'id' => 542, 'municipality_id' => 185, 'name'=> 'Tucaní', ]);
		Parish::create([ 'id' => 543, 'municipality_id' => 185, 'name'=> 'Florencio Ramírez', ]);
		Parish::create([ 'id' => 544, 'municipality_id' => 186, 'name'=> 'Santo Domingo', ]);
		Parish::create([ 'id' => 545, 'municipality_id' => 186, 'name'=> 'Las Piedras', ]);
		Parish::create([ 'id' => 546, 'municipality_id' => 187, 'name'=> 'Guaraque', ]);
		Parish::create([ 'id' => 547, 'municipality_id' => 187, 'name'=> 'Mesa de Quintero', ]);
		Parish::create([ 'id' => 548, 'municipality_id' => 187, 'name'=> 'Río Negro', ]);
		Parish::create([ 'id' => 549, 'municipality_id' => 188, 'name'=> 'Arapuey', ]);
		Parish::create([ 'id' => 550, 'municipality_id' => 188, 'name'=> 'Palmira', ]);
		Parish::create([ 'id' => 551, 'municipality_id' => 189, 'name'=> 'San Cristóbal de Torondoy', ]);
		Parish::create([ 'id' => 552, 'municipality_id' => 189, 'name'=> 'Torondoy', ]);
		Parish::create([ 'id' => 553, 'municipality_id' => 190, 'name'=> 'Antonio Spinetti Dini', ]);
		Parish::create([ 'id' => 554, 'municipality_id' => 190, 'name'=> 'Arias', ]);
		Parish::create([ 'id' => 555, 'municipality_id' => 190, 'name'=> 'Caracciolo Parra Pérez', ]);
		Parish::create([ 'id' => 556, 'municipality_id' => 190, 'name'=> 'Domingo Peña', ]);
		Parish::create([ 'id' => 557, 'municipality_id' => 190, 'name'=> 'El Llano', ]);
		Parish::create([ 'id' => 558, 'municipality_id' => 190, 'name'=> 'Gonzalo Picón Febres', ]);
		Parish::create([ 'id' => 559, 'municipality_id' => 190, 'name'=> 'Jacinto Plaza', ]);
		Parish::create([ 'id' => 560, 'municipality_id' => 190, 'name'=> 'Juan Rodríguez Suárez', ]);
		Parish::create([ 'id' => 561, 'municipality_id' => 190, 'name'=> 'Lasso de la Vega', ]);
		Parish::create([ 'id' => 562, 'municipality_id' => 190, 'name'=> 'Mariano Picón Salas', ]);
		Parish::create([ 'id' => 563, 'municipality_id' => 190, 'name'=> 'Milla', ]);
		Parish::create([ 'id' => 564, 'municipality_id' => 190, 'name'=> 'Osuna Rodríguez', ]);
		Parish::create([ 'id' => 565, 'municipality_id' => 190, 'name'=> 'Sagrario', ]);
		Parish::create([ 'id' => 566, 'municipality_id' => 190, 'name'=> 'El Morro', ]);
		Parish::create([ 'id' => 567, 'municipality_id' => 190, 'name'=> 'Los Nevados', ]);
		Parish::create([ 'id' => 568, 'municipality_id' => 191, 'name'=> 'Andrés Eloy Blanco', ]);
		Parish::create([ 'id' => 569, 'municipality_id' => 191, 'name'=> 'La Venta', ]);
		Parish::create([ 'id' => 570, 'municipality_id' => 191, 'name'=> 'Piñango', ]);
		Parish::create([ 'id' => 571, 'municipality_id' => 191, 'name'=> 'Timotes', ]);
		Parish::create([ 'id' => 572, 'municipality_id' => 192, 'name'=> 'Eloy Paredes', ]);
		Parish::create([ 'id' => 573, 'municipality_id' => 192, 'name'=> 'San Rafael de Alcázar', ]);
		Parish::create([ 'id' => 574, 'municipality_id' => 192, 'name'=> 'Santa Elena de Arenales', ]);
		Parish::create([ 'id' => 575, 'municipality_id' => 193, 'name'=> 'Santa María de Caparo', ]);
		Parish::create([ 'id' => 576, 'municipality_id' => 194, 'name'=> 'Pueblo Llano', ]);
		Parish::create([ 'id' => 577, 'municipality_id' => 195, 'name'=> 'Cacute', ]);
		Parish::create([ 'id' => 578, 'municipality_id' => 195, 'name'=> 'La Toma', ]);
		Parish::create([ 'id' => 579, 'municipality_id' => 195, 'name'=> 'Mucuchíes', ]);
		Parish::create([ 'id' => 580, 'municipality_id' => 195, 'name'=> 'Mucurubá', ]);
		Parish::create([ 'id' => 581, 'municipality_id' => 195, 'name'=> 'San Rafael', ]);
		Parish::create([ 'id' => 582, 'municipality_id' => 196, 'name'=> 'Gerónimo Maldonado', ]);
		Parish::create([ 'id' => 583, 'municipality_id' => 196, 'name'=> 'Bailadores', ]);
		Parish::create([ 'id' => 584, 'municipality_id' => 197, 'name'=> 'Tabay', ]);
		Parish::create([ 'id' => 585, 'municipality_id' => 198, 'name'=> 'Chiguará', ]);
		Parish::create([ 'id' => 586, 'municipality_id' => 198, 'name'=> 'Estánquez', ]);
		Parish::create([ 'id' => 587, 'municipality_id' => 198, 'name'=> 'Lagunillas', ]);
		Parish::create([ 'id' => 588, 'municipality_id' => 198, 'name'=> 'La Trampa', ]);
		Parish::create([ 'id' => 589, 'municipality_id' => 198, 'name'=> 'Pueblo Nuevo del Sur', ]);
		Parish::create([ 'id' => 590, 'municipality_id' => 198, 'name'=> 'San Juan', ]);
		Parish::create([ 'id' => 591, 'municipality_id' => 199, 'name'=> 'El Amparo', ]);
		Parish::create([ 'id' => 592, 'municipality_id' => 199, 'name'=> 'El Llano', ]);
		Parish::create([ 'id' => 593, 'municipality_id' => 199, 'name'=> 'San Francisco', ]);
		Parish::create([ 'id' => 594, 'municipality_id' => 199, 'name'=> 'Tovar', ]);
		Parish::create([ 'id' => 595, 'municipality_id' => 200, 'name'=> 'Independencia', ]);
		Parish::create([ 'id' => 596, 'municipality_id' => 200, 'name'=> 'María de la Concepción Palacios Blanco', ]);
		Parish::create([ 'id' => 597, 'municipality_id' => 200, 'name'=> 'Nueva Bolivia', ]);
		Parish::create([ 'id' => 598, 'municipality_id' => 200, 'name'=> 'Santa Apolonia', ]);
		Parish::create([ 'id' => 599, 'municipality_id' => 201, 'name'=> 'Caño El Tigre', ]);
		Parish::create([ 'id' => 600, 'municipality_id' => 201, 'name'=> 'Zea', ]);
		Parish::create([ 'id' => 601, 'municipality_id' => 223, 'name'=> 'Aragüita', ]);
		Parish::create([ 'id' => 602, 'municipality_id' => 223, 'name'=> 'Arévalo González', ]);
		Parish::create([ 'id' => 603, 'municipality_id' => 223, 'name'=> 'Capaya', ]);
		Parish::create([ 'id' => 604, 'municipality_id' => 223, 'name'=> 'Caucagua', ]);
		Parish::create([ 'id' => 605, 'municipality_id' => 223, 'name'=> 'Panaquire', ]);
		Parish::create([ 'id' => 606, 'municipality_id' => 223, 'name'=> 'Ribas', ]);
		Parish::create([ 'id' => 607, 'municipality_id' => 223, 'name'=> 'El Café', ]);
		Parish::create([ 'id' => 608, 'municipality_id' => 223, 'name'=> 'Marizapa', ]);
		Parish::create([ 'id' => 609, 'municipality_id' => 224, 'name'=> 'Cumbo', ]);
		Parish::create([ 'id' => 610, 'municipality_id' => 224, 'name'=> 'San José de Barlovento', ]);
		Parish::create([ 'id' => 611, 'municipality_id' => 225, 'name'=> 'El Cafetal', ]);
		Parish::create([ 'id' => 612, 'municipality_id' => 225, 'name'=> 'Las Minas', ]);
		Parish::create([ 'id' => 613, 'municipality_id' => 225, 'name'=> 'Nuestra Señora del Rosario', ]);
		Parish::create([ 'id' => 614, 'municipality_id' => 226, 'name'=> 'Higuerote', ]);
		Parish::create([ 'id' => 615, 'municipality_id' => 226, 'name'=> 'Curiepe', ]);
		Parish::create([ 'id' => 616, 'municipality_id' => 226, 'name'=> 'Tacarigua de Brión', ]);
		Parish::create([ 'id' => 617, 'municipality_id' => 227, 'name'=> 'Mamporal', ]);
		Parish::create([ 'id' => 618, 'municipality_id' => 228, 'name'=> 'Carrizal', ]);
		Parish::create([ 'id' => 619, 'municipality_id' => 229, 'name'=> 'Chacao', ]);
		Parish::create([ 'id' => 620, 'municipality_id' => 230, 'name'=> 'Charallave', ]);
		Parish::create([ 'id' => 621, 'municipality_id' => 230, 'name'=> 'Las Brisas', ]);
		Parish::create([ 'id' => 622, 'municipality_id' => 231, 'name'=> 'El Hatillo', ]);
		Parish::create([ 'id' => 623, 'municipality_id' => 232, 'name'=> 'Altagracia de la Montaña', ]);
		Parish::create([ 'id' => 624, 'municipality_id' => 232, 'name'=> 'Cecilio Acosta', ]);
		Parish::create([ 'id' => 625, 'municipality_id' => 232, 'name'=> 'Los Teques', ]);
		Parish::create([ 'id' => 626, 'municipality_id' => 232, 'name'=> 'El Jarillo', ]);
		Parish::create([ 'id' => 627, 'municipality_id' => 232, 'name'=> 'San Pedro', ]);
		Parish::create([ 'id' => 628, 'municipality_id' => 232, 'name'=> 'Tácata', ]);
		Parish::create([ 'id' => 629, 'municipality_id' => 232, 'name'=> 'Paracotos', ]);
		Parish::create([ 'id' => 630, 'municipality_id' => 233, 'name'=> 'Cartanal', ]);
		Parish::create([ 'id' => 631, 'municipality_id' => 233, 'name'=> 'Santa Teresa del Tuy', ]);
		Parish::create([ 'id' => 632, 'municipality_id' => 234, 'name'=> 'La Democracia', ]);
		Parish::create([ 'id' => 633, 'municipality_id' => 234, 'name'=> 'Ocumare del Tuy', ]);
		Parish::create([ 'id' => 634, 'municipality_id' => 234, 'name'=> 'Santa Bárbara', ]);
		Parish::create([ 'id' => 635, 'municipality_id' => 235, 'name'=> 'San Antonio de los Altos', ]);
		Parish::create([ 'id' => 636, 'municipality_id' => 236, 'name'=> 'Río Chico', ]);
		Parish::create([ 'id' => 637, 'municipality_id' => 236, 'name'=> 'El Guapo', ]);
		Parish::create([ 'id' => 638, 'municipality_id' => 236, 'name'=> 'Tacarigua de la Laguna', ]);
		Parish::create([ 'id' => 639, 'municipality_id' => 236, 'name'=> 'Paparo', ]);
		Parish::create([ 'id' => 640, 'municipality_id' => 236, 'name'=> 'San Fernando del Guapo', ]);
		Parish::create([ 'id' => 641, 'municipality_id' => 237, 'name'=> 'Santa Lucía del Tuy', ]);
		Parish::create([ 'id' => 642, 'municipality_id' => 238, 'name'=> 'Cúpira', ]);
		Parish::create([ 'id' => 643, 'municipality_id' => 238, 'name'=> 'Machurucuto', ]);
		Parish::create([ 'id' => 644, 'municipality_id' => 239, 'name'=> 'Guarenas', ]);
		Parish::create([ 'id' => 645, 'municipality_id' => 240, 'name'=> 'San Antonio de Yare', ]);
		Parish::create([ 'id' => 646, 'municipality_id' => 240, 'name'=> 'San Francisco de Yare', ]);
		Parish::create([ 'id' => 647, 'municipality_id' => 241, 'name'=> 'Leoncio Martínez', ]);
		Parish::create([ 'id' => 648, 'municipality_id' => 241, 'name'=> 'Petare', ]);
		Parish::create([ 'id' => 649, 'municipality_id' => 241, 'name'=> 'Caucagüita', ]);
		Parish::create([ 'id' => 650, 'municipality_id' => 241, 'name'=> 'Filas de Mariche', ]);
		Parish::create([ 'id' => 651, 'municipality_id' => 241, 'name'=> 'La Dolorita', ]);
		Parish::create([ 'id' => 652, 'municipality_id' => 242, 'name'=> 'Cúa', ]);
		Parish::create([ 'id' => 653, 'municipality_id' => 242, 'name'=> 'Nueva Cúa', ]);
		Parish::create([ 'id' => 654, 'municipality_id' => 243, 'name'=> 'Guatire', ]);
		Parish::create([ 'id' => 655, 'municipality_id' => 243, 'name'=> 'Bolívar', ]);
		Parish::create([ 'id' => 656, 'municipality_id' => 258, 'name'=> 'San Antonio de Maturín', ]);
		Parish::create([ 'id' => 657, 'municipality_id' => 258, 'name'=> 'San Francisco de Maturín', ]);
		Parish::create([ 'id' => 658, 'municipality_id' => 259, 'name'=> 'Aguasay', ]);
		Parish::create([ 'id' => 659, 'municipality_id' => 260, 'name'=> 'Caripito', ]);
		Parish::create([ 'id' => 660, 'municipality_id' => 261, 'name'=> 'El Guácharo', ]);
		Parish::create([ 'id' => 661, 'municipality_id' => 261, 'name'=> 'La Guanota', ]);
		Parish::create([ 'id' => 662, 'municipality_id' => 261, 'name'=> 'Sabana de Piedra', ]);
		Parish::create([ 'id' => 663, 'municipality_id' => 261, 'name'=> 'San Agustín', ]);
		Parish::create([ 'id' => 664, 'municipality_id' => 261, 'name'=> 'Teresen', ]);
		Parish::create([ 'id' => 665, 'municipality_id' => 261, 'name'=> 'Caripe', ]);
		Parish::create([ 'id' => 666, 'municipality_id' => 262, 'name'=> 'Areo', ]);
		Parish::create([ 'id' => 667, 'municipality_id' => 262, 'name'=> 'Capital Cedeño', ]);
		Parish::create([ 'id' => 668, 'municipality_id' => 262, 'name'=> 'San Félix de Cantalicio', ]);
		Parish::create([ 'id' => 669, 'municipality_id' => 262, 'name'=> 'Viento Fresco', ]);
		Parish::create([ 'id' => 670, 'municipality_id' => 263, 'name'=> 'El Tejero', ]);
		Parish::create([ 'id' => 671, 'municipality_id' => 263, 'name'=> 'Punta de Mata', ]);
		Parish::create([ 'id' => 672, 'municipality_id' => 264, 'name'=> 'Chaguaramas', ]);
		Parish::create([ 'id' => 673, 'municipality_id' => 264, 'name'=> 'Las Alhuacas', ]);
		Parish::create([ 'id' => 674, 'municipality_id' => 264, 'name'=> 'Tabasca', ]);
		Parish::create([ 'id' => 675, 'municipality_id' => 264, 'name'=> 'Temblador', ]);
		Parish::create([ 'id' => 676, 'municipality_id' => 265, 'name'=> 'Alto de los Godos', ]);
		Parish::create([ 'id' => 677, 'municipality_id' => 265, 'name'=> 'Boquerón', ]);
		Parish::create([ 'id' => 678, 'municipality_id' => 265, 'name'=> 'Las Cocuizas', ]);
		Parish::create([ 'id' => 679, 'municipality_id' => 265, 'name'=> 'La Cruz', ]);
		Parish::create([ 'id' => 680, 'municipality_id' => 265, 'name'=> 'San Simón', ]);
		Parish::create([ 'id' => 681, 'municipality_id' => 265, 'name'=> 'El Corozo', ]);
		Parish::create([ 'id' => 682, 'municipality_id' => 265, 'name'=> 'El Furrial', ]);
		Parish::create([ 'id' => 683, 'municipality_id' => 265, 'name'=> 'Jusepín', ]);
		Parish::create([ 'id' => 684, 'municipality_id' => 265, 'name'=> 'La Pica', ]);
		Parish::create([ 'id' => 685, 'municipality_id' => 265, 'name'=> 'San Vicente', ]);
		Parish::create([ 'id' => 686, 'municipality_id' => 266, 'name'=> 'Aparicio', ]);
		Parish::create([ 'id' => 687, 'municipality_id' => 266, 'name'=> 'Aragua de Maturín', ]);
		Parish::create([ 'id' => 688, 'municipality_id' => 266, 'name'=> 'Chaguamal', ]);
		Parish::create([ 'id' => 689, 'municipality_id' => 266, 'name'=> 'El Pinto', ]);
		Parish::create([ 'id' => 690, 'municipality_id' => 266, 'name'=> 'Guanaguana', ]);
		Parish::create([ 'id' => 691, 'municipality_id' => 266, 'name'=> 'La Toscana', ]);
		Parish::create([ 'id' => 692, 'municipality_id' => 266, 'name'=> 'Taguaya', ]);
		Parish::create([ 'id' => 693, 'municipality_id' => 267, 'name'=> 'Cachipo', ]);
		Parish::create([ 'id' => 694, 'municipality_id' => 267, 'name'=> 'Quiriquire', ]);
		Parish::create([ 'id' => 695, 'municipality_id' => 268, 'name'=> 'Santa Bárbara', ]);
		Parish::create([ 'id' => 696, 'municipality_id' => 269, 'name'=> 'Barrancas', ]);
		Parish::create([ 'id' => 697, 'municipality_id' => 269, 'name'=> 'Los Barrancos de Fajardo', ]);
		Parish::create([ 'id' => 698, 'municipality_id' => 270, 'name'=> 'Uracoa', ]);
		Parish::create([ 'id' => 699, 'municipality_id' => 271, 'name'=> 'Antolín del Campo', ]);
		Parish::create([ 'id' => 700, 'municipality_id' => 272, 'name'=> 'Arismendi', ]);
		Parish::create([ 'id' => 701, 'municipality_id' => 273, 'name'=> 'García', ]);
		Parish::create([ 'id' => 702, 'municipality_id' => 273, 'name'=> 'Francisco Fajardo', ]);
		Parish::create([ 'id' => 703, 'municipality_id' => 274, 'name'=> 'Bolívar', ]);
		Parish::create([ 'id' => 704, 'municipality_id' => 274, 'name'=> 'Guevara', ]);
		Parish::create([ 'id' => 705, 'municipality_id' => 274, 'name'=> 'Matasiete', ]);
		Parish::create([ 'id' => 706, 'municipality_id' => 274, 'name'=> 'Santa Ana', ]);
		Parish::create([ 'id' => 707, 'municipality_id' => 274, 'name'=> 'Sucre', ]);
		Parish::create([ 'id' => 708, 'municipality_id' => 275, 'name'=> 'Aguirre', ]);
		Parish::create([ 'id' => 709, 'municipality_id' => 275, 'name'=> 'Maneiro', ]);
		Parish::create([ 'id' => 710, 'municipality_id' => 276, 'name'=> 'Adrián', ]);
		Parish::create([ 'id' => 711, 'municipality_id' => 276, 'name'=> 'Juan Griego', ]);
		Parish::create([ 'id' => 712, 'municipality_id' => 276, 'name'=> 'Yaguaraparo', ]);
		Parish::create([ 'id' => 713, 'municipality_id' => 277, 'name'=> 'Porlamar', ]);
		Parish::create([ 'id' => 714, 'municipality_id' => 278, 'name'=> 'San Francisco de Macanao', ]);
		Parish::create([ 'id' => 715, 'municipality_id' => 278, 'name'=> 'Boca de Río', ]);
		Parish::create([ 'id' => 716, 'municipality_id' => 279, 'name'=> 'Tubores', ]);
		Parish::create([ 'id' => 717, 'municipality_id' => 279, 'name'=> 'Los Baleales', ]);
		Parish::create([ 'id' => 718, 'municipality_id' => 280, 'name'=> 'Vicente Fuentes', ]);
		Parish::create([ 'id' => 719, 'municipality_id' => 280, 'name'=> 'Villalba', ]);
		Parish::create([ 'id' => 720, 'municipality_id' => 281, 'name'=> 'San Juan Bautista', ]);
		Parish::create([ 'id' => 721, 'municipality_id' => 281, 'name'=> 'Zabala', ]);
		Parish::create([ 'id' => 722, 'municipality_id' => 283, 'name'=> 'Capital Araure', ]);
		Parish::create([ 'id' => 723, 'municipality_id' => 283, 'name'=> 'Río Acarigua', ]);
		Parish::create([ 'id' => 724, 'municipality_id' => 284, 'name'=> 'Capital Esteller', ]);
		Parish::create([ 'id' => 725, 'municipality_id' => 284, 'name'=> 'Uveral', ]);
		Parish::create([ 'id' => 726, 'municipality_id' => 285, 'name'=> 'Guanare', ]);
		Parish::create([ 'id' => 727, 'municipality_id' => 285, 'name'=> 'Córdoba', ]);
		Parish::create([ 'id' => 728, 'municipality_id' => 285, 'name'=> 'San José de la Montaña', ]);
		Parish::create([ 'id' => 729, 'municipality_id' => 285, 'name'=> 'San Juan de Guanaguanare', ]);
		Parish::create([ 'id' => 730, 'municipality_id' => 285, 'name'=> 'Virgen de la Coromoto', ]);
		Parish::create([ 'id' => 731, 'municipality_id' => 286, 'name'=> 'Guanarito', ]);
		Parish::create([ 'id' => 732, 'municipality_id' => 286, 'name'=> 'Trinidad de la Capilla', ]);
		Parish::create([ 'id' => 733, 'municipality_id' => 286, 'name'=> 'Divina Pastora', ]);
		Parish::create([ 'id' => 734, 'municipality_id' => 287, 'name'=> 'Monseñor José Vicente de Unda', ]);
		Parish::create([ 'id' => 735, 'municipality_id' => 287, 'name'=> 'Peña Blanca', ]);
		Parish::create([ 'id' => 736, 'municipality_id' => 288, 'name'=> 'Capital Ospino', ]);
		Parish::create([ 'id' => 737, 'municipality_id' => 288, 'name'=> 'Aparición', ]);
		Parish::create([ 'id' => 738, 'municipality_id' => 288, 'name'=> 'La Estación', ]);
		Parish::create([ 'id' => 739, 'municipality_id' => 289, 'name'=> 'Páez', ]);
		Parish::create([ 'id' => 740, 'municipality_id' => 289, 'name'=> 'Payara', ]);
		Parish::create([ 'id' => 741, 'municipality_id' => 289, 'name'=> 'Pimpinela', ]);
		Parish::create([ 'id' => 742, 'municipality_id' => 289, 'name'=> 'Ramón Peraza', ]);
		Parish::create([ 'id' => 743, 'municipality_id' => 290, 'name'=> 'Papelón', ]);
		Parish::create([ 'id' => 744, 'municipality_id' => 290, 'name'=> 'Caño Delgadito', ]);
		Parish::create([ 'id' => 745, 'municipality_id' => 291, 'name'=> 'San Genaro de Boconoito', ]);
		Parish::create([ 'id' => 746, 'municipality_id' => 291, 'name'=> 'Antolín Tovar', ]);
		Parish::create([ 'id' => 747, 'municipality_id' => 292, 'name'=> 'San Rafael de Onoto', ]);
		Parish::create([ 'id' => 748, 'municipality_id' => 292, 'name'=> 'Santa Fe', ]);
		Parish::create([ 'id' => 749, 'municipality_id' => 292, 'name'=> 'Thermo Morles', ]);
		Parish::create([ 'id' => 750, 'municipality_id' => 293, 'name'=> 'Santa Rosalía', ]);
		Parish::create([ 'id' => 751, 'municipality_id' => 293, 'name'=> 'Florida', ]);
		Parish::create([ 'id' => 752, 'municipality_id' => 294, 'name'=> 'Sucre', ]);
		Parish::create([ 'id' => 753, 'municipality_id' => 294, 'name'=> 'Concepción', ]);
		Parish::create([ 'id' => 754, 'municipality_id' => 294, 'name'=> 'San Rafael de Palo Alzado', ]);
		Parish::create([ 'id' => 755, 'municipality_id' => 294, 'name'=> 'Uvencio Antonio Velásquez', ]);
		Parish::create([ 'id' => 756, 'municipality_id' => 294, 'name'=> 'San José de Saguaz', ]);
		Parish::create([ 'id' => 757, 'municipality_id' => 294, 'name'=> 'Villa Rosa', ]);
		Parish::create([ 'id' => 758, 'municipality_id' => 295, 'name'=> 'Turén', ]);
		Parish::create([ 'id' => 759, 'municipality_id' => 295, 'name'=> 'Canelones', ]);
		Parish::create([ 'id' => 760, 'municipality_id' => 295, 'name'=> 'Santa Cruz', ]);
		Parish::create([ 'id' => 761, 'municipality_id' => 295, 'name'=> 'San Isidro Labrador', ]);
		Parish::create([ 'id' => 762, 'municipality_id' => 296, 'name'=> 'Mariño', ]);
		Parish::create([ 'id' => 763, 'municipality_id' => 296, 'name'=> 'Rómulo Gallegos', ]);
		Parish::create([ 'id' => 764, 'municipality_id' => 297, 'name'=> 'San José de Aerocuar', ]);
		Parish::create([ 'id' => 765, 'municipality_id' => 297, 'name'=> 'Tavera Acosta', ]);
		Parish::create([ 'id' => 766, 'municipality_id' => 298, 'name'=> 'Río Caribe', ]);
		Parish::create([ 'id' => 767, 'municipality_id' => 298, 'name'=> 'Antonio José de Sucre', ]);
		Parish::create([ 'id' => 768, 'municipality_id' => 298, 'name'=> 'El Morro de Puerto Santo', ]);
		Parish::create([ 'id' => 769, 'municipality_id' => 298, 'name'=> 'Puerto Santo', ]);
		Parish::create([ 'id' => 770, 'municipality_id' => 298, 'name'=> 'San Juan de las Galdonas', ]);
		Parish::create([ 'id' => 771, 'municipality_id' => 299, 'name'=> 'El Pilar', ]);
		Parish::create([ 'id' => 772, 'municipality_id' => 299, 'name'=> 'El Rincón', ]);
		Parish::create([ 'id' => 773, 'municipality_id' => 299, 'name'=> 'General Francisco Antonio Váquez', ]);
		Parish::create([ 'id' => 774, 'municipality_id' => 299, 'name'=> 'Guaraúnos', ]);
		Parish::create([ 'id' => 775, 'municipality_id' => 299, 'name'=> 'Tunapuicito', ]);
		Parish::create([ 'id' => 776, 'municipality_id' => 299, 'name'=> 'Unión', ]);
		Parish::create([ 'id' => 777, 'municipality_id' => 300, 'name'=> 'Santa Catalina', ]);
		Parish::create([ 'id' => 778, 'municipality_id' => 300, 'name'=> 'Santa Rosa', ]);
		Parish::create([ 'id' => 779, 'municipality_id' => 300, 'name'=> 'Santa Teresa', ]);
		Parish::create([ 'id' => 780, 'municipality_id' => 300, 'name'=> 'Bolívar', ]);
		Parish::create([ 'id' => 781, 'municipality_id' => 300, 'name'=> 'Maracapana', ]);
		Parish::create([ 'id' => 782, 'municipality_id' => 302, 'name'=> 'Libertad', ]);
		Parish::create([ 'id' => 783, 'municipality_id' => 302, 'name'=> 'El Paujil', ]);
		Parish::create([ 'id' => 784, 'municipality_id' => 302, 'name'=> 'Yaguaraparo', ]);
		Parish::create([ 'id' => 785, 'municipality_id' => 303, 'name'=> 'Cruz Salmerón Acosta', ]);
		Parish::create([ 'id' => 786, 'municipality_id' => 303, 'name'=> 'Chacopata', ]);
		Parish::create([ 'id' => 787, 'municipality_id' => 303, 'name'=> 'Manicuare', ]);
		Parish::create([ 'id' => 788, 'municipality_id' => 304, 'name'=> 'Tunapuy', ]);
		Parish::create([ 'id' => 789, 'municipality_id' => 304, 'name'=> 'Campo Elías', ]);
		Parish::create([ 'id' => 790, 'municipality_id' => 305, 'name'=> 'Irapa', ]);
		Parish::create([ 'id' => 791, 'municipality_id' => 305, 'name'=> 'Campo Claro', ]);
		Parish::create([ 'id' => 792, 'municipality_id' => 305, 'name'=> 'Maraval', ]);
		Parish::create([ 'id' => 793, 'municipality_id' => 305, 'name'=> 'San Antonio de Irapa', ]);
		Parish::create([ 'id' => 794, 'municipality_id' => 305, 'name'=> 'Soro', ]);
		Parish::create([ 'id' => 795, 'municipality_id' => 306, 'name'=> 'Mejía', ]);
		Parish::create([ 'id' => 796, 'municipality_id' => 307, 'name'=> 'Cumanacoa', ]);
		Parish::create([ 'id' => 797, 'municipality_id' => 307, 'name'=> 'Arenas', ]);
		Parish::create([ 'id' => 798, 'municipality_id' => 307, 'name'=> 'Aricagua', ]);
		Parish::create([ 'id' => 799, 'municipality_id' => 307, 'name'=> 'Cogollar', ]);
		Parish::create([ 'id' => 800, 'municipality_id' => 307, 'name'=> 'San Fernando', ]);
		Parish::create([ 'id' => 801, 'municipality_id' => 307, 'name'=> 'San Lorenzo', ]);
		Parish::create([ 'id' => 802, 'municipality_id' => 308, 'name'=> 'Villa Frontado (Muelle de Cariaco)', ]);
		Parish::create([ 'id' => 803, 'municipality_id' => 308, 'name'=> 'Catuaro', ]);
		Parish::create([ 'id' => 804, 'municipality_id' => 308, 'name'=> 'Rendón', ]);
		Parish::create([ 'id' => 805, 'municipality_id' => 308, 'name'=> 'San Cruz', ]);
		Parish::create([ 'id' => 806, 'municipality_id' => 308, 'name'=> 'Santa María', ]);
		Parish::create([ 'id' => 807, 'municipality_id' => 309, 'name'=> 'Altagracia', ]);
		Parish::create([ 'id' => 808, 'municipality_id' => 309, 'name'=> 'Santa Inés', ]);
		Parish::create([ 'id' => 809, 'municipality_id' => 309, 'name'=> 'Valentín Valiente', ]);
		Parish::create([ 'id' => 810, 'municipality_id' => 309, 'name'=> 'Ayacucho', ]);
		Parish::create([ 'id' => 811, 'municipality_id' => 309, 'name'=> 'San Juan', ]);
		Parish::create([ 'id' => 812, 'municipality_id' => 309, 'name'=> 'Raúl Leoni', ]);
		Parish::create([ 'id' => 813, 'municipality_id' => 309, 'name'=> 'Gran Mariscal', ]);
		Parish::create([ 'id' => 814, 'municipality_id' => 310, 'name'=> 'Cristóbal Colón', ]);
		Parish::create([ 'id' => 815, 'municipality_id' => 310, 'name'=> 'Bideau', ]);
		Parish::create([ 'id' => 816, 'municipality_id' => 310, 'name'=> 'Punta de Piedras', ]);
		Parish::create([ 'id' => 817, 'municipality_id' => 310, 'name'=> 'Güiria', ]);
		Parish::create([ 'id' => 818, 'municipality_id' => 341, 'name'=> 'Andrés Bello', ]);
		Parish::create([ 'id' => 819, 'municipality_id' => 342, 'name'=> 'Antonio Rómulo Costa', ]);
		Parish::create([ 'id' => 820, 'municipality_id' => 343, 'name'=> 'Ayacucho', ]);
		Parish::create([ 'id' => 821, 'municipality_id' => 343, 'name'=> 'Rivas Berti', ]);
		Parish::create([ 'id' => 822, 'municipality_id' => 343, 'name'=> 'San Pedro del Río', ]);
		Parish::create([ 'id' => 823, 'municipality_id' => 344, 'name'=> 'Bolívar', ]);
		Parish::create([ 'id' => 824, 'municipality_id' => 344, 'name'=> 'Palotal', ]);
		Parish::create([ 'id' => 825, 'municipality_id' => 344, 'name'=> 'General Juan Vicente Gómez', ]);
		Parish::create([ 'id' => 826, 'municipality_id' => 344, 'name'=> 'Isaías Medina Angarita', ]);
		Parish::create([ 'id' => 827, 'municipality_id' => 345, 'name'=> 'Cárdenas', ]);
		Parish::create([ 'id' => 828, 'municipality_id' => 345, 'name'=> 'Amenodoro Ángel Lamus', ]);
		Parish::create([ 'id' => 829, 'municipality_id' => 345, 'name'=> 'La Florida', ]);
		Parish::create([ 'id' => 830, 'municipality_id' => 346, 'name'=> 'Córdoba', ]);
		Parish::create([ 'id' => 831, 'municipality_id' => 347, 'name'=> 'Fernández Feo', ]);
		Parish::create([ 'id' => 832, 'municipality_id' => 347, 'name'=> 'Alberto Adriani', ]);
		Parish::create([ 'id' => 833, 'municipality_id' => 347, 'name'=> 'Santo Domingo', ]);
		Parish::create([ 'id' => 834, 'municipality_id' => 348, 'name'=> 'Francisco de Miranda', ]);
		Parish::create([ 'id' => 835, 'municipality_id' => 349, 'name'=> 'García de Hevia', ]);
		Parish::create([ 'id' => 836, 'municipality_id' => 349, 'name'=> 'Boca de Grita', ]);
		Parish::create([ 'id' => 837, 'municipality_id' => 349, 'name'=> 'José Antonio Páez', ]);
		Parish::create([ 'id' => 838, 'municipality_id' => 350, 'name'=> 'Guásimos', ]);
		Parish::create([ 'id' => 839, 'municipality_id' => 351, 'name'=> 'Independencia', ]);
		Parish::create([ 'id' => 840, 'municipality_id' => 351, 'name'=> 'Juan Germán Roscio', ]);
		Parish::create([ 'id' => 841, 'municipality_id' => 351, 'name'=> 'Román Cárdenas', ]);
		Parish::create([ 'id' => 842, 'municipality_id' => 352, 'name'=> 'Jáuregui', ]);
		Parish::create([ 'id' => 843, 'municipality_id' => 352, 'name'=> 'Emilio Constantino Guerrero', ]);
		Parish::create([ 'id' => 844, 'municipality_id' => 352, 'name'=> 'Monseñor Miguel Antonio Salas', ]);
		Parish::create([ 'id' => 845, 'municipality_id' => 353, 'name'=> 'José María Vargas', ]);
		Parish::create([ 'id' => 846, 'municipality_id' => 354, 'name'=> 'Junín', ]);
		Parish::create([ 'id' => 847, 'municipality_id' => 354, 'name'=> 'La Petrólea', ]);
		Parish::create([ 'id' => 848, 'municipality_id' => 354, 'name'=> 'Quinimarí', ]);
		Parish::create([ 'id' => 849, 'municipality_id' => 354, 'name'=> 'Bramón', ]);
		Parish::create([ 'id' => 850, 'municipality_id' => 355, 'name'=> 'Libertad', ]);
		Parish::create([ 'id' => 851, 'municipality_id' => 355, 'name'=> 'Cipriano Castro', ]);
		Parish::create([ 'id' => 852, 'municipality_id' => 355, 'name'=> 'Manuel Felipe Rugeles', ]);
		Parish::create([ 'id' => 853, 'municipality_id' => 356, 'name'=> 'Libertador', ]);
		Parish::create([ 'id' => 854, 'municipality_id' => 356, 'name'=> 'Doradas', ]);
		Parish::create([ 'id' => 855, 'municipality_id' => 356, 'name'=> 'Emeterio Ochoa', ]);
		Parish::create([ 'id' => 856, 'municipality_id' => 356, 'name'=> 'San Joaquín de Navay', ]);
		Parish::create([ 'id' => 857, 'municipality_id' => 357, 'name'=> 'Lobatera', ]);
		Parish::create([ 'id' => 858, 'municipality_id' => 357, 'name'=> 'Constitución', ]);
		Parish::create([ 'id' => 859, 'municipality_id' => 358, 'name'=> 'Michelena', ]);
		Parish::create([ 'id' => 860, 'municipality_id' => 359, 'name'=> 'Panamericano', ]);
		Parish::create([ 'id' => 861, 'municipality_id' => 359, 'name'=> 'La Palmita', ]);
		Parish::create([ 'id' => 862, 'municipality_id' => 360, 'name'=> 'Pedro María Ureña', ]);
		Parish::create([ 'id' => 863, 'municipality_id' => 360, 'name'=> 'Nueva Arcadia', ]);
		Parish::create([ 'id' => 864, 'municipality_id' => 361, 'name'=> 'Delicias', ]);
		Parish::create([ 'id' => 865, 'municipality_id' => 361, 'name'=> 'Pecaya', ]);
		Parish::create([ 'id' => 866, 'municipality_id' => 362, 'name'=> 'Samuel Darío Maldonado', ]);
		Parish::create([ 'id' => 867, 'municipality_id' => 362, 'name'=> 'Boconó', ]);
		Parish::create([ 'id' => 868, 'municipality_id' => 362, 'name'=> 'Hernández', ]);
		Parish::create([ 'id' => 869, 'municipality_id' => 363, 'name'=> 'La Concordia', ]);
		Parish::create([ 'id' => 870, 'municipality_id' => 363, 'name'=> 'San Juan Bautista', ]);
		Parish::create([ 'id' => 871, 'municipality_id' => 363, 'name'=> 'Pedro María Morantes', ]);
		Parish::create([ 'id' => 872, 'municipality_id' => 363, 'name'=> 'San Sebastián', ]);
		Parish::create([ 'id' => 873, 'municipality_id' => 363, 'name'=> 'Dr. Francisco Romero Lobo', ]);
		Parish::create([ 'id' => 874, 'municipality_id' => 364, 'name'=> 'Seboruco', ]);
		Parish::create([ 'id' => 875, 'municipality_id' => 365, 'name'=> 'Simón Rodríguez', ]);
		Parish::create([ 'id' => 876, 'municipality_id' => 366, 'name'=> 'Sucre', ]);
		Parish::create([ 'id' => 877, 'municipality_id' => 366, 'name'=> 'Eleazar López Contreras', ]);
		Parish::create([ 'id' => 878, 'municipality_id' => 366, 'name'=> 'San Pablo', ]);
		Parish::create([ 'id' => 879, 'municipality_id' => 367, 'name'=> 'Torbes', ]);
		Parish::create([ 'id' => 880, 'municipality_id' => 368, 'name'=> 'Uribante', ]);
		Parish::create([ 'id' => 881, 'municipality_id' => 368, 'name'=> 'Cárdenas', ]);
		Parish::create([ 'id' => 882, 'municipality_id' => 368, 'name'=> 'Juan Pablo Peñalosa', ]);
		Parish::create([ 'id' => 883, 'municipality_id' => 368, 'name'=> 'Potosí', ]);
		Parish::create([ 'id' => 884, 'municipality_id' => 369, 'name'=> 'San Judas Tadeo', ]);
		Parish::create([ 'id' => 885, 'municipality_id' => 370, 'name'=> 'Araguaney', ]);
		Parish::create([ 'id' => 886, 'municipality_id' => 370, 'name'=> 'El Jaguito', ]);
		Parish::create([ 'id' => 887, 'municipality_id' => 370, 'name'=> 'La Esperanza', ]);
		Parish::create([ 'id' => 888, 'municipality_id' => 370, 'name'=> 'Santa Isabel', ]);
		Parish::create([ 'id' => 889, 'municipality_id' => 371, 'name'=> 'Boconó', ]);
		Parish::create([ 'id' => 890, 'municipality_id' => 371, 'name'=> 'El Carmen', ]);
		Parish::create([ 'id' => 891, 'municipality_id' => 371, 'name'=> 'Mosquey', ]);
		Parish::create([ 'id' => 892, 'municipality_id' => 371, 'name'=> 'Ayacucho', ]);
		Parish::create([ 'id' => 893, 'municipality_id' => 371, 'name'=> 'Burbusay', ]);
		Parish::create([ 'id' => 894, 'municipality_id' => 371, 'name'=> 'General Ribas', ]);
		Parish::create([ 'id' => 895, 'municipality_id' => 371, 'name'=> 'Guaramacal', ]);
		Parish::create([ 'id' => 896, 'municipality_id' => 371, 'name'=> 'Vega de Guaramacal', ]);
		Parish::create([ 'id' => 897, 'municipality_id' => 371, 'name'=> 'Monseñor Jáuregui', ]);
		Parish::create([ 'id' => 898, 'municipality_id' => 371, 'name'=> 'Rafael Rangel', ]);
		Parish::create([ 'id' => 899, 'municipality_id' => 371, 'name'=> 'San Miguel', ]);
		Parish::create([ 'id' => 900, 'municipality_id' => 371, 'name'=> 'San José', ]);
		Parish::create([ 'id' => 901, 'municipality_id' => 372, 'name'=> 'Sabana Grande', ]);
		Parish::create([ 'id' => 902, 'municipality_id' => 372, 'name'=> 'Cheregüé', ]);
		Parish::create([ 'id' => 903, 'municipality_id' => 372, 'name'=> 'Granados', ]);
		Parish::create([ 'id' => 904, 'municipality_id' => 373, 'name'=> 'Arnoldo Gabaldón', ]);
		Parish::create([ 'id' => 905, 'municipality_id' => 373, 'name'=> 'Bolivia', ]);
		Parish::create([ 'id' => 906, 'municipality_id' => 373, 'name'=> 'Carrillo', ]);
		Parish::create([ 'id' => 907, 'municipality_id' => 373, 'name'=> 'Cegarra', ]);
		Parish::create([ 'id' => 908, 'municipality_id' => 373, 'name'=> 'Chejendé', ]);
		Parish::create([ 'id' => 909, 'municipality_id' => 373, 'name'=> 'Manuel Salvador Ulloa', ]);
		Parish::create([ 'id' => 910, 'municipality_id' => 373, 'name'=> 'San José', ]);
		Parish::create([ 'id' => 911, 'municipality_id' => 374, 'name'=> 'Carache', ]);
		Parish::create([ 'id' => 912, 'municipality_id' => 374, 'name'=> 'La Concepción', ]);
		Parish::create([ 'id' => 913, 'municipality_id' => 374, 'name'=> 'Cuicas', ]);
		Parish::create([ 'id' => 914, 'municipality_id' => 374, 'name'=> 'Panamericana', ]);
		Parish::create([ 'id' => 915, 'municipality_id' => 374, 'name'=> 'Santa Cruz', ]);
		Parish::create([ 'id' => 916, 'municipality_id' => 375, 'name'=> 'Escuque', ]);
		Parish::create([ 'id' => 917, 'municipality_id' => 375, 'name'=> 'La Unión', ]);
		Parish::create([ 'id' => 918, 'municipality_id' => 375, 'name'=> 'Santa Rita', ]);
		Parish::create([ 'id' => 919, 'municipality_id' => 375, 'name'=> 'Sabana Libre', ]);
		Parish::create([ 'id' => 920, 'municipality_id' => 376, 'name'=> 'El Socorro', ]);
		Parish::create([ 'id' => 921, 'municipality_id' => 376, 'name'=> 'Los Caprichos', ]);
		Parish::create([ 'id' => 922, 'municipality_id' => 376, 'name'=> 'Antonio José de Sucre', ]);
		Parish::create([ 'id' => 923, 'municipality_id' => 377, 'name'=> 'Campo Elías', ]);
		Parish::create([ 'id' => 924, 'municipality_id' => 377, 'name'=> 'Arnoldo Gabaldón', ]);
		Parish::create([ 'id' => 925, 'municipality_id' => 378, 'name'=> 'Santa Apolonia', ]);
		Parish::create([ 'id' => 926, 'municipality_id' => 378, 'name'=> 'El Progreso', ]);
		Parish::create([ 'id' => 927, 'municipality_id' => 378, 'name'=> 'La Ceiba', ]);
		Parish::create([ 'id' => 928, 'municipality_id' => 378, 'name'=> 'Tres de Febrero', ]);
		Parish::create([ 'id' => 929, 'municipality_id' => 379, 'name'=> 'El Dividive', ]);
		Parish::create([ 'id' => 930, 'municipality_id' => 379, 'name'=> 'Agua Santa', ]);
		Parish::create([ 'id' => 931, 'municipality_id' => 379, 'name'=> 'Agua Caliente', ]);
		Parish::create([ 'id' => 932, 'municipality_id' => 379, 'name'=> 'El Cenizo', ]);
		Parish::create([ 'id' => 933, 'municipality_id' => 379, 'name'=> 'Valerita', ]);
		Parish::create([ 'id' => 934, 'municipality_id' => 380, 'name'=> 'Monte Carmelo', ]);
		Parish::create([ 'id' => 935, 'municipality_id' => 380, 'name'=> 'Buena Vista', ]);
		Parish::create([ 'id' => 936, 'municipality_id' => 380, 'name'=> 'Santa María del Horcón', ]);
		Parish::create([ 'id' => 937, 'municipality_id' => 381, 'name'=> 'Motatán', ]);
		Parish::create([ 'id' => 938, 'municipality_id' => 381, 'name'=> 'El Baño', ]);
		Parish::create([ 'id' => 939, 'municipality_id' => 381, 'name'=> 'Jalisco', ]);
		Parish::create([ 'id' => 940, 'municipality_id' => 382, 'name'=> 'Pampán', ]);
		Parish::create([ 'id' => 941, 'municipality_id' => 382, 'name'=> 'Flor de Patria', ]);
		Parish::create([ 'id' => 942, 'municipality_id' => 382, 'name'=> 'La Paz', ]);
		Parish::create([ 'id' => 943, 'municipality_id' => 382, 'name'=> 'Santa Ana', ]);
		Parish::create([ 'id' => 944, 'municipality_id' => 383, 'name'=> 'Pampanito', ]);
		Parish::create([ 'id' => 945, 'municipality_id' => 383, 'name'=> 'La Concepción', ]);
		Parish::create([ 'id' => 946, 'municipality_id' => 383, 'name'=> 'Pampanito II', ]);
		Parish::create([ 'id' => 947, 'municipality_id' => 384, 'name'=> 'Betijoque', ]);
		Parish::create([ 'id' => 948, 'municipality_id' => 384, 'name'=> 'José Gregorio Hernández', ]);
		Parish::create([ 'id' => 949, 'municipality_id' => 384, 'name'=> 'La Pueblita', ]);
		Parish::create([ 'id' => 950, 'municipality_id' => 384, 'name'=> 'Los Cedros', ]);
		Parish::create([ 'id' => 951, 'municipality_id' => 385, 'name'=> 'Carvajal', ]);
		Parish::create([ 'id' => 952, 'municipality_id' => 385, 'name'=> 'Campo Alegre', ]);
		Parish::create([ 'id' => 953, 'municipality_id' => 385, 'name'=> 'Antonio Nicolás Briceño', ]);
		Parish::create([ 'id' => 954, 'municipality_id' => 385, 'name'=> 'José Leonardo Suárez', ]);
		Parish::create([ 'id' => 955, 'municipality_id' => 386, 'name'=> 'Sabana de Mendoza', ]);
		Parish::create([ 'id' => 956, 'municipality_id' => 386, 'name'=> 'Junín', ]);
		Parish::create([ 'id' => 957, 'municipality_id' => 386, 'name'=> 'Valmore Rodríguez', ]);
		Parish::create([ 'id' => 958, 'municipality_id' => 386, 'name'=> 'El Paraíso', ]);
		Parish::create([ 'id' => 959, 'municipality_id' => 387, 'name'=> 'Andrés Linares', ]);
		Parish::create([ 'id' => 960, 'municipality_id' => 387, 'name'=> 'Chiquinquirá', ]);
		Parish::create([ 'id' => 961, 'municipality_id' => 387, 'name'=> 'Cristóbal Mendoza', ]);
		Parish::create([ 'id' => 962, 'municipality_id' => 387, 'name'=> 'Cruz Carrillo', ]);
		Parish::create([ 'id' => 963, 'municipality_id' => 387, 'name'=> 'Matriz', ]);
		Parish::create([ 'id' => 964, 'municipality_id' => 387, 'name'=> 'Monseñor Carrillo', ]);
		Parish::create([ 'id' => 965, 'municipality_id' => 387, 'name'=> 'Tres Esquinas', ]);
		Parish::create([ 'id' => 966, 'municipality_id' => 388, 'name'=> 'Cabimbú', ]);
		Parish::create([ 'id' => 967, 'municipality_id' => 388, 'name'=> 'Jajó', ]);
		Parish::create([ 'id' => 968, 'municipality_id' => 388, 'name'=> 'La Mesa de Esnujaque', ]);
		Parish::create([ 'id' => 969, 'municipality_id' => 388, 'name'=> 'Santiago', ]);
		Parish::create([ 'id' => 970, 'municipality_id' => 388, 'name'=> 'Tuñame', ]);
		Parish::create([ 'id' => 971, 'municipality_id' => 388, 'name'=> 'La Quebrada', ]);
		Parish::create([ 'id' => 972, 'municipality_id' => 389, 'name'=> 'Juan Ignacio Montilla', ]);
		Parish::create([ 'id' => 973, 'municipality_id' => 389, 'name'=> 'La Beatriz', ]);
		Parish::create([ 'id' => 974, 'municipality_id' => 389, 'name'=> 'La Puerta', ]);
		Parish::create([ 'id' => 975, 'municipality_id' => 389, 'name'=> 'Mendoza del Valle de Momboy', ]);
		Parish::create([ 'id' => 976, 'municipality_id' => 389, 'name'=> 'Mercedes Díaz', ]);
		Parish::create([ 'id' => 977, 'municipality_id' => 389, 'name'=> 'San Luis', ]);
		Parish::create([ 'id' => 978, 'municipality_id' => 390, 'name'=> 'Caraballeda', ]);
		Parish::create([ 'id' => 979, 'municipality_id' => 390, 'name'=> 'Carayaca', ]);
		Parish::create([ 'id' => 980, 'municipality_id' => 390, 'name'=> 'Carlos Soublette', ]);
		Parish::create([ 'id' => 981, 'municipality_id' => 390, 'name'=> 'Caruao Chuspa', ]);
		Parish::create([ 'id' => 982, 'municipality_id' => 390, 'name'=> 'Catia La Mar', ]);
		Parish::create([ 'id' => 983, 'municipality_id' => 390, 'name'=> 'El Junko', ]);
		Parish::create([ 'id' => 984, 'municipality_id' => 390, 'name'=> 'La Guaira', ]);
		Parish::create([ 'id' => 985, 'municipality_id' => 390, 'name'=> 'Macuto', ]);
		Parish::create([ 'id' => 986, 'municipality_id' => 390, 'name'=> 'Maiquetía', ]);
		Parish::create([ 'id' => 987, 'municipality_id' => 390, 'name'=> 'Naiguatá', ]);
		Parish::create([ 'id' => 988, 'municipality_id' => 390, 'name'=> 'Urimare', ]);
		Parish::create([ 'id' => 989, 'municipality_id' => 391, 'name'=> 'Arístides Bastidas', ]);
		Parish::create([ 'id' => 990, 'municipality_id' => 392, 'name'=> 'Bolívar', ]);
		Parish::create([ 'id' => 991, 'municipality_id' => 407, 'name'=> 'Chivacoa', ]);
		Parish::create([ 'id' => 992, 'municipality_id' => 407, 'name'=> 'Campo Elías', ]);
		Parish::create([ 'id' => 993, 'municipality_id' => 408, 'name'=> 'Cocorote', ]);
		Parish::create([ 'id' => 994, 'municipality_id' => 409, 'name'=> 'Independencia', ]);
		Parish::create([ 'id' => 995, 'municipality_id' => 410, 'name'=> 'José Antonio Páez', ]);
		Parish::create([ 'id' => 996, 'municipality_id' => 411, 'name'=> 'La Trinidad', ]);
		Parish::create([ 'id' => 997, 'municipality_id' => 412, 'name'=> 'Manuel Monge', ]);
		Parish::create([ 'id' => 998, 'municipality_id' => 413, 'name'=> 'Salóm', ]);
		Parish::create([ 'id' => 999, 'municipality_id' => 413, 'name'=> 'Temerla', ]);
		Parish::create([ 'id' => 1000, 'municipality_id' => 413, 'name'=> 'Nirgua', ]);
		Parish::create([ 'id' => 1001, 'municipality_id' => 414, 'name'=> 'San Andrés', ]);
		Parish::create([ 'id' => 1002, 'municipality_id' => 414, 'name'=> 'Yaritagua', ]);
		Parish::create([ 'id' => 1003, 'municipality_id' => 415, 'name'=> 'San Javier', ]);
		Parish::create([ 'id' => 1004, 'municipality_id' => 415, 'name'=> 'Albarico', ]);
		Parish::create([ 'id' => 1005, 'municipality_id' => 415, 'name'=> 'San Felipe', ]);
		Parish::create([ 'id' => 1006, 'municipality_id' => 416, 'name'=> 'Sucre', ]);
		Parish::create([ 'id' => 1007, 'municipality_id' => 417, 'name'=> 'Urachiche', ]);
		Parish::create([ 'id' => 1008, 'municipality_id' => 418, 'name'=> 'El Guayabo', ]);
		Parish::create([ 'id' => 1009, 'municipality_id' => 418, 'name'=> 'Farriar', ]);
		Parish::create([ 'id' => 1010, 'municipality_id' => 441, 'name'=> 'Isla de Toas', ]);
		Parish::create([ 'id' => 1011, 'municipality_id' => 441, 'name'=> 'Monagas', ]);
		Parish::create([ 'id' => 1012, 'municipality_id' => 442, 'name'=> 'San Timoteo', ]);
		Parish::create([ 'id' => 1013, 'municipality_id' => 442, 'name'=> 'General Urdaneta', ]);
		Parish::create([ 'id' => 1014, 'municipality_id' => 442, 'name'=> 'Libertador', ]);
		Parish::create([ 'id' => 1015, 'municipality_id' => 442, 'name'=> 'Marcelino Briceño', ]);
		Parish::create([ 'id' => 1016, 'municipality_id' => 442, 'name'=> 'Pueblo Nuevo', ]);
		Parish::create([ 'id' => 1017, 'municipality_id' => 442, 'name'=> 'Manuel Guanipa Matos', ]);
		Parish::create([ 'id' => 1018, 'municipality_id' => 443, 'name'=> 'Ambrosio', ]);
		Parish::create([ 'id' => 1019, 'municipality_id' => 443, 'name'=> 'Carmen Herrera', ]);
		Parish::create([ 'id' => 1020, 'municipality_id' => 443, 'name'=> 'La Rosa', ]);
		Parish::create([ 'id' => 1021, 'municipality_id' => 443, 'name'=> 'Germán Ríos Linares', ]);
		Parish::create([ 'id' => 1022, 'municipality_id' => 443, 'name'=> 'San Benito', ]);
		Parish::create([ 'id' => 1023, 'municipality_id' => 443, 'name'=> 'Rómulo Betancourt', ]);
		Parish::create([ 'id' => 1024, 'municipality_id' => 443, 'name'=> 'Jorge Hernández', ]);
		Parish::create([ 'id' => 1025, 'municipality_id' => 443, 'name'=> 'Punta Gorda', ]);
		Parish::create([ 'id' => 1026, 'municipality_id' => 443, 'name'=> 'Arístides Calvani', ]);
		Parish::create([ 'id' => 1027, 'municipality_id' => 444, 'name'=> 'Encontrados', ]);
		Parish::create([ 'id' => 1028, 'municipality_id' => 444, 'name'=> 'Udón Pérez', ]);
		Parish::create([ 'id' => 1029, 'municipality_id' => 445, 'name'=> 'Moralito', ]);
		Parish::create([ 'id' => 1030, 'municipality_id' => 445, 'name'=> 'San Carlos del Zulia', ]);
		Parish::create([ 'id' => 1031, 'municipality_id' => 445, 'name'=> 'Santa Cruz del Zulia', ]);
		Parish::create([ 'id' => 1032, 'municipality_id' => 445, 'name'=> 'Santa Bárbara', ]);
		Parish::create([ 'id' => 1033, 'municipality_id' => 445, 'name'=> 'Urribarrí', ]);
		Parish::create([ 'id' => 1034, 'municipality_id' => 446, 'name'=> 'Carlos Quevedo', ]);
		Parish::create([ 'id' => 1035, 'municipality_id' => 446, 'name'=> 'Francisco Javier Pulgar', ]);
		Parish::create([ 'id' => 1036, 'municipality_id' => 446, 'name'=> 'Simón Rodríguez', ]);
		Parish::create([ 'id' => 1037, 'municipality_id' => 446, 'name'=> 'Guamo-Gavilanes', ]);
		Parish::create([ 'id' => 1038, 'municipality_id' => 448, 'name'=> 'La Concepción', ]);
		Parish::create([ 'id' => 1039, 'municipality_id' => 448, 'name'=> 'San José', ]);
		Parish::create([ 'id' => 1040, 'municipality_id' => 448, 'name'=> 'Mariano Parra León', ]);
		Parish::create([ 'id' => 1041, 'municipality_id' => 448, 'name'=> 'José Ramón Yépez', ]);
		Parish::create([ 'id' => 1042, 'municipality_id' => 449, 'name'=> 'Jesús María Semprún', ]);
		Parish::create([ 'id' => 1043, 'municipality_id' => 449, 'name'=> 'Barí', ]);
		Parish::create([ 'id' => 1044, 'municipality_id' => 450, 'name'=> 'Concepción', ]);
		Parish::create([ 'id' => 1045, 'municipality_id' => 450, 'name'=> 'Andrés Bello', ]);
		Parish::create([ 'id' => 1046, 'municipality_id' => 450, 'name'=> 'Chiquinquirá', ]);
		Parish::create([ 'id' => 1047, 'municipality_id' => 450, 'name'=> 'El Carmelo', ]);
		Parish::create([ 'id' => 1048, 'municipality_id' => 450, 'name'=> 'Potreritos', ]);
		Parish::create([ 'id' => 1049, 'municipality_id' => 451, 'name'=> 'Libertad', ]);
		Parish::create([ 'id' => 1050, 'municipality_id' => 451, 'name'=> 'Alonso de Ojeda', ]);
		Parish::create([ 'id' => 1051, 'municipality_id' => 451, 'name'=> 'Venezuela', ]);
		Parish::create([ 'id' => 1052, 'municipality_id' => 451, 'name'=> 'Eleazar López Contreras', ]);
		Parish::create([ 'id' => 1053, 'municipality_id' => 451, 'name'=> 'Campo Lara', ]);
		Parish::create([ 'id' => 1054, 'municipality_id' => 452, 'name'=> 'Bartolomé de las Casas', ]);
		Parish::create([ 'id' => 1055, 'municipality_id' => 452, 'name'=> 'Libertad', ]);
		Parish::create([ 'id' => 1056, 'municipality_id' => 452, 'name'=> 'Río Negro', ]);
		Parish::create([ 'id' => 1057, 'municipality_id' => 452, 'name'=> 'San José de Perijá', ]);
		Parish::create([ 'id' => 1058, 'municipality_id' => 453, 'name'=> 'San Rafael', ]);
		Parish::create([ 'id' => 1059, 'municipality_id' => 453, 'name'=> 'La Sierrita', ]);
		Parish::create([ 'id' => 1060, 'municipality_id' => 453, 'name'=> 'Las Parcelas', ]);
		Parish::create([ 'id' => 1061, 'municipality_id' => 453, 'name'=> 'Luis de Vicente', ]);
		Parish::create([ 'id' => 1062, 'municipality_id' => 453, 'name'=> 'Monseñor Marcos Sergio Godoy', ]);
		Parish::create([ 'id' => 1063, 'municipality_id' => 453, 'name'=> 'Ricaurte', ]);
		Parish::create([ 'id' => 1064, 'municipality_id' => 453, 'name'=> 'Tamare', ]);
		Parish::create([ 'id' => 1065, 'municipality_id' => 454, 'name'=> 'Antonio Borjas Romero', ]);
		Parish::create([ 'id' => 1066, 'municipality_id' => 454, 'name'=> 'Bolívar', ]);
		Parish::create([ 'id' => 1067, 'municipality_id' => 454, 'name'=> 'Cacique Mara', ]);
		Parish::create([ 'id' => 1068, 'municipality_id' => 454, 'name'=> 'Carracciolo Parra Pérez', ]);
		Parish::create([ 'id' => 1069, 'municipality_id' => 454, 'name'=> 'Cecilio Acosta', ]);
		Parish::create([ 'id' => 1070, 'municipality_id' => 454, 'name'=> 'Cristo de Aranza', ]);
		Parish::create([ 'id' => 1071, 'municipality_id' => 454, 'name'=> 'Coquivacoa', ]);
		Parish::create([ 'id' => 1072, 'municipality_id' => 454, 'name'=> 'Chiquinquirá', ]);
		Parish::create([ 'id' => 1073, 'municipality_id' => 454, 'name'=> 'Francisco Eugenio Bustamante', ]);
		Parish::create([ 'id' => 1074, 'municipality_id' => 454, 'name'=> 'Idelfonzo Vásquez', ]);
		Parish::create([ 'id' => 1075, 'municipality_id' => 454, 'name'=> 'Juana de Ávila', ]);
		Parish::create([ 'id' => 1076, 'municipality_id' => 454, 'name'=> 'Luis Hurtado Higuera', ]);
		Parish::create([ 'id' => 1077, 'municipality_id' => 454, 'name'=> 'Manuel Dagnino', ]);
		Parish::create([ 'id' => 1078, 'municipality_id' => 454, 'name'=> 'Olegario Villalobos', ]);
		Parish::create([ 'id' => 1079, 'municipality_id' => 454, 'name'=> 'Raúl Leoni', ]);
		Parish::create([ 'id' => 1080, 'municipality_id' => 454, 'name'=> 'Santa Lucía', ]);
		Parish::create([ 'id' => 1081, 'municipality_id' => 454, 'name'=> 'Venancio Pulgar', ]);
		Parish::create([ 'id' => 1082, 'municipality_id' => 454, 'name'=> 'San Isidro', ]);
		Parish::create([ 'id' => 1083, 'municipality_id' => 455, 'name'=> 'Altagracia', ]);
		Parish::create([ 'id' => 1084, 'municipality_id' => 455, 'name'=> 'Faría', ]);
		Parish::create([ 'id' => 1085, 'municipality_id' => 455, 'name'=> 'Ana María Campos', ]);
		Parish::create([ 'id' => 1086, 'municipality_id' => 455, 'name'=> 'San Antonio', ]);
		Parish::create([ 'id' => 1087, 'municipality_id' => 455, 'name'=> 'San José', ]);
		Parish::create([ 'id' => 1088, 'municipality_id' => 456, 'name'=> 'Donaldo García', ]);
		Parish::create([ 'id' => 1089, 'municipality_id' => 456, 'name'=> 'El Rosario', ]);
		Parish::create([ 'id' => 1090, 'municipality_id' => 456, 'name'=> 'Sixto Zambrano', ]);
		Parish::create([ 'id' => 1091, 'municipality_id' => 457, 'name'=> 'San Francisco', ]);
		Parish::create([ 'id' => 1092, 'municipality_id' => 457, 'name'=> 'El Bajo', ]);
		Parish::create([ 'id' => 1093, 'municipality_id' => 457, 'name'=> 'Domitila Flores', ]);
		Parish::create([ 'id' => 1094, 'municipality_id' => 457, 'name'=> 'Francisco Ochoa', ]);
		Parish::create([ 'id' => 1095, 'municipality_id' => 457, 'name'=> 'Los Cortijos', ]);
		Parish::create([ 'id' => 1096, 'municipality_id' => 457, 'name'=> 'Marcial Hernández', ]);
		Parish::create([ 'id' => 1097, 'municipality_id' => 458, 'name'=> 'Santa Rita', ]);
		Parish::create([ 'id' => 1098, 'municipality_id' => 458, 'name'=> 'El Mene', ]);
		Parish::create([ 'id' => 1099, 'municipality_id' => 458, 'name'=> 'Pedro Lucas Urribarrí', ]);
		Parish::create([ 'id' => 1100, 'municipality_id' => 458, 'name'=> 'José Cenobio Urribarrí', ]);
		Parish::create([ 'id' => 1101, 'municipality_id' => 459, 'name'=> 'Rafael Maria Baralt', ]);
		Parish::create([ 'id' => 1102, 'municipality_id' => 459, 'name'=> 'Manuel Manrique', ]);
		Parish::create([ 'id' => 1103, 'municipality_id' => 459, 'name'=> 'Rafael Urdaneta', ]);
		Parish::create([ 'id' => 1104, 'municipality_id' => 460, 'name'=> 'Bobures', ]);
		Parish::create([ 'id' => 1105, 'municipality_id' => 460, 'name'=> 'Gibraltar', ]);
		Parish::create([ 'id' => 1106, 'municipality_id' => 460, 'name'=> 'Heras', ]);
		Parish::create([ 'id' => 1107, 'municipality_id' => 460, 'name'=> 'Monseñor Arturo Álvarez', ]);
		Parish::create([ 'id' => 1108, 'municipality_id' => 460, 'name'=> 'Rómulo Gallegos', ]);
		Parish::create([ 'id' => 1109, 'municipality_id' => 460, 'name'=> 'El Batey', ]);
		Parish::create([ 'id' => 1110, 'municipality_id' => 461, 'name'=> 'Rafael Urdaneta', ]);
		Parish::create([ 'id' => 1111, 'municipality_id' => 461, 'name'=> 'La Victoria', ]);
		Parish::create([ 'id' => 1112, 'municipality_id' => 461, 'name'=> 'Raúl Cuenca', ]);
		Parish::create([ 'id' => 1113, 'municipality_id' => 447, 'name'=> 'Sinamaica', ]);
		Parish::create([ 'id' => 1114, 'municipality_id' => 447, 'name'=> 'Alta Guajira', ]);
		Parish::create([ 'id' => 1115, 'municipality_id' => 447, 'name'=> 'Elías Sánchez Rubio', ]);
		Parish::create([ 'id' => 1116, 'municipality_id' => 447, 'name'=> 'Guajira', ]);
		Parish::create([ 'id' => 1117, 'municipality_id' => 462, 'name'=> 'Altagracia', ]);
		Parish::create([ 'id' => 1118, 'municipality_id' => 462, 'name'=> 'Antímano', ]);
		Parish::create([ 'id' => 1119, 'municipality_id' => 462, 'name'=> 'Caricuao', ]);
		Parish::create([ 'id' => 1120, 'municipality_id' => 462, 'name'=> 'Catedral', ]);
		Parish::create([ 'id' => 1121, 'municipality_id' => 462, 'name'=> 'Coche', ]);
		Parish::create([ 'id' => 1122, 'municipality_id' => 462, 'name'=> 'El Junquito', ]);
		Parish::create([ 'id' => 1123, 'municipality_id' => 462, 'name'=> 'El Paraíso', ]);
		Parish::create([ 'id' => 1124, 'municipality_id' => 462, 'name'=> 'El Recreo', ]);
		Parish::create([ 'id' => 1125, 'municipality_id' => 462, 'name'=> 'El Valle', ]);
		Parish::create([ 'id' => 1126, 'municipality_id' => 462, 'name'=> 'La Candelaria', ]);
		Parish::create([ 'id' => 1127, 'municipality_id' => 462, 'name'=> 'La Pastora', ]);
		Parish::create([ 'id' => 1128, 'municipality_id' => 462, 'name'=> 'La Vega', ]);
		Parish::create([ 'id' => 1129, 'municipality_id' => 462, 'name'=> 'Macarao', ]);
		Parish::create([ 'id' => 1130, 'municipality_id' => 462, 'name'=> 'San Agustín', ]);
		Parish::create([ 'id' => 1131, 'municipality_id' => 462, 'name'=> 'San Bernardino', ]);
		Parish::create([ 'id' => 1132, 'municipality_id' => 462, 'name'=> 'San José', ]);
		Parish::create([ 'id' => 1133, 'municipality_id' => 462, 'name'=> 'San Juan', ]);
		Parish::create([ 'id' => 1134, 'municipality_id' => 462, 'name'=> 'San Pedro', ]);
		Parish::create([ 'id' => 1135, 'municipality_id' => 462, 'name'=> 'Santa Rosalía', ]);
		Parish::create([ 'id' => 1136, 'municipality_id' => 462, 'name'=> 'Santa Teresa', ]);
		Parish::create([ 'id' => 1137, 'municipality_id' => 462, 'name'=> 'Sucre (Catia)', ]);
		Parish::create([ 'id' => 1138, 'municipality_id' => 462, 'name'=> '23 de enero', ]);
    }
}
